/*******************************************************************************
 * Script: seed_DimCourseAssessment_dev_testset.sql   (DEV ONLY)
 * Purpose: Course-scoped entry mapping for the synthetic ingest TEST SET
 *          (generated by data/imports/_generate_ingest_testset.ps1). Every
 *          MAT-* -> Math (Language NULL); ELA-* -> English Literacy;
 *          FLA-* -> French Literacy. Idempotent: clears then re-seeds.
 *          Run on DEV after ingesting the test set so entry resolves courses.
 * Region: Canada East (PIIDPA compliant)
 ******************************************************************************/

DELETE FROM DimCourseAssessment;

INSERT INTO DimCourseAssessment (CourseCode, Language, Kind, ActiveFlag, Notes, LastUpdated) VALUES
    ('MAT-P-EN', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('ELA-P-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('MAT-1-EN', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('ELA-1-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('MAT-4-EN', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('ELA-4-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('MAT-5-EN', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('ELA-5-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('MAT-P1-EN', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('ELA-P1-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('MAT-45-EN', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('ELA-45-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('MAT-P-EI', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('FLA-P-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('MAT-1-EI', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('FLA-1-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('MAT-4-EI', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('FLA-4-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('MAT-5-EI', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('FLA-5-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('MAT-P1-EI', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('FLA-P1-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('MAT-45-EI', NULL, 'Math', 1, 'testset (Math)', GETDATE()),
    ('FLA-45-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('ELA-7-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('ELA-8-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('ELA-78-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('FLA-7-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('ELA-7-EI', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('FLA-8-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('ELA-8-EI', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('FLA-78-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('ELA-78-EI', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('FLA-78-LI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('ELA-78-LI', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('ELA-10-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('ELA-11-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('ELA-1011-EN', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('FLA-10-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('ELA-10-EI', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('FLA-11-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('ELA-11-EI', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE()),
    ('FLA-1011-EI', 'French', 'Literacy', 1, 'testset (FLA)', GETDATE()),
    ('ELA-1011-EI', 'English', 'Literacy', 1, 'testset (ELA)', GETDATE());

SELECT Language, Kind, COUNT(*) AS Courses FROM DimCourseAssessment GROUP BY Language, Kind ORDER BY Kind, Language;