/* ============================================================================
   STAGE 01 — schema migrations on existing live tables (RUN ONCE)
   GENERATED by scripts/generate_live_deploy.sh — do not hand-edit; edit sources + regen.
   0.5.0 live deploy. Run DEV first. Run stages in filename order.
   ============================================================================ */

/* ========== sql/scripts/migrate_DimProgram_add_ScopeBucket.sql ========== */
/*******************************************************************************
 * Script: migrate_DimProgram_add_ScopeBucket.sql
 * Purpose: Classify each program into the cycle PROGRAM-SCOPE bucket used by the
 *          /cycles multi-select: 'English' | 'Early Immersion' | 'Late Immersion'.
 *          This is a FACTUAL property of each PowerSchool program code (early vs
 *          late immersion is otherwise only implicit in the program name), so it
 *          lives in DimProgram rather than being derived in a TVF.
 *          Rule (per user 2026-09-17): anything NOT French Immersion folds into
 *          'English' (incl. French Second Language). FI + name contains 'Late' ->
 *          'Late Immersion'; other FI (incl. 'Elementary French Immersion') -> 'Early'.
 * Run ONCE. GO-separated (add column, then backfill). ADD COLUMN + UPDATE supported.
 * Region: Canada East (PIIDPA compliant)
 ******************************************************************************/

IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('dbo.DimProgram') AND name = 'ScopeBucket'
)
BEGIN
    ALTER TABLE dbo.DimProgram ADD ScopeBucket VARCHAR(20) NULL;
END;
GO

UPDATE dbo.DimProgram
SET ScopeBucket =
    CASE WHEN IsImmersion = 0            THEN 'English'          -- non-immersion (incl. FSL) folds into English
         WHEN ProgramName LIKE '%Late%'  THEN 'Late Immersion'
         ELSE 'Early Immersion' END;
GO

-- Verify the split (expect Late = J020/S020/S120/S220; Early = E015/J015/S015/S115/S215; rest English).
SELECT ScopeBucket, COUNT(*) AS Programs, STRING_AGG(ProgramCode, ', ') AS Codes
FROM dbo.DimProgram GROUP BY ScopeBucket ORDER BY ScopeBucket;
GO


/* ========== sql/scripts/migrate_DimAssessmentWindow_add_AssessmentLanguage.sql ========== */
/*******************************************************************************
 * Script: migrate_DimAssessmentWindow_add_AssessmentLanguage.sql
 * Purpose: App-level per-cycle scoping. Adds two columns to DimAssessmentWindow so
 *          a Short Cycle can be scoped, from the /cycles page, along:
 *            AssessmentLanguage  'English'|'French' (NULL = Both: writing toggle /
 *                                reading per student).
 *            ProgramScope        comma-delimited bucket set from
 *                                {English, Early Immersion, Late Immersion}
 *                                (NULL = all programs). Buckets come from
 *                                DimProgram.ScopeBucket (non-immersion -> English).
 *          These combine with the existing MinGrade/MaxGrade grade band. Membership
 *          follows the structural rule (French literacy = French Immersion); WHICH
 *          grades/programs/language a cycle covers is this config, not hardcoded.
 *          The writing RESULT keeps its own AssessmentLanguage (storage); these
 *          scope the CYCLE.
 * Run ONCE. GO-separated. ADD COLUMN supported in Fabric.
 * Region: Canada East (PIIDPA compliant)
 ******************************************************************************/

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.DimAssessmentWindow') AND name = 'AssessmentLanguage')
BEGIN
    ALTER TABLE dbo.DimAssessmentWindow ADD AssessmentLanguage VARCHAR(10) NULL;
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.DimAssessmentWindow') AND name = 'ProgramScope')
BEGIN
    ALTER TABLE dbo.DimAssessmentWindow ADD ProgramScope VARCHAR(100) NULL;
END;
GO

-- Existing cycles stay NULL on both (= Both / all programs) = today's behaviour. No backfill.
SELECT TOP 5 AssessmentWindowID, WindowName, AssessmentType, ProgramScope, ScaleSystem, AssessmentLanguage, MinGrade, MaxGrade
FROM dbo.DimAssessmentWindow ORDER BY AssessmentWindowID DESC;
GO


/* ========== sql/scripts/migrate_DimAssessmentWindow_add_CycleGroupID.sql ========== */
/*******************************************************************************
 * Migration: add DimAssessmentWindow.CycleGroupID
 * Purpose: A "Short Cycle of Response" can cover MULTIPLE subjects (Reading,
 *          Writing, Math) over one date range. Each subject is still its own
 *          DimAssessmentWindow row (facts tie to a single-subject window), so the
 *          rows of one cycle are grouped by a shared CycleGroupID (a GUID the app
 *          generates). This keeps per-subject storage flexible — a cycle could
 *          later carry different dates/grades per subject with no schema change —
 *          while letting the admin manage it as one cycle.
 * Created: 2026-08-27
 * Region: Canada East (PIIDPA compliant)
 *
 * Run once against dev, then live. Nullable add — non-breaking; existing rows
 * (legacy single windows) get NULL and are treated as their own one-subject cycle.
 *
 * Fabric note: run the ALTER on its OWN batch (Fabric parses the whole batch
 * against the pre-ALTER catalog). The proc/reads that use it deploy after.
 ******************************************************************************/

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.DimAssessmentWindow') AND name = 'CycleGroupID')
BEGIN
    ALTER TABLE dbo.DimAssessmentWindow ADD CycleGroupID VARCHAR(36) NULL;
END;
GO


/* ========== sql/scripts/migrate_FactWriting_conventions_varchar.sql ========== */
/*******************************************************************************
 * Script: migrate_FactWriting_conventions_varchar.sql
 * Purpose: Change FactAssessmentWriting.ConventionsScore from INT to VARCHAR(10)
 *          so it can hold the "SCR" (Scribed) code alongside '1'-'4'. Fabric has no
 *          ALTER COLUMN (type change) and we avoid a full table rebuild, so this does
 *          a multi-step column swap that PRESERVES existing data and the column NAME:
 *            add temp VARCHAR -> copy INT->VARCHAR -> drop INT col -> re-add VARCHAR
 *            under the original name -> copy back -> drop temp.
 *          Each step is its own batch (GO) so the parser only sees existing columns
 *          (see the fabric-warehouse-sql skill: catalog-check-in-same-batch gotcha).
 * SCR = Scribed on Conventions only (someone else physically wrote for the student, so
 *          conventions aren't the student's own production). SCR is OMITTED from the
 *          writing average (sum/count over the SCORED traits) — see the reads + proc.
 * Created: 2026-09-17
 * Region: Canada East (PIIDPA compliant)
 *
 * RUN ONCE per warehouse (dev, then live at the 0.5.0 release). Ideas/Organization/
 * Language stay INT. Safe on an empty table too (the UPDATEs just touch 0 rows).
 ******************************************************************************/

-- IDEMPOTENT: every batch is guarded so the swap runs ONLY while ConventionsScore is still INT
-- (system_type_id 56). Once it is VARCHAR (167) every guard is false and the whole script no-ops —
-- safe to re-run, and safe on a dev warehouse that already converted. int=56, varchar=167 are fixed.

-- 1) temp VARCHAR column, seeded from the existing INT — only while conversion is pending.
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'ConventionsScore' AND system_type_id = 56)
   AND NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'ConventionsScoreTmp')
BEGIN
    ALTER TABLE dbo.FactAssessmentWriting ADD ConventionsScoreTmp VARCHAR(10) NULL;
END;
GO
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'ConventionsScoreTmp')
   AND EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'ConventionsScore' AND system_type_id = 56)
BEGIN
    UPDATE dbo.FactAssessmentWriting
       SET ConventionsScoreTmp = CAST(ConventionsScore AS VARCHAR(10))
     WHERE ConventionsScore IS NOT NULL;
END;
GO

-- 2) drop the INT column, re-add it as VARCHAR (same name) — only while the INT still exists + tmp is staged.
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'ConventionsScore' AND system_type_id = 56)
   AND EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'ConventionsScoreTmp')
BEGIN
    ALTER TABLE dbo.FactAssessmentWriting DROP COLUMN ConventionsScore;
END;
GO
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'ConventionsScore')
   AND EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'ConventionsScoreTmp')
BEGIN
    ALTER TABLE dbo.FactAssessmentWriting ADD ConventionsScore VARCHAR(10) NULL;
END;
GO

-- 3) copy back and drop the temp — only while the temp is still present.
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'ConventionsScoreTmp')
BEGIN
    UPDATE dbo.FactAssessmentWriting
       SET ConventionsScore = ConventionsScoreTmp
     WHERE ConventionsScoreTmp IS NOT NULL;
END;
GO
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'ConventionsScoreTmp')
BEGIN
    ALTER TABLE dbo.FactAssessmentWriting DROP COLUMN ConventionsScoreTmp;
END;
GO

-- verify (dev/synthetic — safe to display): distinct conventions values now include codes.
SELECT ConventionsScore, COUNT(*) AS Rows
FROM FactAssessmentWriting
GROUP BY ConventionsScore
ORDER BY ConventionsScore;
GO


/* ========== sql/scripts/migrate_FactWriting_add_AssessmentLanguage.sql ========== */
/*******************************************************************************
 * Script: migrate_FactWriting_add_AssessmentLanguage.sql
 * Purpose: Dual-language writing. Add AssessmentLanguage to FactAssessmentWriting
 *          so a French-Immersion grade-3+ student can hold BOTH an English and a
 *          French writing result per cycle. Grain becomes
 *          (StudentKey, AssessmentWindowID, AssessmentLanguage, AssessmentDate).
 *
 * Backfill: existing rows predate dual-track, so they are the language of the
 *          student's PROGRAM -- English/FSL program -> 'English', French Immersion
 *          -> 'French' (per user, 2026-09-17). Joined on the exact SCD version the
 *          fact points to (StudentKey surrogate), not IsCurrent.
 * Run ONCE. GO-separated: the ADD COLUMN and the UPDATE that references the new
 *          column MUST be in separate batches -- Fabric parses a batch as a unit,
 *          so a column added and used in the same batch raises Msg 207
 *          (Invalid column name). ADD COLUMN + UPDATE are supported (no ALTER-type).
 * Region: Canada East (PIIDPA compliant)
 ******************************************************************************/

-- 1) Add the column (nullable so the ADD succeeds; backfilled below, then always
--    supplied by usp_UpsertWritingAssessment going forward).
IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'AssessmentLanguage'
)
BEGIN
    ALTER TABLE dbo.FactAssessmentWriting ADD AssessmentLanguage VARCHAR(10) NULL;
END;
GO

-- 2) Backfill existing rows by program family (FI -> French; everything else -> English).
--    Separate batch so AssessmentLanguage is already committed and parseable here.
UPDATE faw
SET AssessmentLanguage =
        CASE WHEN dp.ProgramFamily = 'French Immersion' THEN 'French' ELSE 'English' END
FROM dbo.FactAssessmentWriting faw
JOIN dbo.DimStudent s  ON s.StudentKey  = faw.StudentKey       -- exact SCD version the fact references
JOIN dbo.DimProgram dp ON dp.ProgramCode = s.ProgramCode
WHERE faw.AssessmentLanguage IS NULL;
GO

-- 3) Verify: no NULLs remain, and the split looks right.
SELECT AssessmentLanguage, COUNT(*) AS Rows
FROM dbo.FactAssessmentWriting
GROUP BY AssessmentLanguage
ORDER BY AssessmentLanguage;
GO


/* ========== sql/scripts/migrate_FactAssessmentReading_add_score_context.sql ========== */
/*******************************************************************************
 * Script: migrate_FactAssessmentReading_add_score_context.sql
 * Purpose: Make each FactAssessmentReading row SELF-CONTAINED — the actual level
 *          and the expected min/max range are stamped ON the row, alongside the
 *          already-stored ReadingDelta. So a PowerBI export (or any later read)
 *          shows "scored M, expected K-L, delta +1" WITHOUT joining dimensions
 *          whose values could have shifted, and can never disagree with itself.
 *
 *          Adds: LevelCode, ExpectedMinLevelCode, ExpectedMaxLevelCode (VARCHAR(10)).
 *          ReadingScaleID + ReadingDelta are unchanged. The numeric orders are NOT
 *          stored — they only ever fed the delta, which we already have.
 *
 * Created: 2026-09-21
 * Region:  Canada East (PIIDPA compliant)
 * Run on:  DEV and LIVE (same script). Reading is already live, so this is a real
 *          ALTER + backfill of production rows.
 *
 * Backfill is EXACT: benchmarks are UNCHANGED since go-live (confirmed by user
 * 2026-09-21), and the resolution below MIRRORS usp_UpsertReadingAssessment
 * exactly, so the backfilled expected range reconciles with each row's stored
 * ReadingDelta:
 *   LevelCode     <- DimReadingScale by the row's ReadingScaleID
 *   ScaleSystem   <- same DimReadingScale row (the scale the entered level lives in)
 *   Grade + ProgramFamily <- the row's FROZEN DimStudent version (StudentKey) -> DimProgram
 *   DominantMonth <- the window's BenchmarkMonth, else the calendar month with the
 *                    most days in [StartDate, EndDate] (ties -> lower month)
 *   Expected min/max <- DimReadingBenchmark(ScaleSystem, ProgramFamily, Grade, Month)
 * A row with no matching benchmark (the same tolerated edge case the proc warns on)
 * keeps NULL expected + its already-NULL delta.
 *
 * RUN ONCE per environment: the ALTER errors if the columns already exist. The
 * backfill UPDATE is safe to re-run (it re-writes the same values).
 ******************************************************************************/

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentReading') AND name = 'LevelCode')
BEGIN
    ALTER TABLE dbo.FactAssessmentReading
        ADD LevelCode            VARCHAR(10) NULL,
            ExpectedMinLevelCode VARCHAR(10) NULL,
            ExpectedMaxLevelCode VARCHAR(10) NULL;
END;
GO

-- Window dominant month, computed once per window (same lever the proc + read TVFs use).
WITH WinMonth AS (
    SELECT
        w.AssessmentWindowID,
        COALESCE(
            w.BenchmarkMonth,
            (SELECT TOP 1 dc.Month
             FROM DimCalendar dc
             WHERE dc.Date BETWEEN w.StartDate AND w.EndDate
             GROUP BY dc.Month
             ORDER BY COUNT(*) DESC, dc.Month)
        ) AS DominantMonth
    FROM DimAssessmentWindow w
)
UPDATE f
SET f.LevelCode            = drs.LevelCode,
    f.ExpectedMinLevelCode = b.ExpectedMinLevel,
    f.ExpectedMaxLevelCode = b.ExpectedMaxLevel
FROM FactAssessmentReading f
INNER JOIN DimReadingScale drs
        ON drs.ReadingScaleID = f.ReadingScaleID   -- unique by ID; no ActiveFlag filter (want it either way)
INNER JOIN DimStudent s
        ON s.StudentKey = f.StudentKey             -- the row's frozen SCD version = as-was grade/program
INNER JOIN DimProgram dp
        ON dp.ProgramCode = s.ProgramCode
INNER JOIN WinMonth wm
        ON wm.AssessmentWindowID = f.AssessmentWindowID
-- LEFT so rows with no benchmark keep NULL expected (matches the proc's tolerated edge case), and
-- '=' on ProgramFamily matches the proc (a NULL-ProgramFamily benchmark row is not matched here
-- either, so stored expected stays consistent with the stored delta).
LEFT JOIN DimReadingBenchmark b
       ON b.ScaleSystem     = drs.ScaleSystem
      AND b.ProgramFamily   = dp.ProgramFamily
      AND b.GradeCode       = s.Grade
      AND b.AssessmentMonth = wm.DominantMonth;
GO

-- Verify: no self-contradiction — a row with a delta should now carry an expected range.
SELECT
    'rows'                AS Metric, COUNT(*)                                        AS Value FROM FactAssessmentReading
UNION ALL SELECT 'with LevelCode',        COUNT(LevelCode)            FROM FactAssessmentReading
UNION ALL SELECT 'delta set, expected NULL (investigate if >0)',
    SUM(CASE WHEN ReadingDelta IS NOT NULL AND ExpectedMinLevelCode IS NULL THEN 1 ELSE 0 END)
    FROM FactAssessmentReading;


/* ========== sql/scripts/migrate_FactAssessmentWriting_add_average.sql ========== */
/*******************************************************************************
 * Script: migrate_FactAssessmentWriting_add_average.sql
 * Purpose: Store the SCR-aware writing AVERAGE on each FactAssessmentWriting row,
 *          stamped as-was, so the "Scribed drops from the average" rule lives in
 *          the DATA and can't be re-derived wrong later (or disagree with a
 *          report that recomputes it). Conventions='SCR' drops from BOTH the
 *          numerator and the denominator; Ideas/Org/Language are 1-4.
 *
 * Created: 2026-09-21
 * Region:  Canada East (PIIDPA compliant)
 *
 * Run on:  DEV and LIVE (same script). FactAssessmentWriting is already live
 *          (confirmed 2026-09-21), so this is a real ALTER + backfill of
 *          production rows, exactly like the reading migration.
 *
 * RUN ONCE per environment: the ALTER errors if the column already exists. The
 * backfill UPDATE is safe to re-run (it re-writes the same values).
 ******************************************************************************/

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.FactAssessmentWriting') AND name = 'WritingAverage')
BEGIN
    ALTER TABLE dbo.FactAssessmentWriting ADD WritingAverage DECIMAL(4,2) NULL;
END;
GO

-- Backfill from the stored trait scores, exactly as usp_UpsertWritingAssessment now computes it:
-- TRY_CAST turns 'SCR' into NULL so it drops from the mean; the denominator is 3 (+1 when
-- Conventions is numeric). Guarded to complete rows (all three numeric traits present) — incomplete
-- rows should not exist, but this keeps the average NULL rather than wrong if one slipped through.
UPDATE FactAssessmentWriting
SET WritingAverage =
        CAST(IdeasScore + OrganizationScore + LanguageScore
             + COALESCE(TRY_CAST(ConventionsScore AS INT), 0) AS DECIMAL(6,4))
        / (3 + CASE WHEN TRY_CAST(ConventionsScore AS INT) IS NULL THEN 0 ELSE 1 END)
WHERE IdeasScore IS NOT NULL
  AND OrganizationScore IS NOT NULL
  AND LanguageScore IS NOT NULL;
GO

-- Verify.
SELECT
    'rows'                    AS Metric, COUNT(*)                     AS Value FROM FactAssessmentWriting
UNION ALL SELECT 'with WritingAverage', COUNT(WritingAverage)        FROM FactAssessmentWriting
UNION ALL SELECT 'SCR rows (avg over 3)',
    SUM(CASE WHEN ConventionsScore = 'SCR' THEN 1 ELSE 0 END)        FROM FactAssessmentWriting;


