/* ============================================================================
   STAGE 02 — tables new in 0.5.0 (+ seeds/backfills)
   GENERATED by scripts/generate_live_deploy.sh — do not hand-edit; edit sources + regen.
   0.5.0 live deploy. Run DEV first. Run stages in filename order.
   ============================================================================ */

/* ========== sql/dimensions/DimCourseAssessment.sql ========== */
/*******************************************************************************
 * Table: DimCourseAssessment
 * Purpose: Maps a PowerSchool course code (DimSection.CourseCode) to the
 *          assessment it lets a teacher enter -- the LANGUAGE and KIND. Drives
 *          course-scoped entry: a teacher only enters for sections whose course is
 *          in this table, and the course supplies the language (so no EN/FR toggle).
 *
 *          Data-driven on PURPOSE: add/remove a course = insert/delete a row here,
 *          never a code change. Seed the real course list on live
 *          (seed_DimCourseAssessment_live.sql) and the synthetic dev codes on dev
 *          (seed_DimCourseAssessment_dev.sql); the app/TVF logic is identical.
 *
 *   Kind = 'Literacy' -> the course teacher enters BOTH Reading and Writing in
 *          Language ('English' | 'French'). A Language-Arts course covers both.
 *   Kind = 'Math'     -> Math (Language NULL; Math is single-track P-6).
 * SCD Type: N/A (reference/config; managed manually)
 * Created: 2026-09-17
 * Region: Canada East (PIIDPA compliant)
 ******************************************************************************/

CREATE TABLE DimCourseAssessment (
    CourseCode    VARCHAR(50)   NOT NULL,   -- matches DimSection.CourseCode
    Language      VARCHAR(10)   NULL,       -- 'English' | 'French' | NULL (Math)
    Kind          VARCHAR(20)   NOT NULL,   -- 'Literacy' (Reading+Writing) | 'Math'
    ActiveFlag    BIT           NOT NULL,
    Notes         VARCHAR(200)  NULL,       -- e.g. bucket name ('ELA P-12', 'FLA', 'Immersion ELA 3-6', 'Math P-6')
    LastUpdated   DATETIME2(0)  NOT NULL
);


/* ========== sql/scripts/seed_DimCourseAssessment_live.sql ========== */
/*******************************************************************************
 * Script: seed_DimCourseAssessment_live.sql
 * Purpose: LIVE seed of DimCourseAssessment from the real PowerSchool course list
 *          (docs/course-assessment-mapping.md, provided 2026-09-17).
 *            ELA P-12 + Immersion ELA 3-6 -> English literacy
 *            FLA                            -> French literacy
 *            Math                           -> Math
 *          A Language-Arts course = Reading + Writing in its language.
 * Idempotent: clears then re-seeds. Add/remove a course later = INSERT/DELETE a row.
 * VERIFY the codes against a clean PS export before running on live -- the source
 *          table was pasted and had a few dupes/typos (see the docs note).
 * Region: Canada East (PIIDPA compliant)
 ******************************************************************************/

DELETE FROM DimCourseAssessment;

-- ELA P-12 (English-program + immersion 7-12 English LA) -> English literacy
INSERT INTO DimCourseAssessment (CourseCode, Language, Kind, ActiveFlag, Notes, LastUpdated) VALUES
    ('ENG15PR','English','Literacy',1,'ELA P-12',GETDATE()),('ENG15PRIP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG151','English','Literacy',1,'ELA P-12',GETDATE()),('ENG151IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG152','English','Literacy',1,'ELA P-12',GETDATE()),('ENG152IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG153','English','Literacy',1,'ELA P-12',GETDATE()),('ENG153IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG164','English','Literacy',1,'ELA P-12',GETDATE()),('ENG4IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG165','English','Literacy',1,'ELA P-12',GETDATE()),('ENG5IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG166','English','Literacy',1,'ELA P-12',GETDATE()),('ENG6IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG187','English','Literacy',1,'ELA P-12',GETDATE()),('ENG7IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG188','English','Literacy',1,'ELA P-12',GETDATE()),('ENG8IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG9','English','Literacy',1,'ELA P-12',GETDATE()),('ENG9IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG10','English','Literacy',1,'ELA P-12',GETDATE()),('ENG10IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG10O2','English','Literacy',1,'ELA P-12',GETDATE()),('EN10P','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG10PIP','English','Literacy',1,'ELA P-12',GETDATE()),('ENG11C','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG11','English','Literacy',1,'ELA P-12',GETDATE()),('ENG11O2','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG11IP','English','Literacy',1,'ELA P-12',GETDATE()),('ENG11ADV','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG12','English','Literacy',1,'ELA P-12',GETDATE()),('ENG12IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG12ADV','English','Literacy',1,'ELA P-12',GETDATE()),('ECM11','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ECM11IP','English','Literacy',1,'ELA P-12',GETDATE()),('ECM12','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ECM12IP','English','Literacy',1,'ELA P-12',GETDATE()),('ECM12O2','English','Literacy',1,'ELA P-12',GETDATE()),
    ('EN10PIP','English','Literacy',1,'ELA P-12',GETDATE()),('ENG10PRE','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG12O2','English','Literacy',1,'ELA P-12',GETDATE()),('IBENG11','English','Literacy',1,'ELA P-12',GETDATE()),
    ('IBENG12HL','English','Literacy',1,'ELA P-12',GETDATE()),('IBENG12SL','English','Literacy',1,'ELA P-12',GETDATE()),
    ('LAL10','English','Literacy',1,'ELA P-12',GETDATE()),('ENGAH12','English','Literacy',1,'ELA P-12',GETDATE()),
    ('CANLIT12','English','Literacy',1,'ELA P-12',GETDATE()),('CLT12IP','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG12C','English','Literacy',1,'ELA P-12',GETDATE()),('ECM11O2','English','Literacy',1,'ELA P-12',GETDATE()),
    ('ENG12AP','English','Literacy',1,'ELA P-12',GETDATE());

-- Immersion ELA 3-6 (early-immersion English LA) -> English literacy
INSERT INTO DimCourseAssessment (CourseCode, Language, Kind, ActiveFlag, Notes, LastUpdated) VALUES
    ('ELAANG3','English','Literacy',1,'Immersion ELA 3-6',GETDATE()),('ELA3IP','English','Literacy',1,'Immersion ELA 3-6',GETDATE()),
    ('ELAANG164','English','Literacy',1,'Immersion ELA 3-6',GETDATE()),('ELA4IP','English','Literacy',1,'Immersion ELA 3-6',GETDATE()),
    ('ELAANG165','English','Literacy',1,'Immersion ELA 3-6',GETDATE()),('ELA5IP','English','Literacy',1,'Immersion ELA 3-6',GETDATE()),
    ('ELAANG166','English','Literacy',1,'Immersion ELA 3-6',GETDATE()),('ELA6IP','English','Literacy',1,'Immersion ELA 3-6',GETDATE());

-- FLA (Francais / French Immersion LA) -> French literacy
INSERT INTO DimCourseAssessment (CourseCode, Language, Kind, ActiveFlag, Notes, LastUpdated) VALUES
    ('FR151IM','French','Literacy',1,'FLA',GETDATE()),('FR151IMIP','French','Literacy',1,'FLA',GETDATE()),
    ('FR15PRIM','French','Literacy',1,'FLA',GETDATE()),('FR151PRIMIP','French','Literacy',1,'FLA',GETDATE()),
    ('FR152IM','French','Literacy',1,'FLA',GETDATE()),('FR152IMIP','French','Literacy',1,'FLA',GETDATE()),
    ('FR153IM','French','Literacy',1,'FLA',GETDATE()),('FR153IMIP','French','Literacy',1,'FLA',GETDATE()),
    ('FR164IM','French','Literacy',1,'FLA',GETDATE()),('FR165IM','French','Literacy',1,'FLA',GETDATE()),
    ('FRAFLA4IP','French','Literacy',1,'FLA',GETDATE()),('FRAFLA5IP','French','Literacy',1,'FLA',GETDATE()),
    ('FRAFLA6IP','French','Literacy',1,'FLA',GETDATE()),('FR166IM','French','Literacy',1,'FLA',GETDATE()),
    ('FR187EIM','French','Literacy',1,'FLA',GETDATE()),('FR188EIM','French','Literacy',1,'FLA',GETDATE()),
    ('FR9EIM','French','Literacy',1,'FLA',GETDATE()),('FR10IM','French','Literacy',1,'FLA',GETDATE()),
    ('FR11IM','French','Literacy',1,'FLA',GETDATE()),('FR12IM','French','Literacy',1,'FLA',GETDATE()),
    ('FR187LIM','French','Literacy',1,'FLA',GETDATE()),('FR188LIM','French','Literacy',1,'FLA',GETDATE()),
    ('FR6IN','French','Literacy',1,'FLA',GETDATE()),('FRA8IMIP','French','Literacy',1,'FLA',GETDATE()),
    ('FRAFR6INIP','French','Literacy',1,'FLA',GETDATE()),('FR9IMIP','French','Literacy',1,'FLA',GETDATE()),
    ('FRA10IMIP','French','Literacy',1,'FLA',GETDATE()),('FRA11IMIP','French','Literacy',1,'FLA',GETDATE()),
    ('FRA12IMIP','French','Literacy',1,'FLA',GETDATE()),('FRA10PREBI','French','Literacy',1,'FLA',GETDATE()),
    ('FRA7IMIP','French','Literacy',1,'FLA',GETDATE());

-- Math P-6 (Math single-track) -> Math
INSERT INTO DimCourseAssessment (CourseCode, Language, Kind, ActiveFlag, Notes, LastUpdated) VALUES
    ('MT15PR',NULL,'Math',1,'Math P-6',GETDATE()),('MT15PRIP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MT151',NULL,'Math',1,'Math P-6',GETDATE()),('MT151IP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MT152',NULL,'Math',1,'Math P-6',GETDATE()),('MT152IP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MT153',NULL,'Math',1,'Math P-6',GETDATE()),('MT153IP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MT164',NULL,'Math',1,'Math P-6',GETDATE()),('MT4IP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MT165',NULL,'Math',1,'Math P-6',GETDATE()),('MT5IP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MT166',NULL,'Math',1,'Math P-6',GETDATE()),('MT6IP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MT15PRIM',NULL,'Math',1,'Math P-6',GETDATE()),('MT15PRIMIP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MT151IM',NULL,'Math',1,'Math P-6',GETDATE()),('MT151IMIP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MT152IM',NULL,'Math',1,'Math P-6',GETDATE()),('MT152IMIP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MT153IM',NULL,'Math',1,'Math P-6',GETDATE()),('MT153IMIP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MTH164IM',NULL,'Math',1,'Math P-6',GETDATE()),('MTH165IM',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MTH166IM',NULL,'Math',1,'Math P-6',GETDATE()),('MAT4IMIP',NULL,'Math',1,'Math P-6',GETDATE()),
    ('MAT5IMIP',NULL,'Math',1,'Math P-6',GETDATE()),('MAT6IMIP',NULL,'Math',1,'Math P-6',GETDATE());

SELECT Language, Kind, COUNT(*) AS Courses FROM DimCourseAssessment GROUP BY Language, Kind ORDER BY Kind, Language;


/* ========== sql/dimensions/DimShortCycle.sql ========== */
/*******************************************************************************
 * Table: DimShortCycle
 * Purpose: HEADER for a Short Cycle of Response (SCoR). One row per cycle,
 *          identified by a distinct key (CycleGroupID, an app-generated GUID).
 *          Holds the display name + date range ONCE; the per-(subject x language x
 *          program-scope x grade) assessment instances are DimAssessmentWindow rows
 *          that tie back via CycleGroupID and inherit these dates.
 *
 *          DisplayName is NOT unique on purpose: 'SCoR 1' can exist every year --
 *          each is a distinct header key with its own date range, so results (which
 *          hang off the instance windows -> CycleGroupID) always roll up to the
 *          correct cycle even when names repeat.
 * SCD Type: N/A (managed manually via usp_UpsertShortCycleHeader)
 * Created: 2026-09-17
 * Region: Canada East (PIIDPA compliant)
 ******************************************************************************/

CREATE TABLE DimShortCycle (
    CycleGroupID   VARCHAR(36)   NOT NULL,   -- distinct header key (app-generated GUID); DimAssessmentWindow.CycleGroupID references this
    DisplayName    VARCHAR(100)  NOT NULL,   -- e.g. 'SCoR 1' -- NOT unique (one per year is fine; the key distinguishes)
    StartDate      DATE          NOT NULL,
    EndDate        DATE          NOT NULL,
    SchoolYear     VARCHAR(9)    NOT NULL,   -- derived from StartDate (Sep-Aug)
    ActiveFlag     BIT           NOT NULL,
    CreatedDate    DATETIME2(0)  NOT NULL,
    CreatedBy      VARCHAR(100)  NULL,
    LastUpdated    DATETIME2(0)  NOT NULL
);


/* ========== sql/scripts/backfill_DimShortCycle_headers.sql ========== */
/*******************************************************************************
 * Script: backfill_DimShortCycle_headers.sql
 * Purpose: Seed DimShortCycle headers for cycles that predate the header table.
 *          1) Give any legacy single window (CycleGroupID NULL) its own key so it
 *             becomes a standalone cycle.
 *          2) Create a header row for every distinct CycleGroupID not yet headed,
 *             taking the name/dates/year from its instance windows (which share them).
 *          Idempotent: re-running inserts nothing once every group has a header.
 * Run ONCE after DimShortCycle.sql. GO-separated.
 * Region: Canada East (PIIDPA compliant)
 ******************************************************************************/

-- 1) Legacy windows with no group key -> give each its own GUID (its own cycle).
UPDATE DimAssessmentWindow
SET CycleGroupID = LOWER(CONVERT(VARCHAR(36), NEWID())), LastUpdated = GETDATE()
WHERE CycleGroupID IS NULL;
GO

-- 2) Header per distinct CycleGroupID not already in DimShortCycle.
INSERT INTO DimShortCycle (CycleGroupID, DisplayName, StartDate, EndDate, SchoolYear, ActiveFlag, CreatedDate, CreatedBy, LastUpdated)
SELECT
    w.CycleGroupID,
    MAX(w.WindowName)                       AS DisplayName,
    MIN(w.StartDate)                        AS StartDate,
    MAX(w.EndDate)                          AS EndDate,
    MAX(w.SchoolYear)                       AS SchoolYear,
    CAST(MAX(CAST(w.ActiveFlag AS INT)) AS BIT) AS ActiveFlag,
    GETDATE(), 'backfill', GETDATE()
FROM DimAssessmentWindow w
WHERE NOT EXISTS (SELECT 1 FROM DimShortCycle h WHERE h.CycleGroupID = w.CycleGroupID)
GROUP BY w.CycleGroupID;
GO

SELECT (SELECT COUNT(*) FROM DimShortCycle) AS Headers,
       (SELECT COUNT(DISTINCT CycleGroupID) FROM DimAssessmentWindow) AS DistinctCycleGroups;
GO


/* ========== sql/dimensions/DimMathComprehensionBand.sql ========== */
/*******************************************************************************
 * Table: DimMathComprehensionBand
 * Purpose: The 4-tier math achievement-level scale (shown in the UI as
 *          "Achievement Level") — the code -> (label, colour) lookup for a
 *          student's per-unit level, derived from the average of their 0/1
 *          across the unit's tasks. Four rows, one per tier. (Table name kept as
 *          DimMathComprehensionBand; the UI label is "Achievement Level".)
 * SCD Type: Type 1 (overwrite reference data; ActiveFlag soft-retires a tier).
 * Created: 2026-09-02
 * Region: Canada East (PIIDPA compliant)
 *
 * The threshold LADDER lives in the read view, not in this table (mirrors the
 * Writing avg -> band-code pattern that joins DimAchievementLevel by code). The
 * view computes BandCode from the average and joins here for Label + HexColor:
 *
 *       avg <  0.50            -> 1  Emerging
 *       0.50 <= avg <  0.75    -> 2  Developing
 *       0.75 <= avg <  0.90    -> 3  Meeting
 *       avg >= 0.90            -> 4  In-depth
 *   ( < 80% of the unit's tasks scored -> 'Incomplete', handled in the view — not
 *     a stored tier )
 *
 * NOT here: the by-task class-mastery colour code (>80 / 65-80 / 50-64 / <50).
 * That is a display heatmap over a task's proportion-correct, applied in the read
 * view / UI — it is not a comprehension tier and is not stored as reference data.
 *
 * Seed (4 rows): 1 Emerging, 2 Developing, 3 Meeting, 4 In-depth.
 ******************************************************************************/

CREATE TABLE DimMathComprehensionBand (
    MathBandKey     BIGINT          NOT NULL IDENTITY,   -- Surrogate key
    BandCode        INT             NOT NULL,   -- 1 Emerging .. 4 In-depth (matches the view's ladder)
    Label           VARCHAR(50)     NOT NULL,   -- 'Emerging' / 'Developing' / 'Meeting' / 'In-depth'
    HexColor        VARCHAR(7)      NULL,       -- UI colour, e.g. '#b23347'
    SortOrder       INT             NOT NULL,   -- display order (= BandCode)
    ActiveFlag      BIT             NOT NULL,
    LastUpdated     DATETIME2(0)    NOT NULL
);


/* ========== sql/scripts/seed_DimMathComprehensionBand.sql ========== */
/*******************************************************************************
 * Script: seed_DimMathComprehensionBand.sql
 * Purpose: Seed the 4-tier math comprehension scale. Re-runnable (TRUNCATE +
 *          INSERT). Labels/thresholds per the revised Term-1 scale; the
 *          avg -> BandCode ladder lives in the read view (see the table header).
 * Created: 2026-09-02
 * Region: Canada East (PIIDPA compliant)
 *
 * Colours are a first pass (red -> amber -> green -> cyan); adjust to taste or
 * to align with DimAchievementLevel without touching any logic.
 ******************************************************************************/

TRUNCATE TABLE DimMathComprehensionBand;

INSERT INTO DimMathComprehensionBand (BandCode, Label, HexColor, SortOrder, ActiveFlag, LastUpdated)
VALUES
    (1, 'Emerging',   '#b23347', 1, CAST(1 AS BIT), GETDATE()),   -- avg < 0.50
    (2, 'Developing', '#d98a2b', 2, CAST(1 AS BIT), GETDATE()),   -- 0.50 <= avg <  0.75
    (3, 'Meeting',    '#3a9b57', 3, CAST(1 AS BIT), GETDATE()),   -- 0.75 <= avg <  0.90
    (4, 'In-depth',   '#0092c9', 4, CAST(1 AS BIT), GETDATE());   -- avg >= 0.90


/* ========== sql/dimensions/DimMathTask.sql ========== */
/*******************************************************************************
 * Table: DimMathTask
 * Purpose: The bank of P-6 math assessment TASKS. Each task is one outcome-based
 *          item a student is scored on as can-do (1) / cannot (0) in
 *          FactAssessmentMath. Bilingual: one key, an English and a French
 *          description, so a task renders in the teacher's program language but
 *          rolls up on a single key for school/regional summaries.
 * SCD Type: Type 1 (overwrite reference data; ActiveFlag soft-retires a task that
 *           a curriculum revision drops, so historic FactAssessmentMath rows keep
 *           a valid MathTaskKey).
 * Created: 2026-09-02
 * Region: Canada East (PIIDPA compliant)
 *
 * Cadence: Math runs on the SAME region-wide Short Cycles as Reading/Writing —
 *   there is no separate "term" cadence (the seed spreadsheet's Term 1/2/3 split
 *   is just a convenience of that format). A task maps to a cycle by MONTH, the
 *   same way Reading targets do: AssessmentMonth here is matched against the
 *   cycle's benchmark / dominant month (see DimReadingBenchmark.AssessmentMonth).
 *
 * Grain / natural key: (GradeCode, AssessmentMonth, UnitName, QuestionNumber) is
 *   unique. QuestionNumber is NOT unique on its own — the same label (e.g. '2a')
 *   recurs across units, so UnitName is part of the key. UnitName may be NULL (a
 *   cycle whose tasks are not unit-grouped); seeding/upsert compares it NULL-safely
 *   (ISNULL(...,'~')).
 *
 * Page model (drives the entry grid): the entry page loads DimMathTask WHERE
 *   GradeCode = <student grade> AND AssessmentMonth = <cycle month> AND
 *   ActiveFlag = 1, groups rows under UnitName sub-headings ordered by UnitOrder,
 *   orders tasks within a unit by DisplayOrder, labels each by QuestionNumber, and
 *   shows one 0/1 cell per student.
 *
 * Seed source: grade-level spreadsheets authored to MIRROR this table's columns,
 *   ingested through staging + COPY INTO (same pattern as the PowerSchool roster
 *   load) and merged into DimMathTask on the natural key. French descriptions land
 *   later — TaskDescriptionFR is NULL until then.
 ******************************************************************************/

CREATE TABLE DimMathTask (
    MathTaskKey         BIGINT          NOT NULL IDENTITY,   -- Surrogate key (FactAssessmentMath FK)
    GradeCode           VARCHAR(10)     NOT NULL,   -- 'P','1'..'6' — matches DimGrade.GradeCode
    AssessmentMonth     INT             NOT NULL,   -- 1-12 — matched against the Short Cycle's benchmark/dominant month
    UnitName            VARCHAR(100)    NULL,       -- page sub-heading (e.g. 'Unit 1'); NULL if the cycle's tasks are ungrouped
    UnitOrder           INT             NULL,       -- order units appear on the page (NULL when ungrouped)
    QuestionNumber      VARCHAR(10)     NOT NULL,   -- human label '1','2a','2b' — NOT unique alone (see grain)
    DisplayOrder        INT             NOT NULL,   -- sort of the task within its unit
    OutcomeCode         VARCHAR(20)     NULL,       -- NS grade-level outcome, e.g. 'N02.01'; NULL when the task maps to none
    TaskDescriptionEN   VARCHAR(500)    NOT NULL,   -- English task text (shown to English-program teachers)
    TaskDescriptionFR   VARCHAR(500)    NULL,       -- French task text (shown to FI teachers); NULL until seeded
    AnswerKey           VARCHAR(200)    NULL,       -- expected answer — shown to the teacher as a marking reference
    ActiveFlag          BIT             NOT NULL,   -- 1 = current; 0 = retired by a curriculum revision
    LastUpdated         DATETIME2(0)    NOT NULL
);


/* ========== sql/staging/Stg_MathTask.sql ========== */
/*******************************************************************************
 * Table: Stg_MathTask
 * Purpose: All-VARCHAR landing table for the math task-bank seed CSV (one file
 *          per grade, authored to mirror DimMathTask's columns). COPY INTO loads
 *          text here; usp_LoadMathTasks validates / casts and upserts into
 *          DimMathTask. "Load as text, convert in the merge" — the standard
 *          staging pattern, so a single malformed cell can't fail the COPY.
 * SCD Type: N/A (transient staging — TRUNCATEd every load).
 * Created: 2026-09-02
 * Region: Canada East (PIIDPA compliant)
 *
 * Column order MUST match the seed CSV header:
 *   GradeCode, AssessmentMonth, UnitName, UnitOrder, QuestionNumber,
 *   DisplayOrder, OutcomeCode, TaskDescriptionEN, TaskDescriptionFR,
 *   AnswerKey, ActiveFlag
 ******************************************************************************/

CREATE TABLE Stg_MathTask (
    GradeCode           VARCHAR(50)     NULL,
    AssessmentMonth     VARCHAR(50)     NULL,
    UnitName            VARCHAR(200)    NULL,
    UnitOrder           VARCHAR(50)     NULL,
    QuestionNumber      VARCHAR(50)     NULL,
    DisplayOrder        VARCHAR(50)     NULL,
    OutcomeCode         VARCHAR(50)     NULL,
    TaskDescriptionEN   VARCHAR(1000)   NULL,
    TaskDescriptionFR   VARCHAR(1000)   NULL,
    AnswerKey           VARCHAR(500)    NULL,
    ActiveFlag          VARCHAR(50)     NULL
);


/* ========== sql/facts/FactAssessmentMath.sql ========== */
/*******************************************************************************
 * Table: FactAssessmentMath
 * Purpose: Per-task math results entered by teachers — one bit per student per
 *          task per cycle: 1 = can do the task, 0 = cannot. Everything the
 *          reports need (grade, term, unit, outcome, task text) derives through
 *          MathTaskKey -> DimMathTask; the fact stays a thin (who, which task,
 *          got-it?) grain.
 * SCD Type: N/A (fact).
 * Created: 2026-09-02
 * Region: Canada East (PIIDPA compliant)
 *
 * Grain: Student x Window x Task x DATE — one row per (StudentKey,
 *   AssessmentWindowID, MathTaskKey, AssessmentDate). KEEPS CHANGE HISTORY like
 *   FactAssessmentReading/Writing's ongoing-assessment model: usp_UpsertMathAssessment
 *   INSERTS a new dated row (AssessmentDate capped at MIN(today, window EndDate) so
 *   late entry bins into the window's month); a same-date re-entry for the same task
 *   UPDATES that day's row. Every read that resolves a per-(student, task) result
 *   MUST pick the LATEST — ROW_NUMBER() OVER (PARTITION BY StudentKey,
 *   AssessmentWindowID, MathTaskKey ORDER BY AssessmentDate DESC, MathAssessmentID DESC)
 *   = 1 — or a student/task fans out to one row per entry (see the fabric-warehouse-sql
 *   skill's "ongoing-assessment / multiple-entry fact patterns" note).
 *
 * Key resolution: StudentKey / EnteredByStaffKey are the surrogate values
 *   current at entry time (assessment-fact insert-time resolution — see
 *   project_assessment_fact_scd_policy). Reads join back to DimStudent /
 *   DimStaff / DimMathTask; no business keys are stored on the fact.
 *
 * Derived layers (computed in the read views over each student's LATEST result per
 * task, NOT stored here):
 *   - by task:            SUM(Result) / #students assessed -> proportion -> colour band
 *   - by student, unit:   AVG(Result) over the unit's tasks -> comprehension band
 *                         ('Incomplete' when < 80% of the unit's tasks are scored)
 *   - class distribution: COUNT of students in each comprehension band, per unit
 *   Band labels/colours come from DimMathComprehensionBand (join by code);
 *   the exact thresholds live in the view (mirrors the Writing avg->band pattern).
 ******************************************************************************/

CREATE TABLE FactAssessmentMath (
    MathAssessmentID    BIGINT          NOT NULL IDENTITY,   -- Surrogate key
    StudentKey          BIGINT          NOT NULL,   -- References DimStudent.StudentKey (current at entry)
    AssessmentWindowID  BIGINT          NOT NULL,   -- References DimAssessmentWindow.AssessmentWindowID (the Math Short Cycle window)
    MathTaskKey         BIGINT          NOT NULL,   -- References DimMathTask.MathTaskKey
    Result              BIT             NOT NULL,   -- 1 = can do the task, 0 = cannot
    AssessmentDate      DATE            NOT NULL,   -- date the result was recorded (Atlantic)
    EnteredByStaffKey   BIGINT          NOT NULL,   -- References DimStaff.StaffKey
    SubmissionTimestamp DATETIME2(0)    NOT NULL,   -- UTC (storage convention)
    LastUpdated         DATETIME2(0)    NOT NULL    -- Set on insert / bit correction
);


/* ========== sql/facts/FactStudentAdaptation.sql ========== */
/*******************************************************************************
 * Table: FactStudentAdaptation
 * Purpose: Tracks per-student, per-subject, per-program-family ADAPTATION status
 *          with SCD Type 2 versioning. Structural MIRROR of FactStudentIPP,
 *          keyed on the PowerSchool "has adaptations" flag (DimStudent.Adap)
 *          instead of DimStudent.IPP. PowerSchool records only ONE global
 *          "has adaptations" yes/no per student; this table breaks that out by
 *          SUBJECT so teachers can record which subjects a student's adaptation
 *          applies to (Reading / Writing / Math) -- the "Adaptations" half of
 *          the Programming section. No adaptation-type/focus detail is stored:
 *          the grain is simply (student, subject) yes/no.
 *
 *          RECORD-ONLY for now: unlike IPP, an adaptation does NOT alter any
 *          achievement/aggregate computation or data-entry gating. It is
 *          captured to be used as a data FILTER later. (project_programming_makeover)
 * SCD Type: Type 2 (close + insert pattern on HasAdaptation changes)
 * Created: 2026-09-11
 * Region: Canada East (PIIDPA compliant)
 *
 * Reconciliation key (triple): (StudentKey, Subject, ProgramFamily)
 *
 * HasAdaptation semantics (mirrors FactStudentIPP.IsIPP):
 *   NULL = unresolved gate. Auto-created by usp_MergeStudent when a student
 *          appears with PS-Adap = 1. Awaits teacher/admin confirmation.
 *      1 = student has an adaptation for this subject + program family.
 *      0 = student has no adaptation for this subject + program family.
 *
 * Auto-create applicability rules (handled in usp_MergeStudent, mirroring IPP,
 * plus Math which literacy IPP does not yet seed):
 *   ProgramFamily 'English' student with DimStudent.Adap=1:
 *     -> ('Reading','English'), ('Writing','English'), HasAdaptation=NULL
 *   ProgramFamily 'French Immersion' student with DimStudent.Adap=1:
 *     -> ('Reading','French Immersion'), ('Writing','French Immersion') (any grade)
 *     -> If grade >= 3, ALSO ('Reading','English'), ('Writing','English')
 *   Math (any program) with DimStudent.Adap=1 AND grade P-6 (GradeOrder <= 6):
 *     -> ('Math', <the student's own ProgramFamily>)  -- SINGLE row; Math is not
 *        language-split, and Math cycles are P-6 only.
 *
 * Closure rules: when DimStudent.Adap changes 1 -> 0 (or the student is
 *   deactivated / changes program / drops applicability), close all current
 *   rows no longer in the expected set (IsCurrent=0, EffectiveEndDate=@EffectiveDate-1).
 *   History of prior 1/0 values is preserved on the closed rows.
 *
 * Web app binding: the web app reads this via tvf_StudentAdaptation (@UPN-scoped
 *   iTVF) / vw_StudentAdaptation, which cast BIGINT keys to VARCHAR(20) per the
 *   project_powerapps_bigint_precision convention. Writes go through
 *   usp_UpsertStudentAdaptation (wrapper proc; no OUTPUT clause).
 *
 * ChangedBy convention:
 *   'system'   -> row created by usp_MergeStudent auto-create
 *   '<email>'  -> row created by usp_UpsertStudentAdaptation (teacher/admin action)
 ******************************************************************************/

CREATE TABLE FactStudentAdaptation (
    StudentAdaptationID BIGINT          NOT NULL IDENTITY,
    StudentKey          BIGINT          NOT NULL,    -- ref to DimStudent surrogate
    Subject             VARCHAR(20)     NOT NULL,    -- 'Reading', 'Writing', 'Math'
    ProgramFamily       VARCHAR(50)     NOT NULL,    -- 'English', 'French Immersion'
    HasAdaptation       BIT             NULL,        -- NULL = unresolved gate; 1 = has; 0 = none
    EffectiveStartDate  DATE            NOT NULL,
    EffectiveEndDate    DATE            NULL,        -- NULL = current version
    IsCurrent           BIT             NOT NULL,
    ChangedBy           VARCHAR(255)    NULL,        -- 'system' or caller email (lowercased)
    LastUpdated         DATETIME2(0)    NOT NULL
);


/* ========== sql/security/AppMaintenance.sql ========== */
/*******************************************************************************
 * Table: AppMaintenance
 * Purpose: SINGLE-ROW store for the app maintenance window, so a sysadmin can
 *          schedule a graceful entry lockout ahead of an emergency container swap
 *          WITHOUT a rebuild. The running container reads it (via /api/status,
 *          server-side cached) and every client poller keys its staged banner /
 *          entry-lock / auto-save off the returned window + server clock.
 * SCD Type: N/A (single mutable config row, Id = 1)
 * Created: 2026-09-16
 * Region: Canada East (PIIDPA compliant)
 *
 * MaintenanceAt is stored in UTC (Fabric default; the app picks a local Atlantic
 * time and converts before calling usp_SetMaintenanceWindow). NULL = no window.
 * Written only by usp_Set/ClearMaintenanceWindow (both sysadmin-gated); the web app
 * (service principal) reads it. Auto-expiry (ignore a window well past T) is applied
 * in /api/status, so a forgotten window self-heals; an explicit all-clear lifts it
 * immediately. Survives container restarts (that's the point — a swap doesn't clear it).
 ******************************************************************************/

IF OBJECT_ID('dbo.AppMaintenance') IS NULL
    CREATE TABLE AppMaintenance (
        Id             INT           NOT NULL,   -- always 1 (single-row table; Fabric has no TINYINT)
        MaintenanceAt  DATETIME2(0)  NULL,       -- UTC swap moment T; NULL = no window active
        Message        VARCHAR(500)  NULL,       -- optional custom banner message
        SetByEmail     VARCHAR(255)  NULL,       -- who set it (lowercased)
        SetAt          DATETIME2(0)  NULL,       -- UTC when set
        LastUpdated    DATETIME2(0)  NOT NULL
    );
GO

-- Seed the single row once (preserved across redeploys).
IF NOT EXISTS (SELECT 1 FROM AppMaintenance WHERE Id = 1)
    INSERT INTO AppMaintenance (Id, MaintenanceAt, Message, SetByEmail, SetAt, LastUpdated)
    VALUES (1, NULL, NULL, NULL, NULL, GETDATE());
GO

-- Web app connects as the service principal; grant SELECT to it alone.
GRANT SELECT ON dbo.AppMaintenance TO [StudentDataAssessment];
GO


