/* ============================================================================
   STAGE 03a — COPY INTO load-staging procs (run alone; verify each applied)
   GENERATED by scripts/generate_live_deploy.sh — do not hand-edit; edit sources + regen.
   0.5.0 live deploy. Run DEV first. Run stages in filename order.
   ============================================================================ */

/* ========== sql/procedures/usp_LoadStudentsStaging.sql ========== */
/*******************************************************************************
 * Procedure: usp_LoadStudentsStaging
 * Purpose: Strategy A loader — TRUNCATE Stg_Student and COPY INTO from the
 *          OneLake students/ folder. Decoupled from usp_MergeStudent so that
 *          the Strategy B Pipeline (Step 29) can replace this proc with a
 *          Copy activity without touching the merge logic.
 * Created: 2026-04-30
 * Region: Canada East (PIIDPA compliant)
 *
 * Operational expectation: exactly ONE PowerSchool Students export file
 * present in the watched folder at call time. The wildcard pattern below
 * unions any matching files, so leaving stale exports in place will produce
 * duplicates. Operators should clear the folder before each ingest.
 *
 * COPY INTO config — PowerSchool sqlReport CSV format (source updated 2026-06-08;
 * NOT yet deployed — see docs/powerschool-report-specifications.md Appendix C):
 *   FILE_TYPE       = 'CSV'
 *   FIELDTERMINATOR = ','       (sqlReport is comma-delimited)
 *   FIELDQUOTE      = '"'       (text qualifier; handles embedded commas)
 *   FIRSTROW        = 2         (skip header)
 *   ROWTERMINATOR   = (default — sqlReports use CRLF, default catches it)
 * UTF-8 is the default; ENCODING parameter is not supported by Fabric.
 * Replaces the pilot direct-table-extract format (TAB / CR-only 0x0D / .text).
 * DEPLOY ONLY at cutover, together with the new SQL reports — the live pilot
 * ingest still runs the previously-deployed TAB format until then.
 * Folder-routed by '*' wildcard — any single dropped file loads, no filename
 * prefix required.
 *
 * Path note: Step 7 testing showed the GUID-based abfss:// path works in this
 * environment while the name-based path failed authentication. The GUIDs
 * embedded below correspond to the Regional_Data_Portal workspace and the
 * Assessment_Landing lakehouse — read them from the Fabric portal URL if
 * the workspace or lakehouse is ever rebuilt.
 ******************************************************************************/

CREATE PROCEDURE usp_LoadStudentsStaging
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE Stg_Student;

    COPY INTO Stg_Student
    FROM 'abfss://a1b49041-0855-46de-8aca-86762132eefb@onelake.dfs.fabric.microsoft.com/b3819971-8ef8-448b-b0b3-58a6fc7985ef/Files/imports/students/Students*'
    WITH (
        FILE_TYPE       = 'CSV',
        FIELDTERMINATOR = ',',
        FIELDQUOTE      = '"',
        FIRSTROW        = 2
    );
END;


/* ========== sql/procedures/usp_LoadStaffStaging.sql ========== */
/*******************************************************************************
 * Procedure: usp_LoadStaffStaging
 * Purpose: Strategy A loader — TRUNCATE Stg_Staff and COPY INTO from the
 *          OneLake staff/ folder. Decoupled from usp_MergeStaff so the
 *          Strategy B Pipeline (Step 29) can replace this proc with a Copy
 *          activity without touching the merge logic.
 * Created: 2026-04-30
 * Region: Canada East (PIIDPA compliant)
 *
 * Operational expectation: exactly ONE PowerSchool Staff export file present
 * in the watched folder at call time. The wildcard pattern below unions any
 * matching files — operators should clear the folder before each ingest.
 *
 * COPY INTO config — PowerSchool sqlReport CSV format (source updated 2026-06-08;
 * NOT yet deployed — see docs/powerschool-report-specifications.md Appendix C):
 *   FILE_TYPE       = 'CSV'
 *   FIELDTERMINATOR = ','       (sqlReport is comma-delimited)
 *   FIELDQUOTE      = '"'       (text qualifier; handles embedded commas)
 *   FIRSTROW        = 2         (skip header)
 *   ROWTERMINATOR   = (default — sqlReports use CRLF, default catches it)
 * Replaces the pilot direct-table-extract format (TAB / CR-only 0x0D / .text).
 * DEPLOY ONLY at cutover, together with the new SQL reports — the live pilot
 * ingest still runs the previously-deployed TAB format until then.
 * Folder-routed by '*' wildcard — any single dropped file loads, no filename
 * prefix required.
 *
 * Path: GUID-based abfss URL into the Regional_Data_Portal workspace's
 * Assessment_Landing lakehouse — read GUIDs from the Fabric portal URL if
 * the workspace or lakehouse is ever rebuilt.
 ******************************************************************************/

CREATE PROCEDURE usp_LoadStaffStaging
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE Stg_Staff;

    COPY INTO Stg_Staff
    FROM 'abfss://a1b49041-0855-46de-8aca-86762132eefb@onelake.dfs.fabric.microsoft.com/b3819971-8ef8-448b-b0b3-58a6fc7985ef/Files/imports/staff/Staff*'
    WITH (
        FILE_TYPE       = 'CSV',
        FIELDTERMINATOR = ',',
        FIELDQUOTE      = '"',
        FIRSTROW        = 2
    );
END;


/* ========== sql/procedures/usp_LoadSectionStaging.sql ========== */
/*******************************************************************************
 * Procedure: usp_LoadSectionStaging
 * Purpose: Strategy A loader — TRUNCATE Stg_Section and COPY INTO from the
 *          OneLake sections/ folder. Decoupled from usp_MergeSection so the
 *          Strategy B Pipeline (Step 29) can replace this proc with a Copy
 *          activity without touching the merge logic.
 * Created: 2026-05-01
 * Region: Canada East (PIIDPA compliant)
 *
 * Operational expectation: exactly ONE PowerSchool Sections export file
 * present in the watched folder at call time. The wildcard pattern below
 * unions any matching files — operators should clear the folder before
 * each ingest.
 *
 * COPY INTO config — PowerSchool sqlReport CSV format (source updated 2026-06-08;
 * NOT yet deployed — see docs/powerschool-report-specifications.md Appendix C):
 *   FILE_TYPE       = 'CSV'
 *   FIELDTERMINATOR = ','       (sqlReport is comma-delimited)
 *   FIELDQUOTE      = '"'       (text qualifier; handles embedded commas)
 *   FIRSTROW        = 2         (skip header)
 *   ROWTERMINATOR   = (default — sqlReports use CRLF, default catches it)
 * Replaces the pilot direct-table-extract format (TAB / CR-only 0x0D / .text).
 * DEPLOY ONLY at cutover, together with the new SQL reports — the live pilot
 * ingest still runs the previously-deployed TAB format until then.
 * Folder-routed by '*' wildcard — any single dropped file loads, no filename
 * prefix required.
 *
 * Path: GUID-based abfss URL into the Regional_Data_Portal workspace's
 * Assessment_Landing lakehouse — read GUIDs from the Fabric portal URL if
 * the workspace or lakehouse is ever rebuilt.
 ******************************************************************************/

CREATE PROCEDURE usp_LoadSectionStaging
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE Stg_Section;

    COPY INTO Stg_Section
    FROM 'abfss://a1b49041-0855-46de-8aca-86762132eefb@onelake.dfs.fabric.microsoft.com/b3819971-8ef8-448b-b0b3-58a6fc7985ef/Files/imports/sections/Sections*'
    WITH (
        FILE_TYPE       = 'CSV',
        FIELDTERMINATOR = ',',
        FIELDQUOTE      = '"',
        FIRSTROW        = 2
    );
END;


/* ========== sql/procedures/usp_LoadEnrollmentStaging.sql ========== */
/*******************************************************************************
 * Procedure: usp_LoadEnrollmentStaging
 * Purpose: Strategy A loader — TRUNCATE Stg_Enrollment and COPY INTO from the
 *          OneLake enrollments/ folder. Decoupled from usp_MergeEnrollment
 *          so the Strategy B Pipeline (Step 29) can replace this proc with a
 *          Copy activity without touching the merge logic.
 * Created: 2026-05-01
 * Region: Canada East (PIIDPA compliant)
 *
 * Operational expectation: exactly ONE PowerSchool Enrollments export file
 * present in the watched folder at call time. The wildcard pattern below
 * unions any matching files — operators should clear the folder before
 * each ingest.
 *
 * COPY INTO config — PowerSchool sqlReport CSV format (source updated 2026-06-08;
 * NOT yet deployed — see docs/powerschool-report-specifications.md Appendix C):
 *   FILE_TYPE       = 'CSV'
 *   FIELDTERMINATOR = ','       (sqlReport is comma-delimited)
 *   FIELDQUOTE      = '"'       (text qualifier; handles embedded commas)
 *   FIRSTROW        = 2         (skip header)
 *   ROWTERMINATOR   = (default — sqlReports use CRLF, default catches it)
 * Replaces the pilot direct-table-extract format (TAB / CR-only 0x0D / .text).
 * DEPLOY ONLY at cutover, together with the new SQL reports — the live pilot
 * ingest still runs the previously-deployed TAB format until then.
 * Folder-routed by '*' wildcard — any single dropped file loads, no filename
 * prefix required.
 *
 * Path: GUID-based abfss URL into the Regional_Data_Portal workspace's
 * Assessment_Landing lakehouse — read GUIDs from the Fabric portal URL if
 * the workspace or lakehouse is ever rebuilt.
 ******************************************************************************/

CREATE PROCEDURE usp_LoadEnrollmentStaging
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE Stg_Enrollment;

    COPY INTO Stg_Enrollment
    FROM 'abfss://a1b49041-0855-46de-8aca-86762132eefb@onelake.dfs.fabric.microsoft.com/b3819971-8ef8-448b-b0b3-58a6fc7985ef/Files/imports/enrollments/Enrollments*'
    WITH (
        FILE_TYPE       = 'CSV',
        FIELDTERMINATOR = ',',
        FIELDQUOTE      = '"',
        FIRSTROW        = 2
    );
END;


/* ========== sql/procedures/usp_LoadCoTeacherStaging.sql ========== */
/*******************************************************************************
 * Procedure: usp_LoadCoTeacherStaging
 * Purpose: Strategy A loader — TRUNCATE Stg_CoTeacher and COPY INTO from the
 *          OneLake section-teachers/ folder. Decoupled from
 *          usp_MergeSectionTeachers so the Strategy B Pipeline (Step 29)
 *          can replace this proc with a Copy activity without touching
 *          the merge logic.
 * Created: 2026-05-01
 * Region: Canada East (PIIDPA compliant)
 *
 * Operational expectation: exactly ONE PowerSchool Co-Teacher export file
 * present in the watched folder at call time. The wildcard pattern below
 * unions any matching files — operators should clear the folder before
 * each ingest.
 *
 * Empty-file tolerance: if PS is not tracking co-teaching, the export is
 * skipped entirely and this folder is empty. COPY INTO with no matching
 * files raises an error in that case — operators handling that scenario
 * should either drop a 0-row "headers only" placeholder file in the folder
 * or skip calling this proc altogether. usp_MergeSectionTeachers DOES
 * tolerate Stg_CoTeacher being empty (primary teachers from Stg_Section
 * are still ingested).
 *
 * COPY INTO config — DIFFERENT from the direct-table-extract loaders:
 *   FILE_TYPE       = 'CSV'
 *   FIELDTERMINATOR = ','       (sqlReport is comma-delimited, NOT TAB)
 *   FIELDQUOTE      = '"'       (Teacher column emits "Last, First" with embedded commas)
 *   FIRSTROW        = 2         (skip header)
 *   ROWTERMINATOR   = (default — sqlReports use CRLF, default catches it)
 *
 * Path: GUID-based abfss URL into the Regional_Data_Portal workspace's
 * Assessment_Landing lakehouse.
 ******************************************************************************/

CREATE PROCEDURE usp_LoadCoTeacherStaging
AS
BEGIN
    SET NOCOUNT ON;

    TRUNCATE TABLE Stg_CoTeacher;

    COPY INTO Stg_CoTeacher
    FROM 'abfss://a1b49041-0855-46de-8aca-86762132eefb@onelake.dfs.fabric.microsoft.com/b3819971-8ef8-448b-b0b3-58a6fc7985ef/Files/imports/section-teachers/Co-Teachers*'
    WITH (
        FILE_TYPE       = 'CSV',
        FIELDTERMINATOR = ',',
        FIELDQUOTE      = '"',
        FIRSTROW        = 2
    );
END;


/* ========== sql/procedures/usp_LoadMathTasks.sql ========== */
/*******************************************************************************
 * Procedure: usp_LoadMathTasks
 * Purpose: Seed / refresh DimMathTask from a grade-level task CSV (authored to
 *          mirror the table's columns). TRUNCATE + COPY INTO Stg_MathTask, then
 *          a Type-1 upsert into DimMathTask on the natural key
 *          (GradeCode, AssessmentMonth, UnitName, QuestionNumber).
 * Created: 2026-09-02
 * Region: Canada East (PIIDPA compliant)
 *
 * @SourceUri: the FULL abfss:// path to the CSV (wildcards allowed), e.g.
 *   'abfss://<workspace>@onelake.dfs.fabric.microsoft.com/<lakehouse>/Files/imports/mathtasks/PrimaryMathTasks*'
 *   Parameterized (not hard-coded like the PS roster loaders) so the SAME proc
 *   runs against the dev lakehouse or live by just passing the right path.
 *
 * Incremental-safe: the retire step is scoped to the (GradeCode, AssessmentMonth)
 * pairs PRESENT in this batch, so loading one grade's sheet never retires another
 * grade's tasks. Re-loading a grade+month fully refreshes that set (insert new,
 * overwrite changed, retire dropped).
 *
 * Blank-key guard: rows with a blank GradeCode / QuestionNumber, or a
 * non-numeric AssessmentMonth (e.g. a trailing empty CSV line), are ignored.
 *
 * NOTE: builds the COPY INTO via sp_executesql so @SourceUri can vary. This is an
 * internal admin proc (analyst-run); the URI is not user-web-facing input.
 ******************************************************************************/

DROP PROCEDURE IF EXISTS usp_LoadMathTasks;
GO

CREATE PROCEDURE usp_LoadMathTasks
    @SourceUri VARCHAR(1000)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Inserted INT = 0, @Updated INT = 0, @Retired INT = 0;

    -- ------------------------------------------------------------------------
    -- 1. Stage the CSV (all text) from OneLake.
    -- ------------------------------------------------------------------------
    TRUNCATE TABLE Stg_MathTask;

    DECLARE @sql NVARCHAR(MAX) = N'
        COPY INTO Stg_MathTask
        FROM ''' + @SourceUri + N'''
        WITH (
            FILE_TYPE       = ''CSV'',
            FIELDTERMINATOR = '','',
            FIELDQUOTE      = ''"'',
            FIRSTROW        = 2
        );';
    EXEC sp_executesql @sql;

    -- ------------------------------------------------------------------------
    -- 2a. Overwrite changed rows (SCD Type 1) for tasks already on file.
    -- ------------------------------------------------------------------------
    UPDATE d
    SET UnitName          = NULLIF(LTRIM(RTRIM(s.UnitName)), ''),
        UnitOrder         = TRY_CAST(s.UnitOrder AS INT),
        DisplayOrder      = TRY_CAST(s.DisplayOrder AS INT),
        OutcomeCode       = NULLIF(LTRIM(RTRIM(s.OutcomeCode)), ''),
        TaskDescriptionEN = s.TaskDescriptionEN,
        TaskDescriptionFR = NULLIF(s.TaskDescriptionFR, ''),
        AnswerKey         = NULLIF(s.AnswerKey, ''),
        ActiveFlag        = CAST(ISNULL(TRY_CAST(s.ActiveFlag AS INT), 1) AS BIT),
        LastUpdated       = GETDATE()
    FROM DimMathTask d
    INNER JOIN Stg_MathTask s
            ON s.GradeCode = d.GradeCode
           AND TRY_CAST(s.AssessmentMonth AS INT) = d.AssessmentMonth
           AND ISNULL(NULLIF(LTRIM(RTRIM(s.UnitName)), ''), '~') = ISNULL(d.UnitName, '~')
           AND s.QuestionNumber = d.QuestionNumber
    WHERE NULLIF(LTRIM(RTRIM(s.GradeCode)), '')      IS NOT NULL
      AND NULLIF(LTRIM(RTRIM(s.QuestionNumber)), '') IS NOT NULL
      AND TRY_CAST(s.AssessmentMonth AS INT)         IS NOT NULL;

    SET @Updated = @@ROWCOUNT;

    -- ------------------------------------------------------------------------
    -- 2b. Insert new tasks (natural key not already present).
    -- ------------------------------------------------------------------------
    INSERT INTO DimMathTask (
        GradeCode, AssessmentMonth, UnitName, UnitOrder, QuestionNumber,
        DisplayOrder, OutcomeCode, TaskDescriptionEN, TaskDescriptionFR,
        AnswerKey, ActiveFlag, LastUpdated
    )
    SELECT
        s.GradeCode,
        TRY_CAST(s.AssessmentMonth AS INT),
        NULLIF(LTRIM(RTRIM(s.UnitName)), ''),
        TRY_CAST(s.UnitOrder AS INT),
        s.QuestionNumber,
        TRY_CAST(s.DisplayOrder AS INT),
        NULLIF(LTRIM(RTRIM(s.OutcomeCode)), ''),
        s.TaskDescriptionEN,
        NULLIF(s.TaskDescriptionFR, ''),
        NULLIF(s.AnswerKey, ''),
        CAST(ISNULL(TRY_CAST(s.ActiveFlag AS INT), 1) AS BIT),
        GETDATE()
    FROM Stg_MathTask s
    WHERE NULLIF(LTRIM(RTRIM(s.GradeCode)), '')      IS NOT NULL
      AND NULLIF(LTRIM(RTRIM(s.QuestionNumber)), '') IS NOT NULL
      AND TRY_CAST(s.AssessmentMonth AS INT)         IS NOT NULL
      AND NOT EXISTS (
          SELECT 1 FROM DimMathTask d
          WHERE d.GradeCode = s.GradeCode
            AND d.AssessmentMonth = TRY_CAST(s.AssessmentMonth AS INT)
            AND ISNULL(d.UnitName, '~') = ISNULL(NULLIF(LTRIM(RTRIM(s.UnitName)), ''), '~')
            AND d.QuestionNumber = s.QuestionNumber
      );

    SET @Inserted = @@ROWCOUNT;

    -- ------------------------------------------------------------------------
    -- 2c. Retire tasks dropped from the sheet — scoped to the (Grade, Month)
    --     pairs in THIS batch so a single-grade load never touches other grades.
    -- ------------------------------------------------------------------------
    UPDATE d
    SET ActiveFlag = CAST(0 AS BIT), LastUpdated = GETDATE()
    FROM DimMathTask d
    WHERE d.ActiveFlag = 1
      AND EXISTS (   -- this grade+month was part of the load batch
          SELECT 1 FROM Stg_MathTask s
          WHERE s.GradeCode = d.GradeCode
            AND TRY_CAST(s.AssessmentMonth AS INT) = d.AssessmentMonth
      )
      AND NOT EXISTS ( -- ...but this specific task is no longer in the sheet
          SELECT 1 FROM Stg_MathTask s
          WHERE s.GradeCode = d.GradeCode
            AND TRY_CAST(s.AssessmentMonth AS INT) = d.AssessmentMonth
            AND ISNULL(NULLIF(LTRIM(RTRIM(s.UnitName)), ''), '~') = ISNULL(d.UnitName, '~')
            AND s.QuestionNumber = d.QuestionNumber
      );

    SET @Retired = @@ROWCOUNT;

    -- ------------------------------------------------------------------------
    -- 3. Summary.
    -- ------------------------------------------------------------------------
    SELECT @Inserted AS TasksInserted, @Updated AS TasksUpdated, @Retired AS TasksRetired;
END;


