/* ============================================================================
   STAGE 03c — views (DROP/CREATE; full parity)
   GENERATED by scripts/generate_live_deploy.sh — do not hand-edit; edit sources + regen.
   0.5.0 live deploy. Run DEV first. Run stages in filename order.
   ============================================================================ */

/* ========== sql/security/vw_TeacherStudents.sql ========== */
/*******************************************************************************
 * View: vw_TeacherStudents
 * Purpose: RLS-gated teacher roster — returns the current students enrolled
 *          in sections taught by the calling user. One row per (student ×
 *          section assignment). Used by the Power Apps assessment-entry
 *          form to populate the student dropdown for a given section.
 * Created: 2026-05-01
 * Region: Canada East (PIIDPA compliant)
 *
 * RLS model:
 *   The calling user is identified via CURRENT_USER. The view joins
 *   FactSectionTeachers (which keys on TeacherEmail directly — decoupled
 *   from DimSection / DimStaff versioning per the 2026-04-28 design
 *   decision) and filters to only rows whose TeacherEmail matches the
 *   current user. No DimStaff lookup needed for the access check.
 *
 *   Email comparison is wrapped in LOWER() on both sides:
 *     - DimStaff.Email and FactSectionTeachers.TeacherEmail are lowercased
 *       at ingest, so the DB side is already lowercase.
 *     - CURRENT_USER casing is environment-dependent (typically
 *       lowercase in Entra ID but not guaranteed). LOWER() defends against
 *       a mismatch.
 *
 * Visibility rules:
 *   - Student must be current (IsCurrent = 1) in DimStudent.
 *   - EnrollStatus IN (0, -1) — Active or Pre-Enrolled. Inactive (2) and
 *     Graduated (3) are filtered out at PS export upstream and never reach
 *     the warehouse, so this filter is defense-in-depth.
 *   - FactEnrollment.ActiveFlag = 1 — only currently-active enrollments.
 *   - Section must be current (DimSection.IsCurrent = 1).
 *   - FactSectionTeachers row must be current (IsCurrent = 1).
 *   - Universal date gate: FactEnrollment.StartDate <= today. This is
 *     primarily for pre-enrolled students (they appear on the teacher's
 *     roster automatically on the day their start date arrives, even if
 *     the next ingest hasn't run yet). Also correctly hides active students
 *     with future-dated enrollments (e.g. a transfer student pre-registered
 *     for a section starting next semester).
 *
 * Grain: one row per (StudentKey × SectionID × TeacherRole). A student
 * enrolled in two sections taught by the same teacher appears twice. A
 * student enrolled in one section with a Primary teacher and a CoTeacher
 * appears in EACH teacher's view (once per teacher, not multiple times
 * for the same teacher).
 *
 * Connection-identity caveat:
 *   CURRENT_USER returns the connection's authenticated identity.
 *   This works correctly when:
 *     - Power Apps is configured with Entra ID identity passthrough to
 *       the Fabric SQL endpoint
 *     - Power BI semantic model uses DirectQuery with the user's Entra
 *       identity propagated
 *   It does NOT work as expected if the connection uses a service
 *   principal or a shared service account — in that case all queries
 *   return rows for the SP, not the end user. RLS would then need to
 *   move into the Power BI semantic model (DAX-based RLS roles). Confirm
 *   the Power Apps connection mode at Step 16 (Power Apps → Fabric SQL
 *   endpoint connection setup).
 ******************************************************************************/

CREATE VIEW vw_TeacherStudents
AS
SELECT
    s.StudentKey,
    s.StudentNumber,
    s.FirstName,
    s.MiddleName,
    s.LastName,
    s.Grade,
    s.SchoolID,
    s.ProgramCode,
    s.EnrollStatus,
    s.Homeroom,
    s.Gender,
    s.SelfIDAfrican,
    s.SelfIDIndigenous,
    s.IPP,
    s.Adap,
    sec.SectionKey,
    sec.SectionID,
    sec.CourseCode,
    sec.SectionNumber,
    sec.CourseName,
    fst.TeacherEmail,
    fst.TeacherRole,
    e.StartDate     AS EnrollmentStartDate,
    e.EndDate       AS EnrollmentEndDate
FROM DimStudent s
INNER JOIN FactEnrollment e
        ON e.StudentKey = s.StudentKey
       AND e.ActiveFlag = 1
       AND e.StartDate <= CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATE)
INNER JOIN DimSection sec
        ON sec.SectionKey = e.SectionKey
       AND sec.IsCurrent  = 1
INNER JOIN FactSectionTeachers fst
        ON fst.SectionID = sec.SectionID
       AND fst.IsCurrent = 1
WHERE s.IsCurrent = 1
  AND s.EnrollStatus IN (0, -1)
  AND LOWER(fst.TeacherEmail) = LOWER(CURRENT_USER);


/* ========== sql/security/vw_SchoolStudents.sql ========== */
/*******************************************************************************
 * View: vw_SchoolStudents
 * Purpose: RLS-gated school admin roster — returns the current students
 *          assigned to schools the calling user has school-tier access to.
 *          One row per student (no enrollment fanout). Used by school admin
 *          dashboards in Power Apps.
 * Created: 2026-05-01
 * Region: Canada East (PIIDPA compliant)
 *
 * RLS model:
 *   The calling user is identified via CURRENT_USER. Access is
 *   gated through StaffSchoolAccess (materialized RLS-oracle table —
 *   rebuilt on every staff merge), which unpacks DimStaff's HomeSchoolID +
 *   CanChangeSchool + AccessLevel into a (StaffKey, Email, SchoolID,
 *   AccessLevel) row set. The view filters to rows where the user has
 *   access to the student's SchoolID with one of the school-tier
 *   AccessLevels:
 *     - 'Administrator'      — Principal, VP, admin assistants
 *     - 'SpecialistTeacher'  — counsellors, registrars, coordinators,
 *                              resource teachers (school-based)
 *     - 'RegionalAnalyst'    — board-level (multi-school via CanChangeSchool;
 *                              also covered by vw_RegionalData but listed
 *                              here so they see school-level rosters too)
 *
 *   Email comparison wrapped in LOWER() defensively (same rationale as
 *   vw_TeacherStudents).
 *
 * Visibility rules (DELIBERATELY LOOSER than vw_TeacherStudents):
 *   - Student must be current (IsCurrent = 1) in DimStudent.
 *   - EnrollStatus IN (0, -1) — both Active AND Pre-Enrolled visible.
 *   - NO date gate on pre-enrolled — admins see all pre-enrolled students
 *     regardless of FactEnrollment.StartDate, for roster planning purposes.
 *     Decision 2026-05-01: admins need the heads-up to plan staffing
 *     and resources before students arrive; teachers' workflow is
 *     "enter assessments for kids in front of me today" so they get the
 *     date-gated view.
 *
 * Grain: one row per StudentKey (no enrollment fanout). Students with
 * multiple section enrollments appear only once. Students attending
 * multiple schools (rare; would require multiple DimStudent versions
 * with different SchoolID) appear once per school they're
 * currently associated with — but our DimStudent model only stores ONE
 * current school per student, so this is effectively one row per student.
 *
 * Connection-identity caveat: same as vw_TeacherStudents header.
 ******************************************************************************/

CREATE VIEW vw_SchoolStudents
AS
SELECT
    s.StudentKey,
    s.StudentNumber,
    s.FirstName,
    s.MiddleName,
    s.LastName,
    s.Grade,
    s.SchoolID,
    sch.SchoolName,
    s.ProgramCode,
    s.EnrollStatus,
    s.Homeroom,
    s.Gender,
    s.SelfIDAfrican,
    s.SelfIDIndigenous,
    s.IPP,
    s.Adap,
    ssa.AccessLevel    AS UserAccessLevel
FROM DimStudent s
INNER JOIN DimSchool sch
        ON sch.SchoolID = s.SchoolID
INNER JOIN StaffSchoolAccess ssa
        ON ssa.SchoolID = s.SchoolID
WHERE s.IsCurrent = 1
  AND s.EnrollStatus IN (0, -1)
  AND ssa.AccessLevel IN ('Administrator', 'SpecialistTeacher', 'RegionalAnalyst')
  AND LOWER(ssa.Email) = LOWER(CURRENT_USER);


/* ========== sql/security/vw_RegionalData.sql ========== */
/*******************************************************************************
 * View: vw_RegionalData
 * Purpose: RLS-gated region-wide student roster for the 10 regional analyst
 *          users. One row per student, no school filter — full regional
 *          visibility. Used by Power BI region-level reports and Power Apps
 *          regional dashboards.
 * Created: 2026-05-01
 * Region: Canada East (PIIDPA compliant)
 *
 * RLS model:
 *   The calling user is identified via CURRENT_USER. Access is
 *   gated through DimStaff: the user must have a current, active row with
 *   AccessLevel = 'RegionalAnalyst'. AccessLevel is the Type 1 column
 *   denormalized onto DimStaff at staff merge time (computed from the
 *   highest-priority school-tier RoleCode in FactStaffAssignment).
 *
 *   The gate is binary at the user level — either the user IS a regional
 *   analyst (sees all rows) or they're not (sees zero rows). No row-level
 *   filtering against student attributes.
 *
 *   ProvincialAnalyst (DoE / Evaluation Services) is intentionally NOT in
 *   the access list — those accounts are excluded from the PowerApp
 *   security group entirely (confirmed 2026-04-29 with PS admin) and don't
 *   authenticate to the platform.
 *
 *   Email comparison wrapped in LOWER() defensively.
 *
 * Visibility rules:
 *   - Student must be current (IsCurrent = 1).
 *   - EnrollStatus IN (0, -1) — Active and Pre-Enrolled both visible.
 *   - NO date gate (analysts have full visibility for planning, same
 *     rationale as vw_SchoolStudents).
 *
 * Grain: one row per StudentKey. ~6000 rows region-wide at full rollout.
 *
 * Connection-identity caveat: same as vw_TeacherStudents header.
 ******************************************************************************/

CREATE VIEW vw_RegionalData
AS
SELECT
    s.StudentKey,
    s.StudentNumber,
    s.FirstName,
    s.MiddleName,
    s.LastName,
    s.DateOfBirth,
    s.Grade,
    s.SchoolID,
    sch.SchoolName,
    s.ProgramCode,
    s.EnrollStatus,
    s.Homeroom,
    s.Gender,
    s.SelfIDAfrican,
    s.SelfIDIndigenous,
    s.IPP,
    s.Adap
FROM DimStudent s
INNER JOIN DimSchool sch
        ON sch.SchoolID = s.SchoolID
WHERE s.IsCurrent = 1
  AND s.EnrollStatus IN (0, -1)
  AND EXISTS (
      SELECT 1
      FROM DimStaff st
      WHERE LOWER(st.Email) = LOWER(CURRENT_USER)
        AND st.IsCurrent   = 1
        AND st.ActiveFlag  = 1
        AND st.AccessLevel = 'RegionalAnalyst'
  );


/* ========== sql/security/vw_UserAssessmentWindows.sql ========== */
/*******************************************************************************
 * View: vw_UserAssessmentWindows
 * Purpose: Returns one row per (calling user, applicable assessment window)
 *          tuple. Powers `scrWindowSelect` in the Power Apps entry app.
 * Created: 2026-05-13
 * Region: Canada East (PIIDPA compliant)
 *
 * Role-branched historical-roster reconciliation (per
 * project_historical_roster_reconciliation memory, decided 2026-05-12):
 *
 *   For each active window, compute its **effective date**:
 *     CASE WHEN today_atlantic > window.EndDate THEN window.EndDate
 *          ELSE today_atlantic END
 *   Then resolve "applicable students" using that effective date for SCD
 *   point-in-time joins. The effect: for CLOSED windows, teachers see the
 *   roster they HAD AT THE TIME — not their current roster.
 *
 * Role branches (mutually exclusive in practice via c.AccessLevel filter):
 *   - Teacher       (AccessLevel IS NULL):       students in their sections
 *                                                during the window's effective
 *                                                date, gated on FactSection-
 *                                                Teachers + DimSection +
 *                                                FactEnrollment effective dates
 *   - SchoolAdmin / SpecialistTeacher:           students whose DimStudent
 *                                                (effective at window date) had
 *                                                SchoolID in their CURRENT
 *                                                StaffSchoolAccess list
 *                                                (admin side is NOT historically
 *                                                reconciled — MVP scope)
 *   - RegionalAnalyst:                           all students whose DimStudent
 *                                                (effective at window date)
 *                                                matches the window scope
 *
 * Counts:
 *   - ApplicableStudentCount: distinct students the calling user can see for
 *                             this window per the role-branch logic above.
 *   - EnteredStudentCount:    distinct students with a FactAssessmentReading
 *                             row for the window.
 *
 *   TODO (Phase 5+): EnteredStudentCount currently only counts Reading
 *   assessments. When Writing / Math upsert procs go live, extend the count
 *   with a CASE on wed.AssessmentType + LEFT JOIN FactAssessmentWriting /
 *   FactAssessmentMath. For now Writing/Math windows would show 0 entered
 *   even if data existed.
 *
 * Identity:
 *   - Uses CURRENT_USER (not USERPRINCIPALNAME() — not supported in Fabric
 *     Warehouse T-SQL; see fabric-warehouse-sql skill item 14).
 *   - Emails lowercased on the join (DimStaff.Email + FactSectionTeachers
 *     .TeacherEmail are lowercased at ingest; CURRENT_USER casing is
 *     environment-dependent, so LOWER() both sides defensively).
 *
 * Time zone:
 *   - "Today" is computed in Atlantic time per the project time-zone
 *     convention (project_timezone_convention memory).
 ******************************************************************************/

CREATE VIEW vw_UserAssessmentWindows AS
WITH AtlanticToday AS (
    SELECT CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATE) AS Today
),
-- Resolve caller's role + identity once.
Caller AS (
    SELECT TOP 1
        d.StaffKey,
        LOWER(d.Email) AS Email,
        d.AccessLevel
    FROM DimStaff d
    WHERE LOWER(d.Email) = LOWER(CURRENT_USER)
      AND d.IsCurrent = 1
),
-- For each active window, compute its effective date for historical-roster resolution.
WindowEffectiveDates AS (
    SELECT
        w.AssessmentWindowID,
        w.WindowName,
        w.AssessmentType,
        w.SchoolYear,
        w.StartDate,
        w.EndDate,
        w.MinGrade,
        w.MaxGrade,
        w.ProgramFamily,
        w.ScaleSystem,
        CASE WHEN at.Today > w.EndDate THEN w.EndDate
             ELSE at.Today END AS EffectiveDate,
        CASE WHEN at.Today < w.StartDate THEN 'Upcoming'
             WHEN at.Today > w.EndDate   THEN 'Closed'
             WHEN at.Today = w.EndDate   THEN 'ClosesToday'
             ELSE 'Open' END AS WindowStatus
    FROM DimAssessmentWindow w
    CROSS JOIN AtlanticToday at
    WHERE w.ActiveFlag = 1
),
-- ROLE BRANCH 1: Teacher — students in sections they taught during the window.
-- Each join gated on the window effective date being within the relevant
-- Type 2 row's effective period.
TeacherStudents AS (
    SELECT
        wed.AssessmentWindowID,
        s.StudentKey
    FROM Caller c
    CROSS JOIN WindowEffectiveDates wed
    INNER JOIN FactSectionTeachers fst
            ON LOWER(fst.TeacherEmail) = c.Email
           AND wed.EffectiveDate BETWEEN fst.EffectiveStartDate AND COALESCE(fst.EffectiveEndDate, '9999-12-31')
    INNER JOIN DimSection sec
            ON sec.SectionID = fst.SectionID
           AND wed.EffectiveDate BETWEEN sec.EffectiveStartDate AND COALESCE(sec.EffectiveEndDate, '9999-12-31')
    INNER JOIN FactEnrollment e
            ON e.SectionKey  = sec.SectionKey
           AND e.StartDate  <= wed.EndDate
           AND (e.EndDate IS NULL OR e.EndDate >= wed.StartDate)
    INNER JOIN DimStudent s
            ON s.StudentKey = e.StudentKey
    INNER JOIN DimGrade   sg   ON sg.GradeCode   = s.Grade
    INNER JOIN DimGrade   wmin ON wmin.GradeCode = wed.MinGrade
    INNER JOIN DimGrade   wmax ON wmax.GradeCode = wed.MaxGrade
    INNER JOIN DimProgram dp   ON dp.ProgramCode = s.ProgramCode
    WHERE c.AccessLevel IS NULL                                         -- teachers have no school-tier AccessLevel
      AND sg.GradeOrder BETWEEN wmin.GradeOrder AND wmax.GradeOrder
      AND (wed.ProgramFamily IS NULL OR dp.ProgramFamily = wed.ProgramFamily)
),
-- ROLE BRANCH 2: School Admin / SpecialistTeacher — students whose DimStudent
-- (effective at window date) had SchoolID in their CURRENT StaffSchoolAccess list.
AdminStudents AS (
    SELECT
        wed.AssessmentWindowID,
        s.StudentKey
    FROM Caller c
    CROSS JOIN WindowEffectiveDates wed
    INNER JOIN StaffSchoolAccess ssa
            ON ssa.StaffKey = c.StaffKey
    INNER JOIN DimStudent s
            ON s.SchoolID = ssa.SchoolID
           AND wed.EffectiveDate BETWEEN s.EffectiveStartDate AND COALESCE(s.EffectiveEndDate, '9999-12-31')
    INNER JOIN DimGrade   sg   ON sg.GradeCode   = s.Grade
    INNER JOIN DimGrade   wmin ON wmin.GradeCode = wed.MinGrade
    INNER JOIN DimGrade   wmax ON wmax.GradeCode = wed.MaxGrade
    INNER JOIN DimProgram dp   ON dp.ProgramCode = s.ProgramCode
    WHERE c.AccessLevel IN ('Administrator', 'SpecialistTeacher')
      AND sg.GradeOrder BETWEEN wmin.GradeOrder AND wmax.GradeOrder
      AND (wed.ProgramFamily IS NULL OR dp.ProgramFamily = wed.ProgramFamily)
),
-- ROLE BRANCH 3: Regional Analyst — all students whose DimStudent
-- (effective at window date) matches the window's scope.
AnalystStudents AS (
    SELECT
        wed.AssessmentWindowID,
        s.StudentKey
    FROM Caller c
    CROSS JOIN WindowEffectiveDates wed
    INNER JOIN DimStudent s
            ON wed.EffectiveDate BETWEEN s.EffectiveStartDate AND COALESCE(s.EffectiveEndDate, '9999-12-31')
    INNER JOIN DimGrade   sg   ON sg.GradeCode   = s.Grade
    INNER JOIN DimGrade   wmin ON wmin.GradeCode = wed.MinGrade
    INNER JOIN DimGrade   wmax ON wmax.GradeCode = wed.MaxGrade
    INNER JOIN DimProgram dp   ON dp.ProgramCode = s.ProgramCode
    WHERE c.AccessLevel = 'RegionalAnalyst'
      AND sg.GradeOrder BETWEEN wmin.GradeOrder AND wmax.GradeOrder
      AND (wed.ProgramFamily IS NULL OR dp.ProgramFamily = wed.ProgramFamily)
),
ApplicableStudents AS (
    SELECT * FROM TeacherStudents
    UNION ALL SELECT * FROM AdminStudents
    UNION ALL SELECT * FROM AnalystStudents
)
SELECT
    CAST(wed.AssessmentWindowID AS VARCHAR(20)) AS AssessmentWindowID,   -- BIGINT cast to VARCHAR for Power Fx precision (>16 digits loses precision as Number); see feedback_powerapps_bigint_precision memory
    wed.WindowName,
    wed.AssessmentType,
    wed.SchoolYear,
    wed.StartDate,
    wed.EndDate,
    wed.MinGrade,
    wed.MaxGrade,
    wed.ProgramFamily,
    wed.ScaleSystem,
    wed.WindowStatus,
    COUNT(DISTINCT a.StudentKey) AS ApplicableStudentCount,
    COUNT(DISTINCT CASE WHEN far.ReadingAssessmentID IS NOT NULL
                        THEN a.StudentKey END) AS EnteredStudentCount   -- TODO Phase 5+: extend for Writing/Math
FROM WindowEffectiveDates wed
INNER JOIN ApplicableStudents a
        ON a.AssessmentWindowID = wed.AssessmentWindowID
LEFT JOIN FactAssessmentReading far
       ON far.AssessmentWindowID = wed.AssessmentWindowID
      AND far.StudentKey         = a.StudentKey
GROUP BY
    wed.AssessmentWindowID, wed.WindowName, wed.AssessmentType, wed.SchoolYear,
    wed.StartDate, wed.EndDate, wed.MinGrade, wed.MaxGrade, wed.ProgramFamily, wed.ScaleSystem, wed.WindowStatus;


/* ========== sql/security/vw_TeacherGroups.sql ========== */
/*******************************************************************************
 * View: vw_TeacherGroups
 * Purpose: Returns one row per (calling user, applicable window, group) tuple.
 *          Powers `scrGroupSelect` in the Power Apps entry app. Power Apps
 *          filters client-side by gblSelectedWindow.AssessmentWindowID.
 * Created: 2026-05-13
 * Region: Canada East (PIIDPA compliant)
 *
 * Group resolution rules:
 *   - PP-9 students (DimGrade.GradeOrder <= 9): group by Homeroom
 *       GroupKey   = 'HR:' + Homeroom
 *       GroupType  = 'Homeroom'
 *       GroupLabel = 'Homeroom <Homeroom>'
 *   - 10-12 + RG students (DimGrade.GradeOrder >= 10): group by Section
 *       GroupKey   = 'SEC:' + SectionID
 *       GroupType  = 'Section'
 *       GroupLabel = SectionNumber + ' — ' + CourseName
 *
 * Why split: PP-9 students have a stable homeroom designation in PowerSchool
 * that maps to a single elementary teacher's class. Senior students rotate
 * through multiple content sections, none of which is a "homeroom" — they're
 * grouped per content section instead, so a senior teacher sees the students
 * in their own course (e.g. "FRA12.01 — French 12").
 *
 * Role-branched historical-roster reconciliation (per
 * project_historical_roster_reconciliation memory, decided 2026-05-12):
 *   Mirrors the pattern in vw_UserAssessmentWindows. Each role branch
 *   resolves applicable students at the window's effective date.
 *
 *   - Teacher (AccessLevel IS NULL):
 *       Students in sections they taught during the window. Section context
 *       comes from FactSectionTeachers + DimSection naturally — for PP-9
 *       students this multiplies rows by section, handled by COUNT(DISTINCT
 *       StudentKey) in the final aggregation. For 10-12 students each
 *       (window, student, section) tuple is its own group row by design.
 *   - SchoolAdmin / SpecialistTeacher (AccessLevel IN (...)):
 *       Students whose DimStudent (effective at window date) had SchoolID
 *       in their CURRENT StaffSchoolAccess list. No section context from the
 *       admin branch itself — for senior students (GradeOrder >= 10) we
 *       LEFT JOIN FactEnrollment + DimSection (gated on the window effective
 *       date) to surface section groups.
 *   - RegionalAnalyst:
 *       All students whose DimStudent (effective at window date) matches the
 *       window scope. Same section-context augmentation for seniors.
 *
 * Counts (per group, per window):
 *   - ApplicableStudentCount: distinct students in this group the caller can see
 *   - EnteredStudentCount: distinct students in this group with a
 *                          FactAssessmentReading row for the window.
 *
 *   TODO (Phase 5+): EnteredStudentCount currently only counts Reading.
 *   Same Writing/Math gap as vw_UserAssessmentWindows.
 *
 * Notes:
 *   - PP-9 students with NULL Homeroom land in the 'HR:(none)' bucket — a
 *     visible bucket rather than a silently-excluded one, so missing data is
 *     surfaced.
 *   - 10-12 students with no qualifying section enrollment are dropped from
 *     the view (their GroupKey would be NULL). Acceptable for MVP — a senior
 *     student without an enrollment in the window's program scope wouldn't
 *     be assessed anyway.
 *   - Identity / time zone: same conventions as vw_UserAssessmentWindows.
 ******************************************************************************/

CREATE VIEW vw_TeacherGroups AS
WITH AtlanticToday AS (
    SELECT CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATE) AS Today
),
Caller AS (
    SELECT TOP 1
        d.StaffKey,
        LOWER(d.Email) AS Email,
        d.AccessLevel
    FROM DimStaff d
    WHERE LOWER(d.Email) = LOWER(CURRENT_USER)
      AND d.IsCurrent = 1
),
WindowEffectiveDates AS (
    SELECT
        w.AssessmentWindowID,
        w.StartDate AS WindowStartDate,
        w.EndDate   AS WindowEndDate,
        w.MinGrade,
        w.MaxGrade,
        w.ProgramFamily,
        CASE WHEN at.Today > w.EndDate THEN w.EndDate
             ELSE at.Today END AS EffectiveDate
    FROM DimAssessmentWindow w
    CROSS JOIN AtlanticToday at
    WHERE w.ActiveFlag = 1
),
-- ROLE BRANCH 1: Teacher — pulls section context naturally through
-- FactSectionTeachers → DimSection. For PP-9 students this produces
-- (window × student × section) tuples; COUNT(DISTINCT StudentKey) in
-- the final aggregation dedupes per homeroom.
TeacherApplicable AS (
    SELECT
        wed.AssessmentWindowID,
        s.StudentKey,
        s.Grade,
        sg.GradeOrder,
        s.Homeroom,
        sec.SectionID,
        sec.SectionNumber,
        sec.CourseName
    FROM Caller c
    CROSS JOIN WindowEffectiveDates wed
    INNER JOIN FactSectionTeachers fst
            ON LOWER(fst.TeacherEmail) = c.Email
           AND wed.EffectiveDate BETWEEN fst.EffectiveStartDate AND COALESCE(fst.EffectiveEndDate, '9999-12-31')
    INNER JOIN DimSection sec
            ON sec.SectionID = fst.SectionID
           AND wed.EffectiveDate BETWEEN sec.EffectiveStartDate AND COALESCE(sec.EffectiveEndDate, '9999-12-31')
    INNER JOIN FactEnrollment e
            ON e.SectionKey  = sec.SectionKey
           AND e.StartDate  <= wed.WindowEndDate
           AND (e.EndDate IS NULL OR e.EndDate >= wed.WindowStartDate)
    INNER JOIN DimStudent s
            ON s.StudentKey = e.StudentKey
    INNER JOIN DimGrade   sg   ON sg.GradeCode   = s.Grade
    INNER JOIN DimGrade   wmin ON wmin.GradeCode = wed.MinGrade
    INNER JOIN DimGrade   wmax ON wmax.GradeCode = wed.MaxGrade
    INNER JOIN DimProgram dp   ON dp.ProgramCode = s.ProgramCode
    WHERE c.AccessLevel IS NULL
      AND sg.GradeOrder BETWEEN wmin.GradeOrder AND wmax.GradeOrder
      AND (wed.ProgramFamily IS NULL OR dp.ProgramFamily = wed.ProgramFamily)
),
-- ROLE BRANCH 2: SchoolAdmin / SpecialistTeacher — gated via StaffSchoolAccess.
-- One row per (window, student). Section context filled in later via the
-- senior-augmentation LEFT JOIN.
AdminApplicable AS (
    SELECT
        wed.AssessmentWindowID,
        wed.WindowStartDate,
        wed.WindowEndDate,
        wed.EffectiveDate,
        s.StudentKey,
        s.Grade,
        sg.GradeOrder,
        s.Homeroom
    FROM Caller c
    CROSS JOIN WindowEffectiveDates wed
    INNER JOIN StaffSchoolAccess ssa
            ON ssa.StaffKey = c.StaffKey
    INNER JOIN DimStudent s
            ON s.SchoolID = ssa.SchoolID
           AND wed.EffectiveDate BETWEEN s.EffectiveStartDate AND COALESCE(s.EffectiveEndDate, '9999-12-31')
    INNER JOIN DimGrade   sg   ON sg.GradeCode   = s.Grade
    INNER JOIN DimGrade   wmin ON wmin.GradeCode = wed.MinGrade
    INNER JOIN DimGrade   wmax ON wmax.GradeCode = wed.MaxGrade
    INNER JOIN DimProgram dp   ON dp.ProgramCode = s.ProgramCode
    WHERE c.AccessLevel IN ('Administrator', 'SpecialistTeacher')
      AND sg.GradeOrder BETWEEN wmin.GradeOrder AND wmax.GradeOrder
      AND (wed.ProgramFamily IS NULL OR dp.ProgramFamily = wed.ProgramFamily)
),
-- ROLE BRANCH 3: RegionalAnalyst — full population gated only by window scope.
AnalystApplicable AS (
    SELECT
        wed.AssessmentWindowID,
        wed.WindowStartDate,
        wed.WindowEndDate,
        wed.EffectiveDate,
        s.StudentKey,
        s.Grade,
        sg.GradeOrder,
        s.Homeroom
    FROM Caller c
    CROSS JOIN WindowEffectiveDates wed
    INNER JOIN DimStudent s
            ON wed.EffectiveDate BETWEEN s.EffectiveStartDate AND COALESCE(s.EffectiveEndDate, '9999-12-31')
    INNER JOIN DimGrade   sg   ON sg.GradeCode   = s.Grade
    INNER JOIN DimGrade   wmin ON wmin.GradeCode = wed.MinGrade
    INNER JOIN DimGrade   wmax ON wmax.GradeCode = wed.MaxGrade
    INNER JOIN DimProgram dp   ON dp.ProgramCode = s.ProgramCode
    WHERE c.AccessLevel = 'RegionalAnalyst'
      AND sg.GradeOrder BETWEEN wmin.GradeOrder AND wmax.GradeOrder
      AND (wed.ProgramFamily IS NULL OR dp.ProgramFamily = wed.ProgramFamily)
),
-- For admin/analyst rows that need section context (only seniors, GradeOrder >= 10):
-- LEFT JOIN FactEnrollment + DimSection effective at the window date. Each
-- senior student produces one row per section they're enrolled in within
-- the window's date envelope. PP-9 admin/analyst rows pass through unchanged
-- (LEFT JOIN finds no match, section columns stay NULL).
AdminAnalystWithSections AS (
    SELECT
        a.AssessmentWindowID,
        a.StudentKey,
        a.Grade,
        a.GradeOrder,
        a.Homeroom,
        sec.SectionID,
        sec.SectionNumber,
        sec.CourseName
    FROM (
        SELECT * FROM AdminApplicable
        UNION ALL
        SELECT * FROM AnalystApplicable
    ) a
    LEFT JOIN FactEnrollment e
           ON a.GradeOrder >= 10
          AND e.StudentKey  = a.StudentKey
          AND e.StartDate  <= a.WindowEndDate
          AND (e.EndDate IS NULL OR e.EndDate >= a.WindowStartDate)
    LEFT JOIN DimSection sec
           ON sec.SectionKey = e.SectionKey
          AND a.EffectiveDate BETWEEN sec.EffectiveStartDate AND COALESCE(sec.EffectiveEndDate, '9999-12-31')
),
-- Union all three role branches into one uniform shape.
ApplicableStudents AS (
    SELECT AssessmentWindowID, StudentKey, Grade, GradeOrder, Homeroom,
           SectionID, SectionNumber, CourseName
    FROM TeacherApplicable
    UNION ALL
    SELECT AssessmentWindowID, StudentKey, Grade, GradeOrder, Homeroom,
           SectionID, SectionNumber, CourseName
    FROM AdminAnalystWithSections
),
-- Resolve group key/label/type per row.
StudentGroups AS (
    SELECT
        AssessmentWindowID,
        StudentKey,
        Grade,
        CASE WHEN GradeOrder <= 9  THEN 'HR:'  + COALESCE(Homeroom, '(none)')
             WHEN GradeOrder >= 10 AND SectionID IS NOT NULL THEN 'SEC:' + SectionID
        END AS GroupKey,
        CASE WHEN GradeOrder <= 9  THEN 'Homeroom'
             WHEN GradeOrder >= 10 AND SectionID IS NOT NULL THEN 'Section'
        END AS GroupType,
        CASE WHEN GradeOrder <= 9  THEN 'Homeroom ' + COALESCE(Homeroom, '(none)')
             WHEN GradeOrder >= 10 AND SectionID IS NOT NULL THEN SectionNumber + ' — ' + CourseName
        END AS GroupLabel
    FROM ApplicableStudents
)
SELECT
    CAST(sg.AssessmentWindowID AS VARCHAR(20)) AS AssessmentWindowID,   -- BIGINT cast to VARCHAR for Power Fx precision; see feedback_powerapps_bigint_precision memory
    sg.GroupKey,
    sg.GroupType,
    sg.GroupLabel,
    MAX(sg.Grade) AS Grade,                                 -- one grade per group by construction; MAX is safe
    COUNT(DISTINCT sg.StudentKey) AS ApplicableStudentCount,
    COUNT(DISTINCT CASE WHEN far.ReadingAssessmentID IS NOT NULL
                        THEN sg.StudentKey END) AS EnteredStudentCount   -- TODO Phase 5+: extend for Writing/Math
FROM StudentGroups sg
LEFT JOIN FactAssessmentReading far
       ON far.AssessmentWindowID = sg.AssessmentWindowID
      AND far.StudentKey         = sg.StudentKey
WHERE sg.GroupKey IS NOT NULL                               -- drops seniors with no qualifying section enrollment
GROUP BY sg.AssessmentWindowID, sg.GroupKey, sg.GroupType, sg.GroupLabel;


/* ========== sql/security/vw_TeacherRoster.sql ========== */
/*******************************************************************************
 * View: vw_TeacherRoster
 * Purpose: Returns one row per (calling user, applicable window, group,
 *          student) tuple with existing reading-assessment value if any.
 *          Powers `scrRosterGrid` in the Power Apps entry app. Power Apps
 *          filters client-side by gblSelectedWindow.AssessmentWindowID AND
 *          gblSelectedGroup.GroupKey.
 * Created: 2026-05-13
 * Region: Canada East (PIIDPA compliant)
 *
 * Companion view to vw_TeacherGroups — same role-branched historical-roster
 * reconciliation, same group-resolution rules (PP-9 → 'HR:' + Homeroom;
 * 10-12/RG → 'SEC:' + SectionID). See vw_TeacherGroups header for the full
 * reconciliation rationale.
 *
 * "Existing assessment" semantics:
 *   - One assessment per (StudentKey, AssessmentWindowID) by design.
 *   - LEFT JOIN to FactAssessmentReading on that pair surfaces the prior
 *     entry's ReadingScaleID + LevelCode + AssessmentDate if any.
 *   - Power Apps displays the level code (or "—" via Coalesce) in the
 *     "Existing Level" column; the upsert proc resolves new-value writes
 *     against the same (Student, Window) key.
 *
 *   TODO (Phase 5+): the "existing" columns are Reading-only. When Writing/
 *   Math entry screens go live, either branch this view by AssessmentType
 *   or build sibling views (vw_WritingRoster / vw_MathRoster).
 *
 * Dedup note:
 *   The teacher role branch can produce multiple rows for the same student
 *   (one per section the teacher teaches them in). For PP-9 students grouped
 *   by homeroom, those rows collapse to the same (window, group, student)
 *   triple — the final SELECT DISTINCT dedupes. For 10-12 students grouped
 *   by section, each section is its own group, so multi-section enrollment
 *   produces multiple group rows by design.
 *
 * Identity / time zone: same conventions as vw_UserAssessmentWindows /
 * vw_TeacherGroups.
 ******************************************************************************/

CREATE VIEW vw_TeacherRoster AS
WITH AtlanticToday AS (
    SELECT CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATE) AS Today
),
Caller AS (
    SELECT TOP 1
        d.StaffKey,
        LOWER(d.Email) AS Email,
        d.AccessLevel
    FROM DimStaff d
    WHERE LOWER(d.Email) = LOWER(CURRENT_USER)
      AND d.IsCurrent = 1
),
WindowEffectiveDates AS (
    SELECT
        w.AssessmentWindowID,
        w.StartDate AS WindowStartDate,
        w.EndDate   AS WindowEndDate,
        w.MinGrade,
        w.MaxGrade,
        w.ProgramFamily,
        CASE WHEN at.Today > w.EndDate THEN w.EndDate
             ELSE at.Today END AS EffectiveDate
    FROM DimAssessmentWindow w
    CROSS JOIN AtlanticToday at
    WHERE w.ActiveFlag = 1
),
-- ROLE BRANCH 1: Teacher
TeacherApplicable AS (
    SELECT
        wed.AssessmentWindowID,
        s.StudentKey,
        s.StudentNumber,
        s.FirstName,
        s.LastName,
        s.Grade,
        sg.GradeOrder,
        s.Homeroom,
        s.ProgramCode,
        dp.ProgramFamily,
        sec.SectionID,
        sec.SectionNumber,
        sec.CourseName
    FROM Caller c
    CROSS JOIN WindowEffectiveDates wed
    INNER JOIN FactSectionTeachers fst
            ON LOWER(fst.TeacherEmail) = c.Email
           AND wed.EffectiveDate BETWEEN fst.EffectiveStartDate AND COALESCE(fst.EffectiveEndDate, '9999-12-31')
    INNER JOIN DimSection sec
            ON sec.SectionID = fst.SectionID
           AND wed.EffectiveDate BETWEEN sec.EffectiveStartDate AND COALESCE(sec.EffectiveEndDate, '9999-12-31')
    INNER JOIN FactEnrollment e
            ON e.SectionKey  = sec.SectionKey
           AND e.StartDate  <= wed.WindowEndDate
           AND (e.EndDate IS NULL OR e.EndDate >= wed.WindowStartDate)
    INNER JOIN DimStudent s
            ON s.StudentKey = e.StudentKey
    INNER JOIN DimGrade   sg   ON sg.GradeCode   = s.Grade
    INNER JOIN DimGrade   wmin ON wmin.GradeCode = wed.MinGrade
    INNER JOIN DimGrade   wmax ON wmax.GradeCode = wed.MaxGrade
    INNER JOIN DimProgram dp   ON dp.ProgramCode = s.ProgramCode
    WHERE c.AccessLevel IS NULL
      AND sg.GradeOrder BETWEEN wmin.GradeOrder AND wmax.GradeOrder
      AND (wed.ProgramFamily IS NULL OR dp.ProgramFamily = wed.ProgramFamily)
),
-- ROLE BRANCH 2: SchoolAdmin / SpecialistTeacher
AdminApplicable AS (
    SELECT
        wed.AssessmentWindowID,
        wed.WindowStartDate,
        wed.WindowEndDate,
        wed.EffectiveDate,
        s.StudentKey,
        s.StudentNumber,
        s.FirstName,
        s.LastName,
        s.Grade,
        sg.GradeOrder,
        s.Homeroom,
        s.ProgramCode,
        dp.ProgramFamily
    FROM Caller c
    CROSS JOIN WindowEffectiveDates wed
    INNER JOIN StaffSchoolAccess ssa
            ON ssa.StaffKey = c.StaffKey
    INNER JOIN DimStudent s
            ON s.SchoolID = ssa.SchoolID
           AND wed.EffectiveDate BETWEEN s.EffectiveStartDate AND COALESCE(s.EffectiveEndDate, '9999-12-31')
    INNER JOIN DimGrade   sg   ON sg.GradeCode   = s.Grade
    INNER JOIN DimGrade   wmin ON wmin.GradeCode = wed.MinGrade
    INNER JOIN DimGrade   wmax ON wmax.GradeCode = wed.MaxGrade
    INNER JOIN DimProgram dp   ON dp.ProgramCode = s.ProgramCode
    WHERE c.AccessLevel IN ('Administrator', 'SpecialistTeacher')
      AND sg.GradeOrder BETWEEN wmin.GradeOrder AND wmax.GradeOrder
      AND (wed.ProgramFamily IS NULL OR dp.ProgramFamily = wed.ProgramFamily)
),
-- ROLE BRANCH 3: RegionalAnalyst
AnalystApplicable AS (
    SELECT
        wed.AssessmentWindowID,
        wed.WindowStartDate,
        wed.WindowEndDate,
        wed.EffectiveDate,
        s.StudentKey,
        s.StudentNumber,
        s.FirstName,
        s.LastName,
        s.Grade,
        sg.GradeOrder,
        s.Homeroom,
        s.ProgramCode,
        dp.ProgramFamily
    FROM Caller c
    CROSS JOIN WindowEffectiveDates wed
    INNER JOIN DimStudent s
            ON wed.EffectiveDate BETWEEN s.EffectiveStartDate AND COALESCE(s.EffectiveEndDate, '9999-12-31')
    INNER JOIN DimGrade   sg   ON sg.GradeCode   = s.Grade
    INNER JOIN DimGrade   wmin ON wmin.GradeCode = wed.MinGrade
    INNER JOIN DimGrade   wmax ON wmax.GradeCode = wed.MaxGrade
    INNER JOIN DimProgram dp   ON dp.ProgramCode = s.ProgramCode
    WHERE c.AccessLevel = 'RegionalAnalyst'
      AND sg.GradeOrder BETWEEN wmin.GradeOrder AND wmax.GradeOrder
      AND (wed.ProgramFamily IS NULL OR dp.ProgramFamily = wed.ProgramFamily)
),
-- Senior section context for admin/analyst rows (only GradeOrder >= 10).
AdminAnalystWithSections AS (
    SELECT
        a.AssessmentWindowID,
        a.StudentKey,
        a.StudentNumber,
        a.FirstName,
        a.LastName,
        a.Grade,
        a.GradeOrder,
        a.Homeroom,
        a.ProgramCode,
        a.ProgramFamily,
        sec.SectionID,
        sec.SectionNumber,
        sec.CourseName
    FROM (
        SELECT * FROM AdminApplicable
        UNION ALL
        SELECT * FROM AnalystApplicable
    ) a
    LEFT JOIN FactEnrollment e
           ON a.GradeOrder >= 10
          AND e.StudentKey  = a.StudentKey
          AND e.StartDate  <= a.WindowEndDate
          AND (e.EndDate IS NULL OR e.EndDate >= a.WindowStartDate)
    LEFT JOIN DimSection sec
           ON sec.SectionKey = e.SectionKey
          AND a.EffectiveDate BETWEEN sec.EffectiveStartDate AND COALESCE(sec.EffectiveEndDate, '9999-12-31')
),
ApplicableStudents AS (
    SELECT AssessmentWindowID, StudentKey, StudentNumber, FirstName, LastName,
           Grade, GradeOrder, Homeroom, ProgramCode, ProgramFamily,
           SectionID, SectionNumber, CourseName
    FROM TeacherApplicable
    UNION ALL
    SELECT AssessmentWindowID, StudentKey, StudentNumber, FirstName, LastName,
           Grade, GradeOrder, Homeroom, ProgramCode, ProgramFamily,
           SectionID, SectionNumber, CourseName
    FROM AdminAnalystWithSections
),
StudentGroups AS (
    SELECT
        AssessmentWindowID,
        StudentKey,
        StudentNumber,
        FirstName,
        LastName,
        Grade,
        ProgramCode,
        ProgramFamily,
        CASE WHEN GradeOrder <= 9  THEN 'HR:'  + COALESCE(Homeroom, '(none)')
             WHEN GradeOrder >= 10 AND SectionID IS NOT NULL THEN 'SEC:' + SectionID
        END AS GroupKey
    FROM ApplicableStudents
)
SELECT DISTINCT
    CAST(sg.AssessmentWindowID         AS VARCHAR(20)) AS AssessmentWindowID,           -- BIGINT cast to VARCHAR for Power Fx precision (see feedback_powerapps_bigint_precision memory)
    sg.GroupKey,
    CAST(sg.StudentKey                 AS VARCHAR(20)) AS StudentKey,                   -- BIGINT IDENTITY — cast for Power Apps
    sg.StudentNumber,                                                                    -- BIGINT but provincial 10-digit number, within Power Fx safe range; left as Number
    sg.FirstName,
    sg.LastName,
    sg.Grade,
    sg.ProgramCode,
    sg.ProgramFamily,
    CAST(far.ReadingAssessmentID       AS VARCHAR(20)) AS ExistingReadingAssessmentID,  -- BIGINT IDENTITY — cast for Power Apps
    CAST(far.ReadingScaleID            AS VARCHAR(20)) AS ExistingReadingScaleID,       -- BIGINT IDENTITY — cast for Power Apps (matched against cmbNewLevel.Selected.ReadingScaleID)
    drs.LevelCode           AS ExistingScaleValue,
    far.AssessmentDate      AS ExistingAssessmentDate
FROM StudentGroups sg
LEFT JOIN FactAssessmentReading far
       ON far.AssessmentWindowID = sg.AssessmentWindowID
      AND far.StudentKey         = sg.StudentKey
LEFT JOIN DimReadingScale drs
       ON drs.ReadingScaleID = far.ReadingScaleID
WHERE sg.GroupKey IS NOT NULL;


/* ========== sql/security/vw_StudentCohort.sql ========== */
/*******************************************************************************
 * View: vw_StudentCohort
 * Purpose: Power-Apps-facing cohort view for scrStudentData. One row per
 *          student in the calling user's scope, with demographics for filters
 *          + most-recent reading evidence for the pie chart.
 *
 *          Consumed by:
 *            - scrStudentData (cohort screen): student gallery, demographic
 *              slicers (Grade, Gender, SelfIDAfrican, SelfIDIndigenous, IPP,
 *              Homeroom), and the achievement-level pie chart.
 *
 * Created: 2026-05-27
 * Region: Canada East (PIIDPA compliant)
 *
 * RLS branching (OR-across-EXISTS pattern, matching vw_StudentIPP):
 *   Regional Analyst:  full visibility (no school/student filter)
 *   Admin / SpecialistTeacher: students in their schools via StaffSchoolAccess
 *   Teacher: students currently on their section roster via FactSectionTeachers
 *
 *   Uses CURRENT_USER under Entra ID Integrated auth (not USERPRINCIPALNAME()
 *   -- the latter is not supported in Fabric Warehouse).
 *
 * "Most recent reading" semantics (locked in 2026-05-27):
 *   Lifetime-latest completed reading assessment for the student -- NOT
 *   bounded by school year or date range. The cohort screen's school-year
 *   filter affects the bar chart and detail timeline, not the pie chart's
 *   per-student "current level" classification. Tie-break by AssessmentDate
 *   DESC, then ReadingAssessmentID DESC.
 *
 * IPP gating (locked in 2026-05-27):
 *   IsChartEligibleReading is a convenience BIT for the pie chart filter.
 *   Set to 0 when the student has a current Reading IPP row (FactStudentIPP
 *   IsCurrent = 1) that is either confirmed IPP (IsIPP = 1) OR unresolved
 *   (IsIPP IS NULL). Confirmed not-IPP (IsIPP = 0) or no row at all -> 1.
 *
 * Most-recent reading columns are NULL for students with zero history. The
 *   Power Apps pie chart filters on
 *     IsChartEligibleReading = true And Not(IsBlank(MostRecentAchievementLevelCode))
 *   so unassessed students simply don't appear in the chart -- but still
 *   appear in the cohort gallery.
 *
 * Power Apps binding notes:
 *   - StudentKey, MostRecentAssessmentWindowID, MostRecentReadingScaleID,
 *     MostRecentReadingAssessmentID are CAST to VARCHAR(20) to avoid Power
 *     Fx's 16-digit ceiling on 19-digit BIGINT IDENTITY (see
 *     project_powerapps_bigint_precision memory).
 *   - StudentNumber stays BIGINT (10-digit provincial number, within range).
 *   - AchievementLevelCode is plain INT (1-4) -- no cast needed.
 *
 * After deploying this view: Power Apps users MUST remove + re-add the
 * Assessment_Warehouse data source (feedback_powerapps_data_source_refresh).
 ******************************************************************************/

DROP VIEW IF EXISTS vw_StudentCohort;
GO

CREATE VIEW vw_StudentCohort AS
WITH LatestReading AS (
    SELECT
        far.StudentKey,
        far.ReadingAssessmentID,
        far.AssessmentWindowID,
        far.ReadingScaleID,
        far.ReadingDelta,
        far.AssessmentDate,
        ROW_NUMBER() OVER (
            PARTITION BY far.StudentKey
            ORDER BY far.AssessmentDate DESC, far.ReadingAssessmentID DESC
        ) AS rn
    FROM FactAssessmentReading far
),
CurrentReadingIPP AS (
    SELECT
        fsi.StudentKey,
        fsi.ProgramFamily,
        fsi.IsIPP
    FROM FactStudentIPP fsi
    WHERE fsi.IsCurrent = 1
      AND fsi.Subject   = 'Reading'
)
SELECT
    CAST(s.StudentKey AS VARCHAR(20))                       AS StudentKey,
    s.StudentNumber,
    s.FirstName,
    s.MiddleName,
    s.LastName,
    s.FirstName + ' ' + s.LastName                          AS FullName,
    s.Grade,
    sg.GradeOrder,
    s.SchoolID,
    sch.SchoolName,
    sch.Abbreviation                                         AS SchoolAbbreviation,
    s.ProgramCode,
    p.ProgramFamily,
    s.Gender,
    s.SelfIDAfrican,
    s.SelfIDIndigenous,
    s.IPP                                                    AS IPP_PSFlag,
    s.Adap,
    s.Homeroom,
    -- IPP gate for charts (Reading, matched on student's program family)
    crd.IsIPP                                                AS IsIPP_Reading,
    CASE
        WHEN crd.StudentKey IS NULL          THEN 'N/A'         -- no applicable Reading IPP row
        WHEN crd.IsIPP IS NULL                THEN 'Unresolved'
        WHEN crd.IsIPP = 1                    THEN 'IPP'
        WHEN crd.IsIPP = 0                    THEN 'Not IPP'
    END                                                      AS IPPStatus_Reading,
    CAST(
        CASE
            WHEN crd.StudentKey IS NULL THEN 1                -- no IPP row -> eligible
            WHEN crd.IsIPP = 0           THEN 1                -- confirmed not-IPP -> eligible
            ELSE 0                                            -- IPP=1 or NULL -> exclude
        END AS BIT
    )                                                        AS IsChartEligibleReading,
    -- Most-recent reading evidence (lifetime, NULL if none)
    CAST(lr.ReadingAssessmentID AS VARCHAR(20))              AS MostRecentReadingAssessmentID,
    CAST(lr.AssessmentWindowID  AS VARCHAR(20))              AS MostRecentAssessmentWindowID,
    aw.WindowName                                            AS MostRecentWindowName,
    aw.SchoolYear                                            AS MostRecentSchoolYear,
    lr.AssessmentDate                                        AS MostRecentAssessmentDate,
    CAST(lr.ReadingScaleID      AS VARCHAR(20))              AS MostRecentReadingScaleID,
    drs.LevelCode                                            AS MostRecentLevelCode,
    drs.LevelOrder                                           AS MostRecentLevelOrder,
    lr.ReadingDelta                                          AS MostRecentReadingDelta,
    dal.AchievementLevelCode                                 AS MostRecentAchievementLevelCode,
    dal.AchievementLevelName                                 AS MostRecentAchievementLevelName,
    dal.HexColor                                             AS MostRecentAchievementHexColor,
    dal.HexColorTint                                         AS MostRecentAchievementHexColorTint
FROM DimStudent s
JOIN DimProgram p
    ON p.ProgramCode = s.ProgramCode
JOIN DimGrade sg
    ON sg.GradeCode  = s.Grade
LEFT JOIN DimSchool sch
    ON sch.SchoolID = s.SchoolID
LEFT JOIN CurrentReadingIPP crd
    ON  crd.StudentKey    = s.StudentKey
    AND crd.ProgramFamily = p.ProgramFamily
LEFT JOIN LatestReading lr
    ON  lr.StudentKey = s.StudentKey
    AND lr.rn         = 1
LEFT JOIN DimAssessmentWindow aw
    ON  aw.AssessmentWindowID = lr.AssessmentWindowID
LEFT JOIN DimReadingScale drs
    ON  drs.ReadingScaleID = lr.ReadingScaleID
LEFT JOIN DimAchievementLevel dal
    ON  dal.ActiveFlag = 1
    AND lr.ReadingDelta IS NOT NULL
    AND (
            dal.LowerBound IS NULL
         OR (dal.LowerOp = '>=' AND lr.ReadingDelta >= dal.LowerBound)
         OR (dal.LowerOp = '>'  AND lr.ReadingDelta >  dal.LowerBound)
         OR (dal.LowerOp = '='  AND lr.ReadingDelta =  dal.LowerBound)
        )
    AND (
            dal.UpperBound IS NULL
         OR (dal.UpperOp = '<=' AND lr.ReadingDelta <= dal.UpperBound)
         OR (dal.UpperOp = '<'  AND lr.ReadingDelta <  dal.UpperBound)
         OR (dal.UpperOp = '='  AND lr.ReadingDelta =  dal.UpperBound)
        )
WHERE s.IsCurrent     = 1
  AND s.EnrollStatus IN (0, -1)
  AND (
        -- Regional Analyst: full visibility
        EXISTS (
            SELECT 1 FROM DimStaff staff
            WHERE LOWER(staff.Email) = LOWER(CURRENT_USER)
              AND staff.IsCurrent    = 1
              AND staff.AccessLevel  = 'RegionalAnalyst'
        )
        OR
        -- Administrator / SpecialistTeacher: school-scoped
        EXISTS (
            SELECT 1 FROM StaffSchoolAccess ssa
            WHERE LOWER(ssa.Email)   = LOWER(CURRENT_USER)
              AND ssa.SchoolID       = s.SchoolID
              AND ssa.AccessLevel   IN ('Administrator', 'SpecialistTeacher')
        )
        OR
        -- Teacher: section-roster-scoped
        EXISTS (
            SELECT 1
            FROM   FactSectionTeachers fst
            JOIN   DimSection sec
                ON sec.SectionID = fst.SectionID
               AND sec.IsCurrent = 1
            JOIN   FactEnrollment e
                ON e.SectionKey  = sec.SectionKey
               AND e.ActiveFlag  = 1
            WHERE LOWER(fst.TeacherEmail) = LOWER(CURRENT_USER)
              AND fst.IsCurrent = 1
              AND e.StudentKey  = s.StudentKey
        )
      );
GO


/* ========== sql/security/vw_StudentAssessmentHistory.sql ========== */
/*******************************************************************************
 * View: vw_StudentAssessmentHistory
 * Purpose: Power-Apps-facing history view for scrStudentData. One row per
 *          (student, completed reading assessment) for students in the
 *          calling user's scope. Powers the cohort bar chart (achievement
 *          distribution across windows in the selected date range) and the
 *          per-student detail timelines (reading level / achievement /
 *          difference over time).
 *
 * Created: 2026-05-27
 * Region: Canada East (PIIDPA compliant)
 *
 * Grain: one row per (StudentKey, ReadingAssessmentID).
 *
 * Date range / school year filtering:
 *   Done client-side in Power Apps. The view exposes WindowSchoolYear,
 *   WindowStartDate, WindowEndDate, and AssessmentDate -- Power Apps applies
 *   the active filter (default current school year) at the collection level.
 *
 * IPP gating:
 *   IsChartEligibleReading is computed the same way as in vw_StudentCohort
 *   (CURRENT IPP-Reading status for the student's program family). Per the
 *   2026-05-27 design decision, IPP students (confirmed OR unresolved) are
 *   excluded from charts. The detail timeline screen may choose to surface
 *   their data anyway -- the column is present for filtering, not enforced.
 *
 * RLS branching: same OR-across-EXISTS pattern as vw_StudentCohort /
 *   vw_StudentIPP. Regional Analyst -> all; Admin/SpecialistTeacher -> their
 *   schools; Teacher -> current section roster.
 *
 * Power Apps binding notes:
 *   - StudentKey, ReadingAssessmentID, AssessmentWindowID, ReadingScaleID
 *     CAST to VARCHAR(20) (project_powerapps_bigint_precision).
 *   - StudentNumber stays BIGINT (10-digit, within Power Fx safe range).
 *
 * After deploying: Power Apps users MUST remove + re-add the
 * Assessment_Warehouse data source (feedback_powerapps_data_source_refresh).
 ******************************************************************************/

DROP VIEW IF EXISTS vw_StudentAssessmentHistory;
GO

CREATE VIEW vw_StudentAssessmentHistory AS
WITH CurrentReadingIPP AS (
    SELECT
        fsi.StudentKey,
        fsi.ProgramFamily,
        fsi.IsIPP
    FROM FactStudentIPP fsi
    WHERE fsi.IsCurrent = 1
      AND fsi.Subject   = 'Reading'
)
SELECT
    CAST(s.StudentKey         AS VARCHAR(20))               AS StudentKey,
    s.StudentNumber,
    s.FirstName,
    s.LastName,
    s.FirstName + ' ' + s.LastName                          AS FullName,
    s.Grade,
    s.SchoolID,
    s.ProgramCode,
    p.ProgramFamily                                          AS StudentProgramFamily,
    -- IPP gate (same convention as vw_StudentCohort)
    CAST(
        CASE
            WHEN crd.StudentKey IS NULL THEN 1
            WHEN crd.IsIPP = 0           THEN 1
            ELSE 0
        END AS BIT
    )                                                        AS IsChartEligibleReading,
    -- Assessment record
    CAST(far.ReadingAssessmentID AS VARCHAR(20))             AS ReadingAssessmentID,
    CAST(far.AssessmentWindowID  AS VARCHAR(20))             AS AssessmentWindowID,
    aw.WindowName,
    aw.AssessmentType,
    aw.SchoolYear                                            AS WindowSchoolYear,
    aw.StartDate                                             AS WindowStartDate,
    aw.EndDate                                               AS WindowEndDate,
    aw.ProgramFamily                                         AS WindowProgramFamily,
    aw.ScaleSystem,
    far.AssessmentDate,
    CAST(far.ReadingScaleID AS VARCHAR(20))                  AS ReadingScaleID,
    drs.LevelCode,
    drs.LevelOrder,
    far.ReadingDelta,
    dal.AchievementLevelCode,
    dal.AchievementLevelName,
    dal.HexColor                                             AS AchievementHexColor,
    dal.HexColorTint                                         AS AchievementHexColorTint
FROM FactAssessmentReading far
JOIN DimStudent s
    ON  s.StudentKey = far.StudentKey
    AND s.IsCurrent  = 1
JOIN DimProgram p
    ON p.ProgramCode = s.ProgramCode
JOIN DimAssessmentWindow aw
    ON aw.AssessmentWindowID = far.AssessmentWindowID
JOIN DimReadingScale drs
    ON drs.ReadingScaleID = far.ReadingScaleID
LEFT JOIN CurrentReadingIPP crd
    ON  crd.StudentKey    = s.StudentKey
    AND crd.ProgramFamily = p.ProgramFamily
LEFT JOIN DimAchievementLevel dal
    ON  dal.ActiveFlag = 1
    AND far.ReadingDelta IS NOT NULL
    AND (
            dal.LowerBound IS NULL
         OR (dal.LowerOp = '>=' AND far.ReadingDelta >= dal.LowerBound)
         OR (dal.LowerOp = '>'  AND far.ReadingDelta >  dal.LowerBound)
         OR (dal.LowerOp = '='  AND far.ReadingDelta =  dal.LowerBound)
        )
    AND (
            dal.UpperBound IS NULL
         OR (dal.UpperOp = '<=' AND far.ReadingDelta <= dal.UpperBound)
         OR (dal.UpperOp = '<'  AND far.ReadingDelta <  dal.UpperBound)
         OR (dal.UpperOp = '='  AND far.ReadingDelta =  dal.UpperBound)
        )
WHERE s.EnrollStatus IN (0, -1)
  AND (
        -- Regional Analyst: full visibility
        EXISTS (
            SELECT 1 FROM DimStaff staff
            WHERE LOWER(staff.Email) = LOWER(CURRENT_USER)
              AND staff.IsCurrent    = 1
              AND staff.AccessLevel  = 'RegionalAnalyst'
        )
        OR
        -- Administrator / SpecialistTeacher: school-scoped
        EXISTS (
            SELECT 1 FROM StaffSchoolAccess ssa
            WHERE LOWER(ssa.Email)   = LOWER(CURRENT_USER)
              AND ssa.SchoolID       = s.SchoolID
              AND ssa.AccessLevel   IN ('Administrator', 'SpecialistTeacher')
        )
        OR
        -- Teacher: section-roster-scoped
        EXISTS (
            SELECT 1
            FROM   FactSectionTeachers fst
            JOIN   DimSection sec
                ON sec.SectionID = fst.SectionID
               AND sec.IsCurrent = 1
            JOIN   FactEnrollment e
                ON e.SectionKey  = sec.SectionKey
               AND e.ActiveFlag  = 1
            WHERE LOWER(fst.TeacherEmail) = LOWER(CURRENT_USER)
              AND fst.IsCurrent = 1
              AND e.StudentKey  = s.StudentKey
        )
      );
GO


/* ========== sql/security/vw_StudentIPP.sql ========== */
/*******************************************************************************
 * View: vw_StudentIPP
 * Purpose: Power-Apps-facing view of per-student IPP status, RLS-filtered to
 *          the calling user's scope. Long format: one row per (Student,
 *          Subject, ProgramFamily) where a current FactStudentIPP row exists.
 *          Non-applicable combinations (e.g. English Reading IPP for an FI
 *          grade-1 student) simply don't appear -- the screen renders those
 *          cells as "n/a" by absence.
 *
 *          Consumed by:
 *            - scrIPP (the bulk IPP management screen): primary data source.
 *            - scrRosterGrid: inline IPP gating check (does this row's matching
 *              (Subject, ProgramFamily) have IsIPP = NULL?).
 *            - scrGroupSelect: red alert when any student in a section has a
 *              matching NULL IsIPP for the current assessment context.
 *
 * Created: 2026-05-26
 * Region: Canada East (PIIDPA compliant)
 *
 * RLS branching (role-branched via OR across three EXISTS clauses):
 *   Regional Analyst:  sees all current IPP rows (no school/student filter)
 *   Admin / SpecialistTeacher: sees rows for students in their schools
 *                              (StaffSchoolAccess.AccessLevel IN
 *                              'Administrator','SpecialistTeacher')
 *   Teacher: sees rows for students on their current section roster
 *            (FactSectionTeachers matching CURRENT_USER, joined through
 *            DimSection / FactEnrollment to DimStudent)
 *
 *   Uses CURRENT_USER (not USERPRINCIPALNAME() -- the latter is not supported
 *   in Fabric Warehouse SQL; CURRENT_USER returns the same UPN under Entra
 *   auth).
 *
 * Power Apps binding notes:
 *   - StudentKey and StudentIPPID are CAST to VARCHAR(20) to dodge Power Fx's
 *     16-digit precision ceiling on 19-digit BIGINT IDENTITY values (see
 *     project_powerapps_bigint_precision memory).
 *   - StudentNumber stays BIGINT (10-digit provincial number; within Power
 *     Fx safe range).
 *
 * After deploying this view: Power Apps users MUST remove + re-add the
 * Assessment_Warehouse data source so the connector picks up the new view
 * (per feedback_powerapps_data_source_refresh memory).
 ******************************************************************************/

DROP VIEW IF EXISTS vw_StudentIPP;
GO

CREATE VIEW vw_StudentIPP AS
SELECT
    CAST(s.StudentKey AS VARCHAR(20))         AS StudentKey,
    s.StudentNumber,
    s.FirstName,
    s.MiddleName,
    s.LastName,
    s.Grade,
    s.Homeroom,
    s.SchoolID,
    s.ProgramCode,
    p.ProgramFamily                            AS StudentProgramFamily,
    fsi.Subject,
    fsi.ProgramFamily                          AS IPPProgramFamily,
    fsi.IsIPP,
    CAST(fsi.StudentIPPID AS VARCHAR(20))      AS StudentIPPID,
    fsi.EffectiveStartDate                     AS IPPEffectiveStartDate,
    fsi.ChangedBy                              AS IPPChangedBy
FROM DimStudent s
JOIN DimProgram p
    ON p.ProgramCode = s.ProgramCode
JOIN FactStudentIPP fsi
    ON  fsi.StudentKey = s.StudentKey
    AND fsi.IsCurrent  = 1
WHERE s.IsCurrent = 1
  AND (
        -- Regional Analyst: full visibility
        EXISTS (
            SELECT 1 FROM DimStaff staff
            WHERE LOWER(staff.Email) = LOWER(CURRENT_USER)
              AND staff.IsCurrent  = 1
              AND staff.AccessLevel = 'RegionalAnalyst'
        )
        OR
        -- Administrator / SpecialistTeacher: school-scoped
        EXISTS (
            SELECT 1 FROM StaffSchoolAccess ssa
            WHERE LOWER(ssa.Email) = LOWER(CURRENT_USER)
              AND ssa.SchoolID     = s.SchoolID
              AND ssa.AccessLevel IN ('Administrator', 'SpecialistTeacher')
        )
        OR
        -- Teacher: section-roster-scoped
        EXISTS (
            SELECT 1
            FROM   FactSectionTeachers fst
            JOIN   DimSection sec
                ON sec.SectionID = fst.SectionID
               AND sec.IsCurrent = 1
            JOIN   FactEnrollment e
                ON e.SectionKey  = sec.SectionKey
               AND e.ActiveFlag  = 1
            WHERE LOWER(fst.TeacherEmail) = LOWER(CURRENT_USER)
              AND fst.IsCurrent = 1
              AND e.StudentKey  = s.StudentKey
        )
      );
GO


/* ========== sql/security/vw_StudentCohortTeachers.sql ========== */
/*******************************************************************************
 * View: vw_StudentCohortTeachers
 * Purpose: Companion bridge view to vw_StudentCohort for the scrStudentData
 *          Teacher filter (Pack B). One row per (student, teacher) pair in the
 *          calling user's scope — a student appears once per distinct current
 *          section teacher. Power Apps uses it two ways:
 *            1. Teacher combo options: distinct (TeacherEmail, TeacherName)
 *            2. Filter predicate: cohort StudentKey membership against the
 *               pairs whose TeacherEmail is selected
 *
 *          Consumed by:
 *            - scrStudentData cmbFltTeacher (admin/analyst-gated multi-select)
 *
 * Created: 2026-06-11
 * Region: Canada East (PIIDPA compliant)
 *
 * Grain: DISTINCT (StudentKey, TeacherEmail, TeacherName). TeacherRole is
 *   deliberately excluded — a teacher covering the same student in two roles
 *   or two sections still yields one row, which is the grain the filter needs.
 *
 * Teacher resolution: current section teachers only — FactSectionTeachers
 *   (IsCurrent = 1) via DimSection (IsCurrent = 1) joined to active
 *   enrollments (FactEnrollment.ActiveFlag = 1). This matches the cohort
 *   screen's current-state semantics (vw_StudentCohort is current-roster
 *   scoped); historical-roster reconciliation deliberately does NOT apply
 *   here — that pattern is reserved for the window-context views.
 *
 * TeacherName: DimStaff (IsCurrent = 1) FirstName + LastName via lowercased
 *   email match; falls back to the raw TeacherEmail if the staff row is
 *   missing (e.g. teacher not yet in a staff import).
 *
 * RLS branching: identical OR-across-EXISTS block to vw_StudentCohort —
 *   Regional Analyst (all), Admin/SpecialistTeacher (their schools via
 *   StaffSchoolAccess), Teacher (their section roster). Keep the two views'
 *   RLS blocks in sync if either changes. Uses CURRENT_USER (Fabric Warehouse
 *   does not support USERPRINCIPALNAME()).
 *
 * Power Apps binding notes:
 *   - StudentKey CAST to VARCHAR(20) to match vw_StudentCohort.StudentKey
 *     (BIGINT precision — see project_powerapps_bigint_precision memory).
 *   - NEW data source: must be ADDED in Studio (first-time add picks up the
 *     current schema; no refresh dance needed).
 ******************************************************************************/

DROP VIEW IF EXISTS vw_StudentCohortTeachers;
GO

CREATE VIEW vw_StudentCohortTeachers AS
SELECT DISTINCT
    CAST(s.StudentKey AS VARCHAR(20))                        AS StudentKey,
    LOWER(fst.TeacherEmail)                                  AS TeacherEmail,
    COALESCE(staff.FirstName + ' ' + staff.LastName,
             LOWER(fst.TeacherEmail))                        AS TeacherName
FROM DimStudent s
JOIN FactEnrollment e
    ON  e.StudentKey = s.StudentKey
    AND e.ActiveFlag = 1
JOIN DimSection sec
    ON  sec.SectionKey = e.SectionKey
    AND sec.IsCurrent  = 1
JOIN FactSectionTeachers fst
    ON  fst.SectionID = sec.SectionID
    AND fst.IsCurrent = 1
LEFT JOIN DimStaff staff
    ON  LOWER(staff.Email) = LOWER(fst.TeacherEmail)
    AND staff.IsCurrent    = 1
WHERE s.IsCurrent     = 1
  AND s.EnrollStatus IN (0, -1)
  AND (
        -- Regional Analyst: full visibility
        EXISTS (
            SELECT 1 FROM DimStaff st
            WHERE LOWER(st.Email)  = LOWER(CURRENT_USER)
              AND st.IsCurrent     = 1
              AND st.AccessLevel   = 'RegionalAnalyst'
        )
        OR
        -- Administrator / SpecialistTeacher: school-scoped
        EXISTS (
            SELECT 1 FROM StaffSchoolAccess ssa
            WHERE LOWER(ssa.Email)  = LOWER(CURRENT_USER)
              AND ssa.SchoolID      = s.SchoolID
              AND ssa.AccessLevel  IN ('Administrator', 'SpecialistTeacher')
        )
        OR
        -- Teacher: section-roster-scoped
        EXISTS (
            SELECT 1
            FROM   FactSectionTeachers fst2
            JOIN   DimSection sec2
                ON sec2.SectionID = fst2.SectionID
               AND sec2.IsCurrent = 1
            JOIN   FactEnrollment e2
                ON e2.SectionKey  = sec2.SectionKey
               AND e2.ActiveFlag  = 1
            WHERE LOWER(fst2.TeacherEmail) = LOWER(CURRENT_USER)
              AND fst2.IsCurrent = 1
              AND e2.StudentKey  = s.StudentKey
        )
      );
GO


/* ========== sql/security/vw_DimReadingScale.sql ========== */
/*******************************************************************************
 * View: vw_DimReadingScale
 * Purpose: Power Apps-facing wrapper over DimReadingScale that casts the
 *          BIGINT IDENTITY ReadingScaleID to VARCHAR(20). Required because
 *          Power Fx Number is IEEE 754 double (16-digit safe max) and Fabric
 *          BIGINT IDENTITY emits ~19-digit values — direct binding loses
 *          precision and breaks any equality comparison on the key.
 *
 *          Powers the cmbNewLevel dropdown on `scrRosterGrid` and any other
 *          Power Apps surface that needs to filter / look up by ReadingScaleID.
 *
 * Created: 2026-05-21
 * Region: Canada East (PIIDPA compliant)
 *
 * See project_powerapps_bigint_precision memory for the full pattern.
 * No RLS — DimReadingScale is global reference data; all callers see all levels.
 ******************************************************************************/

CREATE VIEW vw_DimReadingScale AS
SELECT
    CAST(ReadingScaleID AS VARCHAR(20)) AS ReadingScaleID,
    LevelCode,
    LevelOrder,
    ScaleSystem,
    Description,
    ActiveFlag
FROM DimReadingScale;


/* ========== sql/security/vw_StudentReadingStartingPoint.sql ========== */
/*******************************************************************************
 * View: vw_StudentReadingStartingPoint
 * Purpose: Each student's READING "starting point" for the current school year —
 *          the last recorded reading level from the PREVIOUS school year — so the
 *          roster can show where a student began and the cumulative progress since.
 * Created: 2026-09-10
 * Region:  Canada East (PIIDPA compliant)
 *
 * YEAR-FLIP ABSTRACTION (must stay this shape): the starting point is
 *   COALESCE( latest prior-school-year FactAssessmentReading , PriorYearBaseline seed ).
 * This school year (2026-2027) the prior year (2025-2026) has NO in-system facts, so
 * it resolves to the PriorYearBaseline seed. From Sept 2027 the prior year IS in the
 * facts, so it resolves there automatically — ZERO code change at the flip; the seed
 * is only for the pre-system year. "Previous year" is derived from Atlantic today
 * (school year = Sep..Aug). Grain: one row per (StudentNumber, ScaleSystem).
 *
 * StartingLevelOrder is NULL when the level doesn't map to a DimReadingScale level
 * (e.g. a baseline code ABS/INS/EAL) — the caller then shows the level with no Δ.
 ******************************************************************************/

DROP VIEW IF EXISTS dbo.vw_StudentReadingStartingPoint;
GO

CREATE VIEW dbo.vw_StudentReadingStartingPoint
AS
WITH Today AS (
    SELECT CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATE) AS d
),
Yr AS (
    SELECT
        CASE WHEN MONTH(d) >= 9 THEN CONCAT(CAST(YEAR(d)-1 AS VARCHAR(4)), '-', CAST(YEAR(d)   AS VARCHAR(4)))
             ELSE CONCAT(CAST(YEAR(d)-2 AS VARCHAR(4)), '-', CAST(YEAR(d)-1 AS VARCHAR(4))) END AS PriorYear
    FROM Today
),
-- Latest prior-school-year reading fact per (StudentNumber, ScaleSystem).
PriorFact AS (
    SELECT
        ds.StudentNumber, drs.ScaleSystem, drs.LevelCode, drs.LevelOrder,
        ROW_NUMBER() OVER (PARTITION BY ds.StudentNumber, drs.ScaleSystem
                           ORDER BY far.AssessmentDate DESC, far.ReadingAssessmentID DESC) AS rn
    FROM FactAssessmentReading far
    INNER JOIN DimAssessmentWindow w   ON w.AssessmentWindowID = far.AssessmentWindowID
    INNER JOIN Yr                       ON w.SchoolYear        = Yr.PriorYear
    INNER JOIN DimStudent      ds       ON ds.StudentKey       = far.StudentKey
    INNER JOIN DimReadingScale drs      ON drs.ReadingScaleID  = far.ReadingScaleID
),
-- Baseline seed: only exists for the pre-system prior year (2025-2026). Map the
-- assessment language to the reading scale system; level code joins DimReadingScale.
BaselineSeed AS (
    SELECT
        b.StudentNumber,
        CASE WHEN b.AssessmentLanguage = 'French' THEN 'FR_Reading' ELSE 'EN_Reading' END AS ScaleSystem,
        b.ReadingLevel AS LevelCode
    FROM PriorYearBaseline b
    INNER JOIN Yr ON b.SchoolYear = Yr.PriorYear
    WHERE b.ReadingLevel IS NOT NULL
)
SELECT
    COALESCE(pf.StudentNumber, bs.StudentNumber) AS StudentNumber,
    COALESCE(pf.ScaleSystem,   bs.ScaleSystem)   AS ScaleSystem,
    COALESCE(pf.LevelCode,     bs.LevelCode)     AS StartingLevelCode,
    COALESCE(pf.LevelOrder,    bsrs.LevelOrder)  AS StartingLevelOrder,
    CASE WHEN pf.StudentNumber IS NOT NULL THEN 'fact' ELSE 'baseline' END AS StartingSource
FROM (SELECT * FROM PriorFact WHERE rn = 1) pf
FULL OUTER JOIN BaselineSeed bs
       ON bs.StudentNumber = pf.StudentNumber
      AND bs.ScaleSystem   = pf.ScaleSystem
LEFT JOIN DimReadingScale bsrs
       ON bsrs.ScaleSystem = bs.ScaleSystem
      AND bsrs.LevelCode   = bs.LevelCode;
GO

GRANT SELECT ON [dbo].[vw_StudentReadingStartingPoint] TO [StudentDataAssessment];
GO


