/*******************************************************************************
 * Procedure: usp_InsertSubmissionAudit
 * Purpose: Power Apps writeable wrapper for inserting one row into
 *          FactSubmissionAudit. Bypasses the Power Apps Patch/SubmitForm
 *          limitation against Fabric Warehouse tables (see project memory
 *          `project_powerapps_write_pattern.md` and fabric-warehouse-sql
 *          skill items 15-16).
 * Created: 2026-05-11
 * Region: Canada East (PIIDPA compliant)
 *
 * Why this proc exists:
 *   Power Apps cannot Patch/SubmitForm directly to Fabric Warehouse tables —
 *   Defaults() returns {} and the connector errors with generic "invalid
 *   arguments". The established workaround is per-write-target stored
 *   procedures called from Power Apps formulas via the same SQL Server
 *   connector that already works for reads. This is the first such proc and
 *   doubles as the Step 16 smoke test.
 *
 * Power Apps invocation (approximate; locale formatting may vary):
 *   'Assessment_Warehouse'.dbo.usp_InsertSubmissionAudit({
 *       RecordType:  "Test",
 *       Source:      "PowerApps",
 *       SubmittedBy: User().Email,
 *       Status:      "Test",
 *       Message:     "Step 16 connectivity smoke test",
 *       RecordCount: 0
 *   })
 *
 * Parameters:
 *   @RecordType   VARCHAR(50)  — required, e.g. 'ReadingAssessment',
 *                                'WritingAssessment', 'CSVImport', 'Test'
 *   @Source       VARCHAR(50)  — required, e.g. 'PowerApps', 'PowerSchool',
 *                                'system'
 *   @SubmittedBy  VARCHAR(255) — required, Entra UPN of submitting user
 *                                (use User().Email in Power Apps)
 *   @Status       VARCHAR(50)  — required, e.g. 'Accepted', 'Rejected',
 *                                'Test', 'AcceptedWithWarnings'
 *   @Message      VARCHAR(MAX) — optional, free-form details / error text
 *   @RecordCount  INT          — optional, count of records the audit row
 *                                describes (e.g. assessments submitted in
 *                                this batch)
 *
 * Server-populated columns:
 *   SubmissionTimestamp = GETDATE() at proc execution
 *   LastUpdated         = GETDATE() at proc execution
 *   AuditID             = IDENTITY auto-generated by Fabric Warehouse
 *
 * Constraints honored:
 *   - No OUTPUT clause (Fabric Warehouse doesn't support it — see
 *     fabric-warehouse-sql skill item 15)
 *   - All NOT NULL columns on FactSubmissionAudit are required parameters
 ******************************************************************************/

CREATE PROCEDURE usp_InsertSubmissionAudit
    @RecordType   VARCHAR(50),
    @Source       VARCHAR(50),
    @SubmittedBy  VARCHAR(255),
    @Status       VARCHAR(50),
    @Message      VARCHAR(MAX) = NULL,
    @RecordCount  INT          = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Now DATETIME2(0) = GETDATE();

    INSERT INTO FactSubmissionAudit (
        RecordType,
        Source,
        SubmittedBy,
        SubmissionTimestamp,
        Status,
        Message,
        RecordCount,
        LastUpdated
    )
    VALUES (
        @RecordType,
        @Source,
        @SubmittedBy,
        @Now,
        @Status,
        @Message,
        @RecordCount,
        @Now
    );
END;
