/*******************************************************************************
 * Procedure: usp_InsertSubmissionAudit
 * Purpose: Power Apps writeable wrapper for inserting one row into
 *          FactSubmissionAudit. Bypasses the Power Apps Patch/SubmitForm
 *          limitation against Fabric Warehouse tables (see project memory
 *          `project_powerapps_write_pattern.md` and fabric-warehouse-sql
 *          skill items 15-16).
 * Created: 2026-05-11
 * Updated: 2026-05-13 — added Layer 2 input validation
 *                      (see project_submission_validation_strategy.md)
 * Region: Canada East (PIIDPA compliant)
 *
 * Why this proc exists:
 *   Power Apps cannot Patch/SubmitForm directly to Fabric Warehouse tables —
 *   Defaults() returns {} and the connector errors with generic "invalid
 *   arguments". The established workaround is per-write-target stored
 *   procedures called from Power Apps formulas via the same SQL Server
 *   connector that already works for reads. This is the first such proc and
 *   doubles as the Step 16 smoke test.
 *
 * Power Apps invocation (approximate; locale formatting may vary):
 *   'Assessment_Warehouse'.dbo.usp_InsertSubmissionAudit({
 *       RecordType:  "Test",
 *       Source:      "PowerApps",
 *       SubmittedBy: User().Email,
 *       Status:      "Test",
 *       Message:     "Step 16 connectivity smoke test",
 *       RecordCount: 0
 *   })
 *
 * Parameters:
 *   @RecordType   VARCHAR(50)  — required, must be one of:
 *                                'ReadingAssessment', 'WritingAssessment',
 *                                'CSVImport', 'Test', 'DataQualityCheck'
 *   @Source       VARCHAR(50)  — required, must be one of:
 *                                'PowerApps', 'PowerSchool', 'system'
 *   @SubmittedBy  VARCHAR(255) — required, Entra UPN of submitting user
 *                                (use User().Email in Power Apps).
 *                                Must contain '@'. Lowercased before insert
 *                                to match the project-wide Email convention.
 *   @Status       VARCHAR(50)  — required, must be one of:
 *                                'Accepted', 'Rejected', 'Test',
 *                                'AcceptedWithWarnings'
 *   @Message      VARCHAR(MAX) — optional, free-form details / error text
 *   @RecordCount  INT          — optional, count of records the audit row
 *                                describes (e.g. assessments submitted in
 *                                this batch)
 *
 * Layer 2 validation error codes (see project_submission_validation_strategy):
 *   51010 — required parameter NULL
 *   51011 — @RecordType not in allow-list
 *   51012 — @Source not in allow-list
 *   51013 — @Status not in allow-list
 *   51014 — @SubmittedBy not an email (no '@')
 *
 * Server-populated columns:
 *   SubmissionTimestamp = GETDATE() at proc execution (UTC; convert at display)
 *   LastUpdated         = GETDATE() at proc execution (UTC; convert at display)
 *   AuditID             = IDENTITY auto-generated by Fabric Warehouse
 *
 * Constraints honored:
 *   - No OUTPUT clause (Fabric Warehouse doesn't support it — see
 *     fabric-warehouse-sql skill item 15)
 *   - All NOT NULL columns on FactSubmissionAudit are required parameters
 ******************************************************************************/

CREATE PROCEDURE usp_InsertSubmissionAudit
    @RecordType   VARCHAR(50),
    @Source       VARCHAR(50),
    @SubmittedBy  VARCHAR(255),
    @Status       VARCHAR(50),
    @Message      VARCHAR(MAX) = NULL,
    @RecordCount  INT          = NULL
AS
BEGIN
    SET NOCOUNT ON;

    -- =========================================================================
    -- Layer 2: Server-side input validation
    -- Defensive guards for anything Layer 1 (Power Apps) should have caught.
    -- See project_submission_validation_strategy.md for the full 3-layer
    -- pattern. Error codes: 51010 (NULL), 51011-51014 (allow-list / format).
    -- =========================================================================

    -- 51010: required parameters not NULL
    IF @RecordType IS NULL OR @Source IS NULL
       OR @SubmittedBy IS NULL OR @Status IS NULL
    BEGIN
        ;THROW 51010, 'usp_InsertSubmissionAudit: @RecordType, @Source, @SubmittedBy, and @Status are required (no NULLs).', 1;
    END;

    -- 51011: @RecordType allow-list
    IF @RecordType NOT IN ('ReadingAssessment', 'WritingAssessment',
                           'CSVImport', 'Test', 'DataQualityCheck')
    BEGIN
        ;THROW 51011, 'usp_InsertSubmissionAudit: @RecordType must be one of ReadingAssessment, WritingAssessment, CSVImport, Test, DataQualityCheck.', 1;
    END;

    -- 51012: @Source allow-list
    IF @Source NOT IN ('PowerApps', 'PowerSchool', 'system')
    BEGIN
        ;THROW 51012, 'usp_InsertSubmissionAudit: @Source must be one of PowerApps, PowerSchool, system.', 1;
    END;

    -- 51013: @Status allow-list
    IF @Status NOT IN ('Accepted', 'Rejected', 'Test', 'AcceptedWithWarnings')
    BEGIN
        ;THROW 51013, 'usp_InsertSubmissionAudit: @Status must be one of Accepted, Rejected, Test, AcceptedWithWarnings.', 1;
    END;

    -- 51014: @SubmittedBy must look like an email (contain '@')
    IF CHARINDEX('@', @SubmittedBy) = 0
    BEGIN
        ;THROW 51014, 'usp_InsertSubmissionAudit: @SubmittedBy must be an email address (contain ''@'').', 1;
    END;

    -- Normalize email casing to match the project-wide Email convention
    -- (DimStaff.Email, FactSectionTeachers.TeacherEmail, RLS predicates).
    SET @SubmittedBy = LOWER(@SubmittedBy);

    DECLARE @Now DATETIME2(0) = GETDATE();

    INSERT INTO FactSubmissionAudit (
        RecordType,
        Source,
        SubmittedBy,
        SubmissionTimestamp,
        Status,
        Message,
        RecordCount,
        LastUpdated
    )
    VALUES (
        @RecordType,
        @Source,
        @SubmittedBy,
        @Now,
        @Status,
        @Message,
        @RecordCount,
        @Now
    );
END;
