/* ============================================================================
   STAGE 03 — procedures changed in 0.7.0 (DROP/CREATE)
   GENERATED by scripts/generate_live_deploy_0.7.0.sh — do not hand-edit; edit sources + regen.
   0.7.0 live deploy (live is at 0.6.3). Run DEV first. Run stages in filename order.
   ============================================================================ */

/* ========== sql/procedures/usp_UpsertReadingAssessment.sql ========== */
/*******************************************************************************
 * Procedure: usp_UpsertReadingAssessment
 * Purpose: Power Apps wrapper for entering or correcting a single reading
 *          assessment. Called from `scrRosterGrid` once per dirty row in the
 *          Save batch. Implements the 3-layer validation strategy and the
 *          ReadingDelta computation against DimReadingBenchmark.
 * Created: 2026-05-13
 * Modified: 2026-05-21 — @AssessmentWindowID + @ReadingScaleID flipped from
 *                       BIGINT to VARCHAR(20) for Power Fx precision. CAST
 *                       to BIGINT locals on entry; internal logic unchanged.
 *                       See project_powerapps_bigint_precision memory.
 * Modified: 2026-06-22 — added optional @CallerUPN for the web-app/service-
 *                       principal path (Phase 3b). When passed, the caller
 *                       identity (EnteredByStaffKey + the 51030/51031 gate)
 *                       resolves from @CallerUPN instead of CURRENT_USER, which
 *                       under the SP connection is the app, not the teacher.
 *                       NULL preserves the legacy CURRENT_USER behaviour.
 *                       SECURITY: the proc now TRUSTS the caller to pass a
 *                       truthful UPN — safe only because EXECUTE is granted to
 *                       the SP alone and the web app passes an Entra-validated
 *                       UPN (same trust boundary as the @UPN bridge reads).
 * Modified: 2026-06-25 — ONGOING-ASSESSMENT model. Windows are now monthly bins
 *                       (open 1st, closed last day of month). Grain is now
 *                       (StudentKey, AssessmentWindowID, AssessmentDate): a
 *                       teacher may record MULTIPLE dated results per window —
 *                       each date is its own row (prior entries preserved); a
 *                       same-date re-save is a correction (UPDATE in place).
 *                       Closed windows are WRITEABLE (late entry) — the teacher
 *                       "closed window" block (51031) was removed. The 51017 date
 *                       gate upper bound is now MIN(today, window EndDate) so a
 *                       late entry is dated inside that window's month.
 * Region: Canada East (PIIDPA compliant)
 *
 * Behavior (grain = StudentKey x AssessmentWindowID x AssessmentDate):
 *   - INSERT path (no row yet for that triple — a NEW assessment date in the
 *       window): resolves StudentKey via effective-date join on (StudentNumber,
 *       @AssessmentDate), computes ReadingDelta, inserts. Multiple dates in one
 *       window therefore accumulate as separate rows — prior entries are kept,
 *       and cohort reads pull the latest by AssessmentDate (then entry order).
 *   - UPDATE path (a row already exists for that exact date — a correction):
 *       touches ONLY score + audit columns. StudentKey stays frozen (matched on
 *       the row's own date), per project_assessment_fact_scd_policy.
 *
 * Power Apps invocation:
 *   'Assessment_Warehouse'.dbo.usp_UpsertReadingAssessment({
 *       StudentNumber:      ThisItem.StudentNumber,
 *       AssessmentWindowID: gblSelectedWindow.AssessmentWindowID,     -- Text from vw_UserAssessmentWindows
 *       ReadingScaleID:     ThisItem.NewLevel.ReadingScaleID,          -- Text from vw_DimReadingScale
 *       AssessmentDate:     Today()
 *   })
 *
 * Parameters:
 *   @StudentNumber      BIGINT       — required, provincial 10-digit student #
 *                                      (10 digits, within Power Fx safe range)
 *   @AssessmentWindowID VARCHAR(20)  — required, must resolve to ActiveFlag=1
 *                                      (BIGINT IDENTITY surfaced as VARCHAR
 *                                      for Power Apps)
 *   @ReadingScaleID     VARCHAR(20)  — required, must resolve to ActiveFlag=1
 *                                      and ScaleSystem must match window's
 *                                      (BIGINT IDENTITY surfaced as VARCHAR
 *                                      for Power Apps)
 *   @AssessmentDate     DATE         — required (used for INSERT path's
 *                                      effective-date StudentKey resolution
 *                                      and stored on the fact row; IGNORED
 *                                      on UPDATE)
 *
 * Server-resolved:
 *   StudentKey         — via effective-date join on (StudentNumber, @AssessmentDate)
 *   EnteredByStaffKey  — via CURRENT_USER -> DimStaff(IsCurrent=1)
 *   ReadingDelta       — DimReadingBenchmark lookup + arithmetic
 *
 * THROW codes (per project_submission_validation_strategy memory):
 *   --- Layer 3 (safety nets, 51001-51009) ---
 *   51001  @StudentLevelOrder is NULL despite valid @ReadingScaleID
 *
 *   --- Layer 2 input validation (51010-51029) ---
 *   51010  required parameter NULL
 *   51011  @StudentNumber does not resolve to a DimStudent row at @AssessmentDate
 *   51012  @AssessmentWindowID does not resolve to an active window
 *   51013  @ReadingScaleID does not resolve to an active scale
 *   51014  @ReadingScaleID.ScaleSystem does not match window's ScaleSystem
 *   51015  window AssessmentType is not 'Reading'
 *   51016  student grade (at AssessmentDate) outside window's [MinGrade, MaxGrade]
 *   51017  @AssessmentDate outside [window.StartDate, MIN(today_atlantic, window.EndDate)]
 *
 *   --- Layer 2 permission failures (51030-51049) ---
 *   51030  caller not in DimStaff (IsCurrent=1)
 *   51031  RETIRED 2026-06-25 — closed windows are now writeable (ongoing-assessment
 *          model); teachers may enter late. No longer thrown.
 *   51032  window is Upcoming (not yet started) — applies to all callers
 *
 * Note: bad VARCHAR-to-BIGINT cast on @AssessmentWindowID / @ReadingScaleID
 *       throws a native conversion error (no project THROW code). Shouldn't
 *       fire in practice — Power Apps only ever sends strings sourced from
 *       the casted views.
 *
 * No OUTPUT clause (Fabric Warehouse limitation — see fabric-warehouse-sql item 15).
 *
 * Time zone: today_atlantic computed via AT TIME ZONE Atlantic Standard Time
 *            (handles DST automatically). Stored timestamps are UTC.
 ******************************************************************************/

DROP PROCEDURE IF EXISTS usp_UpsertReadingAssessment;
GO

CREATE PROCEDURE usp_UpsertReadingAssessment
    @StudentNumber      BIGINT,
    @AssessmentWindowID VARCHAR(20),
    @ReadingScaleID     VARCHAR(20),
    @AssessmentDate     DATE,
    @CallerUPN          VARCHAR(255) = NULL   -- web-app/SP path: signed-in teacher UPN; NULL -> CURRENT_USER (legacy)
AS
BEGIN
    SET NOCOUNT ON;

    -- All variables declared up front (Fabric-friendly).
    DECLARE @Now                    DATETIME2(0)  = GETDATE();
    DECLARE @Today                  DATE          = CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATE);
    DECLARE @CallerEmail            VARCHAR(255)  = LOWER(COALESCE(@CallerUPN, CURRENT_USER));
    DECLARE @CallerStaffKey         BIGINT;
    DECLARE @CallerAccessLevel      VARCHAR(50);
    DECLARE @AssessmentWindowID_BI  BIGINT;   -- BIGINT form of VARCHAR @AssessmentWindowID for joins
    DECLARE @ReadingScaleID_BI      BIGINT;   -- BIGINT form of VARCHAR @ReadingScaleID for joins
    DECLARE @WindowStartDate        DATE;
    DECLARE @WindowEndDate          DATE;
    DECLARE @WindowMinGrade         VARCHAR(10);
    DECLARE @WindowMaxGrade         VARCHAR(10);
    DECLARE @WindowProgramFamily    VARCHAR(50);
    DECLARE @WindowScaleSystem      VARCHAR(20);
    DECLARE @WindowBenchmarkMonth   INT;
    DECLARE @WindowAssessmentType   VARCHAR(20);
    DECLARE @WindowStatus           VARCHAR(20);
    DECLARE @StudentKey             BIGINT;
    DECLARE @StudentGrade           VARCHAR(10);
    DECLARE @StudentProgramCode     VARCHAR(10);
    DECLARE @StudentProgramFamily   VARCHAR(50);
    DECLARE @StudentGradeOrder      INT;
    DECLARE @MinGradeOrder          INT;
    DECLARE @MaxGradeOrder          INT;
    DECLARE @ScaleSystem            VARCHAR(20);
    DECLARE @StudentLevelOrder      INT;
    DECLARE @StudentLevelCode       VARCHAR(10);   -- actual level code, stamped on the fact (as-was)
    DECLARE @DominantMonth          INT;
    DECLARE @ExpectedMinLevel       VARCHAR(10);
    DECLARE @ExpectedMaxLevel       VARCHAR(10);
    DECLARE @ExpectedMinOrder       INT;
    DECLARE @ExpectedMaxOrder       INT;
    DECLARE @ReadingDelta           INT           = NULL;
    DECLARE @AuditWarning           VARCHAR(400)  = NULL;
    DECLARE @ExistingAssessmentID   BIGINT;

    -- =========================================================================
    -- Layer 2 — 51010: required parameter NULL guard
    -- =========================================================================
    IF @StudentNumber IS NULL OR @AssessmentWindowID IS NULL
       OR @ReadingScaleID IS NULL OR @AssessmentDate IS NULL
    BEGIN
        ;THROW 51010, 'usp_UpsertReadingAssessment: @StudentNumber, @AssessmentWindowID, @ReadingScaleID, and @AssessmentDate are all required (no NULLs).', 1;
    END;

    -- Cast VARCHAR surrogate keys to BIGINT for internal joins. Native
    -- conversion error fires if Power Apps somehow sent a non-numeric string.
    SET @AssessmentWindowID_BI = CAST(@AssessmentWindowID AS BIGINT);
    SET @ReadingScaleID_BI     = CAST(@ReadingScaleID     AS BIGINT);

    -- =========================================================================
    -- Layer 2 — 51030: caller resolves to a current DimStaff row
    -- =========================================================================
    SELECT TOP 1
        @CallerStaffKey    = StaffKey,
        @CallerAccessLevel = AccessLevel
    FROM DimStaff
    WHERE LOWER(Email) = @CallerEmail
      AND IsCurrent = 1;

    IF @CallerStaffKey IS NULL
    BEGIN
        ;THROW 51030, 'usp_UpsertReadingAssessment: caller does not resolve to a current DimStaff row. Cannot enter assessments without a staff identity.', 1;
    END;

    -- =========================================================================
    -- Layer 2 — 51012: window resolves and is active
    -- =========================================================================
    SELECT
        @WindowStartDate      = StartDate,
        @WindowEndDate        = EndDate,
        @WindowMinGrade       = MinGrade,
        @WindowMaxGrade       = MaxGrade,
        @WindowProgramFamily  = ProgramFamily,
        @WindowScaleSystem    = ScaleSystem,
        @WindowBenchmarkMonth = BenchmarkMonth,
        @WindowAssessmentType = AssessmentType
    FROM DimAssessmentWindow
    WHERE AssessmentWindowID = @AssessmentWindowID_BI
      AND ActiveFlag = 1;

    IF @WindowStartDate IS NULL
    BEGIN
        ;THROW 51012, 'usp_UpsertReadingAssessment: @AssessmentWindowID does not resolve to an active DimAssessmentWindow row.', 1;
    END;

    -- =========================================================================
    -- Layer 2 — 51015: this proc only handles Reading windows
    -- =========================================================================
    IF @WindowAssessmentType <> 'Reading'
    BEGIN
        ;THROW 51015, 'usp_UpsertReadingAssessment: window AssessmentType is not Reading. Use the matching upsert proc for Writing/Math.', 1;
    END;

    -- =========================================================================
    -- Layer 2 — window-status permission gating (51032, 51031)
    -- =========================================================================
    SET @WindowStatus =
        CASE WHEN @Today < @WindowStartDate THEN 'Upcoming'
             WHEN @Today > @WindowEndDate   THEN 'Closed'
             WHEN @Today = @WindowEndDate   THEN 'ClosesToday'
             ELSE 'Open' END;

    IF @WindowStatus = 'Upcoming'
    BEGIN
        ;THROW 51032, 'usp_UpsertReadingAssessment: window is Upcoming (not yet started). No entries allowed before the window opens.', 1;
    END;

    -- 51040: GRACE-LOCK (0.7.0). Past EndDate + the cycle's GraceHours (default 168h, from the close
    -- moment = midnight after EndDate), the window is LOCKED: read-only for everyone EXCEPT a caller
    -- holding the Literacy override (StaffAppAccess.CanOverrideLiteracy) or IsSysAdmin. Hour-granular,
    -- so compare the Atlantic NOW timestamp. @IsLocked drives the audit note.
    DECLARE @GraceHours INT, @LockBoundary DATETIME2(0), @IsLocked BIT = 0, @HasOverride BIT = 0;
    SELECT @GraceHours = COALESCE(sc.GraceHours, 168)
    FROM DimAssessmentWindow w
    LEFT JOIN DimShortCycle sc ON sc.CycleGroupID = w.CycleGroupID
    WHERE w.AssessmentWindowID = @AssessmentWindowID_BI;

    SET @LockBoundary = DATEADD(HOUR, COALESCE(@GraceHours, 168), CAST(DATEADD(DAY, 1, @WindowEndDate) AS DATETIME2(0)));
    IF CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATETIME2(0)) > @LockBoundary
        SET @IsLocked = 1;

    IF @IsLocked = 1
    BEGIN
        SELECT @HasOverride = CASE WHEN IsSysAdmin = 1 OR COALESCE(CanOverrideLiteracy, 0) = 1 THEN 1 ELSE 0 END
        FROM StaffAppAccess WHERE LOWER(Email) = @CallerEmail;
        IF @HasOverride = 0
        BEGIN
            ;THROW 51040, 'usp_UpsertReadingAssessment: this cycle is locked (grace period expired). You do not hold the Literacy override to enter data for it.', 1;
        END;
    END;

    -- Closed windows remain WRITEABLE (ongoing-assessment model, 2026-06-25): a teacher may
    -- enter a result after the month closes if entry was delayed. The 51017 date gate keeps a
    -- late entry dated inside that window's own month. The former 51031 "teachers can't edit a
    -- closed window" block was removed with this change.

    -- =========================================================================
    -- Layer 2 — 51013: scale resolves and is active. @ScaleSystem is the scale of
    -- the ENTERED level (EN_Reading / FR_Reading), which under the region-wide
    -- "Short Cycle of Response" model is the student's scale — the cycle no longer
    -- carries a ScaleSystem. The 51014 "right language for this student" check now
    -- runs AFTER the student's program is resolved (below), not against the cycle.
    -- =========================================================================
    SELECT
        @StudentLevelOrder = LevelOrder,
        @ScaleSystem       = ScaleSystem,
        @StudentLevelCode  = LevelCode
    FROM DimReadingScale
    WHERE ReadingScaleID = @ReadingScaleID_BI
      AND ActiveFlag = 1;

    IF @StudentLevelOrder IS NULL
    BEGIN
        ;THROW 51013, 'usp_UpsertReadingAssessment: @ReadingScaleID does not resolve to an active DimReadingScale row.', 1;
    END;

    -- =========================================================================
    -- Layer 2 — 51011: student resolves via effective-date join on AssessmentDate
    -- =========================================================================
    SELECT TOP 1
        @StudentKey         = s.StudentKey,
        @StudentGrade       = s.Grade,
        @StudentProgramCode = s.ProgramCode
    FROM DimStudent s
    WHERE s.StudentNumber = @StudentNumber
      AND @AssessmentDate BETWEEN s.EffectiveStartDate
                              AND COALESCE(s.EffectiveEndDate, '9999-12-31');

    IF @StudentKey IS NULL
    BEGIN
        ;THROW 51011, 'usp_UpsertReadingAssessment: @StudentNumber does not resolve to a DimStudent row effective at @AssessmentDate. Student may not have existed yet, or AssessmentDate may be wrong.', 1;
    END;

    -- Resolve student's ProgramFamily for benchmark lookup
    SELECT @StudentProgramFamily = ProgramFamily
    FROM DimProgram
    WHERE ProgramCode = @StudentProgramCode;

    -- =========================================================================
    -- Layer 2 — 51014: the entered scale must be the reading scale for the
    -- student's PROGRAM family (English -> EN_Reading, French Immersion ->
    -- FR_Reading). Region-wide "Short Cycles of Response" carry no ScaleSystem,
    -- so this "right language for this student" guard is program-based, not
    -- cycle-based. Programs with no reading scale (e.g. French Second Language)
    -- map to NULL and skip the check (they have no benchmark either — tolerated).
    -- =========================================================================
    DECLARE @ExpectedScaleSystem VARCHAR(20) =
        CASE @StudentProgramFamily
             WHEN 'English'          THEN 'EN_Reading'
             WHEN 'French Immersion' THEN 'FR_Reading'
             ELSE NULL END;

    IF @ExpectedScaleSystem IS NOT NULL AND @ScaleSystem <> @ExpectedScaleSystem
    BEGIN
        ;THROW 51014, 'usp_UpsertReadingAssessment: entered scale does not match the student''s program reading scale (e.g. EN_Reading levels for a French Immersion student).', 1;
    END;

    -- =========================================================================
    -- Layer 2 — 51016: student grade within window's [MinGrade, MaxGrade]
    -- =========================================================================
    SELECT @StudentGradeOrder = GradeOrder FROM DimGrade WHERE GradeCode = @StudentGrade;
    SELECT @MinGradeOrder     = GradeOrder FROM DimGrade WHERE GradeCode = @WindowMinGrade;
    SELECT @MaxGradeOrder     = GradeOrder FROM DimGrade WHERE GradeCode = @WindowMaxGrade;

    IF @StudentGradeOrder IS NULL OR @MinGradeOrder IS NULL OR @MaxGradeOrder IS NULL
       OR @StudentGradeOrder NOT BETWEEN @MinGradeOrder AND @MaxGradeOrder
    BEGIN
        ;THROW 51016, 'usp_UpsertReadingAssessment: student grade at AssessmentDate is outside the window grade range.', 1;
    END;

    -- =========================================================================
    -- Layer 2 — 51017: AssessmentDate within [WindowStartDate, MIN(today, WindowEndDate)].
    -- Upper bound is the window's own month-end once that month has passed, so a LATE entry
    -- into a closed window is dated INSIDE that month (correct monthly binning) and can never
    -- land in a later month. For the current (open) window the cap is today (no future-dating).
    -- =========================================================================
    IF @AssessmentDate < @WindowStartDate
       OR @AssessmentDate > CASE WHEN @Today < @WindowEndDate THEN @Today ELSE @WindowEndDate END
    BEGIN
        ;THROW 51017, 'usp_UpsertReadingAssessment: @AssessmentDate is outside this window''s range [StartDate, min(today, EndDate)].', 1;
    END;

    -- =========================================================================
    -- Benchmark month for the DimReadingBenchmark lookup. Use the EXPLICIT month
    -- set on the Short Cycle if provided; otherwise fall back to the dominant
    -- month of the range (the calendar month with the most days; a tie is broken
    -- by month number). Explicit lets a multi-month cycle target the intended
    -- grade-month expectation rather than the auto-computed one — the reason it
    -- exists is that "most days" can pick a less representative month when a cycle
    -- spans several. Property of the WINDOW, not the AssessmentDate.
    -- =========================================================================
    IF @WindowBenchmarkMonth IS NOT NULL
        SET @DominantMonth = @WindowBenchmarkMonth;
    ELSE
        SELECT TOP 1 @DominantMonth = Month
        FROM DimCalendar
        WHERE Date BETWEEN @WindowStartDate AND @WindowEndDate
        GROUP BY Month
        ORDER BY COUNT(*) DESC, Month;

    -- =========================================================================
    -- Resolve benchmark + ReadingDelta. Missing benchmark for the
    -- (ScaleSystem, ProgramFamily, GradeCode, Month) combination is a
    -- tolerated edge case — ReadingDelta = NULL + audit warning.
    -- =========================================================================
    SELECT
        @ExpectedMinLevel = ExpectedMinLevel,
        @ExpectedMaxLevel = ExpectedMaxLevel
    FROM DimReadingBenchmark
    WHERE ScaleSystem     = @ScaleSystem
      AND ProgramFamily   = @StudentProgramFamily
      AND GradeCode       = @StudentGrade
      AND AssessmentMonth = @DominantMonth;

    IF @ExpectedMinLevel IS NOT NULL
        SELECT @ExpectedMinOrder = LevelOrder
        FROM DimReadingScale
        WHERE LevelCode = @ExpectedMinLevel AND ScaleSystem = @ScaleSystem;

    IF @ExpectedMaxLevel IS NOT NULL
        SELECT @ExpectedMaxOrder = LevelOrder
        FROM DimReadingScale
        WHERE LevelCode = @ExpectedMaxLevel AND ScaleSystem = @ScaleSystem;

    IF @ExpectedMinOrder IS NULL OR @ExpectedMaxOrder IS NULL
    BEGIN
        -- Tolerated edge case: no benchmark for this (system, program, grade, month).
        -- Leave @ReadingDelta = NULL; surface a warning in the audit row so admin can decide.
        SET @AuditWarning = CONCAT(
            '[WARN: no benchmark for ScaleSystem=', @ScaleSystem,
            ', ProgramFamily=', COALESCE(@StudentProgramFamily, '(null)'),
            ', Grade=', @StudentGrade,
            ', Month=', CAST(@DominantMonth AS VARCHAR(2)), ']'
        );
    END
    ELSE IF @StudentLevelOrder IS NULL
    BEGIN
        -- Layer 3 safety net — should be impossible after Layer 2 validation.
        ;THROW 51001, 'usp_UpsertReadingAssessment: @StudentLevelOrder NULL despite valid @ReadingScaleID. Impossible state.', 1;
    END
    ELSE
    BEGIN
        SET @ReadingDelta = CASE
            WHEN @StudentLevelOrder >= @ExpectedMinOrder
             AND @StudentLevelOrder <= @ExpectedMaxOrder      THEN 0
            WHEN @StudentLevelOrder <  @ExpectedMinOrder      THEN @StudentLevelOrder - @ExpectedMinOrder
            WHEN @StudentLevelOrder >  @ExpectedMaxOrder      THEN @StudentLevelOrder - @ExpectedMaxOrder
        END;
    END;

    -- =========================================================================
    -- UPSERT into FactAssessmentReading, grain = (StudentKey, AssessmentWindowID,
    -- AssessmentDate). Ongoing-assessment model (2026-06-25): a teacher may record
    -- MULTIPLE results across a window (one per assessment DATE) -- each distinct
    -- date is its own row, so the prior entries are preserved. A re-save on the
    -- SAME date is a correction (UPDATE in place, no duplicate). Cohort reads pull
    -- the latest by AssessmentDate (then entry order); the others stay on record.
    -- StudentKey is frozen per row at its own AssessmentDate (effective-date join).
    -- =========================================================================
    SELECT @ExistingAssessmentID = ReadingAssessmentID
    FROM FactAssessmentReading
    WHERE StudentKey = @StudentKey
      AND AssessmentWindowID = @AssessmentWindowID_BI
      AND AssessmentDate = @AssessmentDate;

    IF @ExistingAssessmentID IS NOT NULL
    BEGIN
        UPDATE FactAssessmentReading
        SET ReadingScaleID       = @ReadingScaleID_BI,
            ReadingDelta         = @ReadingDelta,
            LevelCode            = @StudentLevelCode,
            ExpectedMinLevelCode = @ExpectedMinLevel,
            ExpectedMaxLevelCode = @ExpectedMaxLevel,
            EnteredByStaffKey    = @CallerStaffKey,
            SubmissionTimestamp  = @Now,
            LastUpdated          = @Now
        WHERE ReadingAssessmentID = @ExistingAssessmentID;
    END
    ELSE
    BEGIN
        INSERT INTO FactAssessmentReading (
            StudentKey, AssessmentWindowID, ReadingScaleID, ReadingDelta,
            LevelCode, ExpectedMinLevelCode, ExpectedMaxLevelCode,
            AssessmentDate, EnteredByStaffKey, SubmissionTimestamp, LastUpdated
        )
        VALUES (
            @StudentKey, @AssessmentWindowID_BI, @ReadingScaleID_BI, @ReadingDelta,
            @StudentLevelCode, @ExpectedMinLevel, @ExpectedMaxLevel,
            @AssessmentDate, @CallerStaffKey, @Now, @Now
        );
    END;

    -- =========================================================================
    -- Audit row to FactSubmissionAudit. Direct INSERT (no call to
    -- usp_InsertSubmissionAudit) since validation here is already
    -- comprehensive — re-running the wrapper's Layer 2 checks is overhead.
    -- =========================================================================
    INSERT INTO FactSubmissionAudit (
        RecordType, Source, SubmittedBy, SubmissionTimestamp, Status, Message,
        RecordCount, LastUpdated
    )
    VALUES (
        'ReadingAssessment',
        CASE WHEN @CallerUPN IS NOT NULL THEN 'WebApp' ELSE 'PowerApps' END,
        @CallerEmail,
        @Now,
        CASE WHEN @AuditWarning IS NULL THEN 'Accepted' ELSE 'AcceptedWithWarnings' END,
        CONCAT(
            'usp_UpsertReadingAssessment: ',
            CASE WHEN @ExistingAssessmentID IS NULL THEN 'INSERT' ELSE 'UPDATE' END,
            ' | StudentNumber=',      CAST(@StudentNumber AS VARCHAR(20)),
            ' | AssessmentWindowID=', @AssessmentWindowID,
            ' | ReadingScaleID=',     @ReadingScaleID,
            ' | ReadingDelta=',       COALESCE(CAST(@ReadingDelta AS VARCHAR(10)), 'NULL'),
            COALESCE(CONCAT(' ', @AuditWarning), ''),
            CASE WHEN @IsLocked = 1 THEN ' | GRACE-OVERRIDE' ELSE '' END   -- 0.7.0: save into a locked cycle via override
        ),
        1,
        @Now
    );
END;

GO

/* ========== sql/procedures/usp_UpsertWritingAssessment.sql ========== */
/*******************************************************************************
 * Procedure: usp_UpsertWritingAssessment
 * Purpose: Web-app / Power Apps wrapper for entering or correcting a single
 *          writing assessment — the four-trait rubric (Ideas, Organization,
 *          Language, Conventions), each scored 1–4 by the teacher. Mirrors
 *          usp_UpsertReadingAssessment's structure and the ongoing-assessment
 *          monthly-window model, but writing has NO reading scale, NO grade
 *          benchmark and NO delta: the teacher's scores ARE the value stored.
 *          The cohort roll-up (average of the four → achievement band) is a
 *          READ-side concern (the writing cohort/history TVFs), not stored here.
 * Created: 2026-06-25
 * Region: Canada East (PIIDPA compliant)
 *
 * Model (same as reading): windows are monthly bins; grain is
 *   (StudentKey, AssessmentWindowID, AssessmentDate). A teacher may record
 *   MULTIPLE dated results per window (each date its own row — prior entries
 *   kept; cohort pulls the latest by AssessmentDate); a same-date re-save is a
 *   correction (UPDATE in place). Closed windows are WRITEABLE (late entry); the
 *   51017 date gate caps the date at MIN(today, window EndDate) so a late entry
 *   bins into that window's month.
 *
 * Parameters:
 *   @StudentNumber      BIGINT       required, provincial 10-digit student #
 *   @AssessmentWindowID VARCHAR(20)  required, must resolve to ActiveFlag=1
 *                                    (BIGINT IDENTITY surfaced as VARCHAR for Power Fx)
 *   @IdeasScore         INT          required, 1–4
 *   @OrganizationScore  INT          required, 1–4
 *   @LanguageScore      INT          required, 1–4
 *   @ConventionsScore   VARCHAR(10)  required, '1'–'4' or 'SCR' (Scribed; omitted from the average)
 *   @AssessmentDate     DATE         required (effective-date StudentKey resolution + stored)
 *   @AssessmentLanguage VARCHAR(10)  'English'|'French' writing track (part of the grain); NULL ->
 *                                    derive from program family (single-language students)
 *   @CallerUPN          VARCHAR(255) web-app/SP path: signed-in teacher UPN; NULL -> CURRENT_USER
 *
 * THROW codes (writing variants of the shared scheme):
 *   51010  required parameter NULL
 *   51011  @StudentNumber does not resolve to a DimStudent row at @AssessmentDate
 *   51012  @AssessmentWindowID does not resolve to an active window
 *   51015  window AssessmentType is not 'Writing'
 *   51016  student grade (at AssessmentDate) outside window's [MinGrade, MaxGrade]
 *   51017  @AssessmentDate outside [window.StartDate, MIN(today_atlantic, window.EndDate)]
 *   51018  a trait score is outside 1–4
 *   51019  student ProgramFamily does not match the window's (when program-scoped), OR
 *          @AssessmentLanguage invalid for the student (French writing requires French Immersion;
 *          English writing for an immersion student requires grade 3+) — the dual-language track guard
 *   51030  caller not in DimStaff (IsCurrent=1)
 *   51032  window is Upcoming (not yet started)
 *
 * No OUTPUT clause (Fabric Warehouse limitation). Timestamps stored UTC; today
 * computed in Atlantic (DST-aware).
 ******************************************************************************/

DROP PROCEDURE IF EXISTS usp_UpsertWritingAssessment;
GO

CREATE PROCEDURE usp_UpsertWritingAssessment
    @StudentNumber      BIGINT,
    @AssessmentWindowID VARCHAR(20),
    @IdeasScore         INT,
    @OrganizationScore  INT,
    @LanguageScore      INT,
    @ConventionsScore   VARCHAR(10),  -- '1'-'4', or 'SCR' (Scribed) — scribed is omitted from the average
    @AssessmentDate     DATE,
    @AssessmentLanguage VARCHAR(10)  = NULL,  -- 'English' | 'French' writing track; NULL = derive from the student's program family (single-language students)
    @CallerUPN          VARCHAR(255) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Now                    DATETIME2(0)  = GETDATE();
    DECLARE @Today                  DATE          = CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATE);
    DECLARE @CallerEmail            VARCHAR(255)  = LOWER(COALESCE(@CallerUPN, CURRENT_USER));
    DECLARE @CallerStaffKey         BIGINT;
    DECLARE @WritingAverage         DECIMAL(4,2);   -- SCR-aware average, stamped on the fact (as-was)
    DECLARE @ConvNum                INT;            -- numeric Conventions, or NULL when 'SCR'
    DECLARE @AssessmentWindowID_BI  BIGINT;
    DECLARE @WindowStartDate        DATE;
    DECLARE @WindowEndDate          DATE;
    DECLARE @WindowMinGrade         VARCHAR(10);
    DECLARE @WindowMaxGrade         VARCHAR(10);
    DECLARE @WindowProgramFamily    VARCHAR(50);
    DECLARE @WindowAssessmentType   VARCHAR(20);
    DECLARE @WindowStatus           VARCHAR(20);
    DECLARE @StudentKey             BIGINT;
    DECLARE @StudentGrade           VARCHAR(10);
    DECLARE @StudentProgramCode     VARCHAR(10);
    DECLARE @StudentProgramFamily   VARCHAR(50);
    DECLARE @StudentGradeOrder      INT;
    DECLARE @MinGradeOrder          INT;
    DECLARE @MaxGradeOrder          INT;
    DECLARE @ExistingAssessmentID   BIGINT;

    -- 51010: required params
    IF @StudentNumber IS NULL OR @AssessmentWindowID IS NULL OR @AssessmentDate IS NULL
       OR @IdeasScore IS NULL OR @OrganizationScore IS NULL
       OR @LanguageScore IS NULL OR @ConventionsScore IS NULL
    BEGIN
        ;THROW 51010, 'usp_UpsertWritingAssessment: @StudentNumber, @AssessmentWindowID, all four trait scores, and @AssessmentDate are required (no NULLs).', 1;
    END;

    -- 51018: Ideas/Organization/Language in 1..4 (numeric); Conventions is '1'-'4' OR 'SCR' (Scribed,
    -- the only non-numeric code allowed, and only on Conventions). SCR is omitted from the read-side
    -- average (sum/count over scored traits).
    IF @IdeasScore        NOT BETWEEN 1 AND 4
       OR @OrganizationScore NOT BETWEEN 1 AND 4
       OR @LanguageScore  NOT BETWEEN 1 AND 4
    BEGIN
        ;THROW 51018, 'usp_UpsertWritingAssessment: Ideas, Organization, and Language must each be an integer 1-4.', 1;
    END;

    IF @ConventionsScore NOT IN ('1', '2', '3', '4', 'SCR')
    BEGIN
        ;THROW 51018, 'usp_UpsertWritingAssessment: Conventions must be ''1''-''4'' or ''SCR'' (Scribed).', 1;
    END;

    SET @AssessmentWindowID_BI = CAST(@AssessmentWindowID AS BIGINT);

    -- 51030: caller resolves to a current DimStaff row
    SELECT TOP 1 @CallerStaffKey = StaffKey
    FROM DimStaff WHERE LOWER(Email) = @CallerEmail AND IsCurrent = 1;

    IF @CallerStaffKey IS NULL
    BEGIN
        ;THROW 51030, 'usp_UpsertWritingAssessment: caller does not resolve to a current DimStaff row. Cannot enter assessments without a staff identity.', 1;
    END;

    -- 51012: window resolves and is active
    SELECT
        @WindowStartDate      = StartDate,
        @WindowEndDate        = EndDate,
        @WindowMinGrade       = MinGrade,
        @WindowMaxGrade       = MaxGrade,
        @WindowProgramFamily  = ProgramFamily,
        @WindowAssessmentType = AssessmentType
    FROM DimAssessmentWindow
    WHERE AssessmentWindowID = @AssessmentWindowID_BI AND ActiveFlag = 1;

    IF @WindowStartDate IS NULL
    BEGIN
        ;THROW 51012, 'usp_UpsertWritingAssessment: @AssessmentWindowID does not resolve to an active DimAssessmentWindow row.', 1;
    END;

    -- 51015: this proc only handles Writing windows
    IF @WindowAssessmentType <> 'Writing'
    BEGIN
        ;THROW 51015, 'usp_UpsertWritingAssessment: window AssessmentType is not Writing. Use the matching upsert proc for Reading/Math.', 1;
    END;

    -- Window status — block Upcoming (51032). Closed windows stay writeable (late entry).
    SET @WindowStatus =
        CASE WHEN @Today < @WindowStartDate THEN 'Upcoming'
             WHEN @Today > @WindowEndDate   THEN 'Closed'
             WHEN @Today = @WindowEndDate   THEN 'ClosesToday'
             ELSE 'Open' END;

    IF @WindowStatus = 'Upcoming'
    BEGIN
        ;THROW 51032, 'usp_UpsertWritingAssessment: window is Upcoming (not yet started). No entries allowed before the window opens.', 1;
    END;

    -- 51040: GRACE-LOCK (0.7.0). Past EndDate + the cycle's GraceHours (default 168h, from the close
    -- moment = midnight after EndDate), the window is LOCKED: read-only for everyone EXCEPT a caller
    -- holding the Literacy override (StaffAppAccess.CanOverrideLiteracy) or IsSysAdmin. Hour-granular,
    -- so compare the Atlantic NOW timestamp. @IsLocked drives the audit note.
    DECLARE @GraceHours INT, @LockBoundary DATETIME2(0), @IsLocked BIT = 0, @HasOverride BIT = 0;
    SELECT @GraceHours = COALESCE(sc.GraceHours, 168)
    FROM DimAssessmentWindow w
    LEFT JOIN DimShortCycle sc ON sc.CycleGroupID = w.CycleGroupID
    WHERE w.AssessmentWindowID = @AssessmentWindowID_BI;

    SET @LockBoundary = DATEADD(HOUR, COALESCE(@GraceHours, 168), CAST(DATEADD(DAY, 1, @WindowEndDate) AS DATETIME2(0)));
    IF CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATETIME2(0)) > @LockBoundary
        SET @IsLocked = 1;

    IF @IsLocked = 1
    BEGIN
        SELECT @HasOverride = CASE WHEN IsSysAdmin = 1 OR COALESCE(CanOverrideLiteracy, 0) = 1 THEN 1 ELSE 0 END
        FROM StaffAppAccess WHERE LOWER(Email) = @CallerEmail;
        IF @HasOverride = 0
        BEGIN
            ;THROW 51040, 'usp_UpsertWritingAssessment: this cycle is locked (grace period expired). You do not hold the Literacy override to enter data for it.', 1;
        END;
    END;

    -- 51011: student resolves via effective-date join on AssessmentDate
    SELECT TOP 1
        @StudentKey         = s.StudentKey,
        @StudentGrade       = s.Grade,
        @StudentProgramCode = s.ProgramCode
    FROM DimStudent s
    WHERE s.StudentNumber = @StudentNumber
      AND @AssessmentDate BETWEEN s.EffectiveStartDate AND COALESCE(s.EffectiveEndDate, '9999-12-31');

    IF @StudentKey IS NULL
    BEGIN
        ;THROW 51011, 'usp_UpsertWritingAssessment: @StudentNumber does not resolve to a DimStudent row effective at @AssessmentDate.', 1;
    END;

    SELECT @StudentProgramFamily = ProgramFamily FROM DimProgram WHERE ProgramCode = @StudentProgramCode;

    -- 51019: student program family matches the window's (when the window is program-scoped)
    IF @WindowProgramFamily IS NOT NULL AND ISNULL(@StudentProgramFamily, '~') <> @WindowProgramFamily
    BEGIN
        ;THROW 51019, 'usp_UpsertWritingAssessment: student ProgramFamily does not match the window ProgramFamily (e.g. an English student in a French Immersion window).', 1;
    END;

    -- 51016: student grade within window's [MinGrade, MaxGrade]
    SELECT @StudentGradeOrder = GradeOrder FROM DimGrade WHERE GradeCode = @StudentGrade;
    SELECT @MinGradeOrder     = GradeOrder FROM DimGrade WHERE GradeCode = @WindowMinGrade;
    SELECT @MaxGradeOrder     = GradeOrder FROM DimGrade WHERE GradeCode = @WindowMaxGrade;

    IF @StudentGradeOrder IS NULL OR @MinGradeOrder IS NULL OR @MaxGradeOrder IS NULL
       OR @StudentGradeOrder NOT BETWEEN @MinGradeOrder AND @MaxGradeOrder
    BEGIN
        ;THROW 51016, 'usp_UpsertWritingAssessment: student grade at AssessmentDate is outside the window grade range.', 1;
    END;

    -- 51017: AssessmentDate within [WindowStartDate, MIN(today, WindowEndDate)]
    IF @AssessmentDate < @WindowStartDate
       OR @AssessmentDate > CASE WHEN @Today < @WindowEndDate THEN @Today ELSE @WindowEndDate END
    BEGIN
        ;THROW 51017, 'usp_UpsertWritingAssessment: @AssessmentDate is outside this window''s range [StartDate, min(today, EndDate)].', 1;
    END;

    -- Language track: default to the student's program language when not supplied
    -- (single-language students), then validate against the writing tracks (mirrors
    -- usp_MergeStudent Step 6): French writing requires French Immersion; English
    -- writing for an immersion student requires grade >= 3 (ELA).
    IF @AssessmentLanguage IS NULL
        SET @AssessmentLanguage = CASE WHEN @StudentProgramFamily = 'French Immersion' THEN 'French' ELSE 'English' END;

    IF @AssessmentLanguage NOT IN ('English', 'French')
    BEGIN
        ;THROW 51019, 'usp_UpsertWritingAssessment: @AssessmentLanguage must be ''English'' or ''French''.', 1;
    END;

    IF (@AssessmentLanguage = 'French'  AND @StudentProgramFamily <> 'French Immersion')
       OR (@AssessmentLanguage = 'English' AND @StudentProgramFamily = 'French Immersion' AND @StudentGradeOrder < 3)
    BEGIN
        ;THROW 51019, 'usp_UpsertWritingAssessment: @AssessmentLanguage is not valid for this student (French writing requires French Immersion; English writing for an immersion student requires grade 3+).', 1;
    END;

    -- =========================================================================
    -- UPSERT into FactAssessmentWriting, grain = (StudentKey, AssessmentWindowID,
    -- AssessmentLanguage, AssessmentDate). A student may hold an English AND a French
    -- result in the same cycle (FI grade 3+). Same (language,date) re-save = correction;
    -- a new date = a new row (prior entries kept; cohort pulls the latest date per language).
    -- =========================================================================
    SELECT @ExistingAssessmentID = WritingAssessmentID
    FROM FactAssessmentWriting
    WHERE StudentKey = @StudentKey
      AND AssessmentWindowID = @AssessmentWindowID_BI
      AND AssessmentLanguage = @AssessmentLanguage
      AND AssessmentDate = @AssessmentDate;

    -- Writing average, stamped on the row (as-was) so the SCR rule lives in the DATA, not only in
    -- the read logic: Conventions='SCR' drops from BOTH numerator and denominator. Ideas/Org/Language
    -- are validated 1-4 (always present, 3 values); Conventions is 1-4 or 'SCR'.
    SET @ConvNum = TRY_CAST(@ConventionsScore AS INT);   -- 'SCR' -> NULL
    SET @WritingAverage =
        CAST(@IdeasScore + @OrganizationScore + @LanguageScore + COALESCE(@ConvNum, 0) AS DECIMAL(6,4))
        / (3 + CASE WHEN @ConvNum IS NULL THEN 0 ELSE 1 END);

    IF @ExistingAssessmentID IS NOT NULL
    BEGIN
        UPDATE FactAssessmentWriting
        SET IdeasScore          = @IdeasScore,
            OrganizationScore   = @OrganizationScore,
            LanguageScore       = @LanguageScore,
            ConventionsScore    = @ConventionsScore,
            WritingAverage      = @WritingAverage,
            EnteredByStaffKey   = @CallerStaffKey,
            SubmissionTimestamp = @Now,
            LastUpdated         = @Now
        WHERE WritingAssessmentID = @ExistingAssessmentID;
    END
    ELSE
    BEGIN
        INSERT INTO FactAssessmentWriting (
            StudentKey, AssessmentWindowID, AssessmentLanguage, IdeasScore, OrganizationScore,
            LanguageScore, ConventionsScore, WritingAverage, AssessmentDate, EnteredByStaffKey,
            SubmissionTimestamp, LastUpdated
        )
        VALUES (
            @StudentKey, @AssessmentWindowID_BI, @AssessmentLanguage, @IdeasScore, @OrganizationScore,
            @LanguageScore, @ConventionsScore, @WritingAverage, @AssessmentDate, @CallerStaffKey,
            @Now, @Now
        );
    END;

    -- Audit row
    INSERT INTO FactSubmissionAudit (
        RecordType, Source, SubmittedBy, SubmissionTimestamp, Status, Message, RecordCount, LastUpdated
    )
    VALUES (
        'WritingAssessment',
        CASE WHEN @CallerUPN IS NOT NULL THEN 'WebApp' ELSE 'PowerApps' END,
        @CallerEmail,
        @Now,
        'Accepted',
        CONCAT(
            'usp_UpsertWritingAssessment: ',
            CASE WHEN @ExistingAssessmentID IS NULL THEN 'INSERT' ELSE 'UPDATE' END,
            ' | StudentNumber=',      CAST(@StudentNumber AS VARCHAR(20)),
            ' | AssessmentWindowID=', @AssessmentWindowID,
            ' | Language=',           @AssessmentLanguage,
            ' | Scores I/O/L/C=',     CONCAT(@IdeasScore, '/', @OrganizationScore, '/', @LanguageScore, '/', @ConventionsScore),
            CASE WHEN @IsLocked = 1 THEN ' | GRACE-OVERRIDE' ELSE '' END   -- 0.7.0: save into a locked cycle via override
        ),
        1,
        @Now
    );
END;
GO

-- DROP+CREATE drops object grants; re-grant EXECUTE to the web-app SP so a redeploy is self-contained.
GRANT EXECUTE ON [dbo].[usp_UpsertWritingAssessment] TO [StudentDataAssessment];
GO

/* ========== sql/procedures/usp_UpsertMathAssessment.sql ========== */
/*******************************************************************************
 * Procedure: usp_UpsertMathAssessment
 * Purpose: Web-app wrapper for entering / correcting a single MATH task result
 *          (can-do 1 / cannot 0) for one student. Called once per dirty cell in
 *          the roster grid's Save batch. Mirrors usp_UpsertReadingAssessment's
 *          3-layer validation + ongoing-assessment (dated-history) upsert, but
 *          the value is a BIT and there is no benchmark/delta.
 * Created: 2026-09-03
 * Region: Canada East (PIIDPA compliant)
 *
 * Grain = (StudentKey, AssessmentWindowID, MathTaskKey, AssessmentDate). A NEW
 *   date is a new row (history kept); a same-date re-save is a correction (UPDATE).
 *   Reads pick latest-by-date. StudentKey is frozen per row at its own date.
 *
 * IPP: NOT stored per task. A student's Math IPP lives in FactStudentIPP
 *   (Subject='Math'); the grid shows "IPP" for that student's unmarked cells by
 *   reading that status. This proc only ever records real 0/1 marks. Marking a
 *   specific task 0/1 for an IPP student is a legitimate override (a real row).
 *
 * @Result: '1' or '0' to mark; NULL (or empty) to CLEAR — deletes the row for
 *   this exact (student, window, task, date) if one exists (undo a same-day
 *   mismark back to blank). Clearing never touches a prior date's row, so history
 *   is preserved; the latest surviving date then shows.
 *
 * THROW codes (aligned with usp_UpsertReadingAssessment):
 *   51010  required parameter NULL (@Result may be NULL = clear)
 *   51011  @StudentNumber does not resolve at @AssessmentDate
 *   51012  @AssessmentWindowID not an active window
 *   51013  @MathTaskKey not an active DimMathTask
 *   51015  window AssessmentType is not 'Math'
 *   51016  student grade (at date) outside window [MinGrade, MaxGrade]
 *   51017  @AssessmentDate outside [StartDate, MIN(today_atlantic, EndDate)]
 *   51018  task is not applicable to this student/cycle (task GradeCode <> the
 *          student's grade, or task AssessmentMonth <> the cycle's month)
 *   51019  @Result is not '0', '1', or NULL
 *   51030  caller not in DimStaff (IsCurrent=1)
 *   51032  window is Upcoming (not yet started)
 *
 * No OUTPUT clause (Fabric Warehouse limitation). Timestamps stored UTC; "today"
 * computed in Atlantic (DST-aware).
 ******************************************************************************/

DROP PROCEDURE IF EXISTS usp_UpsertMathAssessment;
GO

CREATE PROCEDURE usp_UpsertMathAssessment
    @StudentNumber      BIGINT,
    @AssessmentWindowID VARCHAR(20),
    @MathTaskKey        VARCHAR(20),
    @Result             VARCHAR(10),          -- '1' / '0' to mark; NULL or '' to clear
    @AssessmentDate     DATE,
    @CallerUPN          VARCHAR(255) = NULL   -- signed-in teacher UPN; NULL -> CURRENT_USER (legacy)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Now                    DATETIME2(0) = GETDATE();
    DECLARE @Today                  DATE         = CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATE);
    DECLARE @CallerEmail            VARCHAR(255) = LOWER(COALESCE(@CallerUPN, CURRENT_USER));
    DECLARE @CallerStaffKey         BIGINT;
    DECLARE @CallerAccessLevel      VARCHAR(50);
    DECLARE @AssessmentWindowID_BI  BIGINT;
    DECLARE @MathTaskKey_BI         BIGINT;
    DECLARE @ResultClean            VARCHAR(10)  = NULLIF(LTRIM(RTRIM(@Result)), '');
    DECLARE @ResultBit              BIT          = NULL;
    DECLARE @WindowStartDate        DATE;
    DECLARE @WindowEndDate          DATE;
    DECLARE @WindowMinGrade         VARCHAR(10);
    DECLARE @WindowMaxGrade         VARCHAR(10);
    DECLARE @WindowBenchmarkMonth   INT;
    DECLARE @WindowAssessmentType   VARCHAR(20);
    DECLARE @WindowStatus           VARCHAR(20);
    DECLARE @DominantMonth          INT;
    DECLARE @StudentKey             BIGINT;
    DECLARE @StudentGrade           VARCHAR(10);
    DECLARE @StudentGradeOrder      INT;
    DECLARE @MinGradeOrder          INT;
    DECLARE @MaxGradeOrder          INT;
    DECLARE @TaskGrade              VARCHAR(10);
    DECLARE @TaskMonth              INT;
    DECLARE @ExistingAssessmentID   BIGINT;
    DECLARE @Action                 VARCHAR(10);

    -- 51010: required-parameter NULL guard (@Result may be NULL = clear)
    IF @StudentNumber IS NULL OR @AssessmentWindowID IS NULL
       OR @MathTaskKey IS NULL OR @AssessmentDate IS NULL
    BEGIN
        ;THROW 51010, 'usp_UpsertMathAssessment: @StudentNumber, @AssessmentWindowID, @MathTaskKey and @AssessmentDate are required (no NULLs).', 1;
    END;

    -- 51019: @Result must be '0', '1', or a clear (NULL/empty)
    IF @ResultClean IS NOT NULL AND @ResultClean NOT IN ('0', '1')
    BEGIN
        ;THROW 51019, 'usp_UpsertMathAssessment: @Result must be ''0'', ''1'', or NULL/empty (to clear).', 1;
    END;
    SET @ResultBit = CASE @ResultClean WHEN '1' THEN 1 WHEN '0' THEN 0 END;

    SET @AssessmentWindowID_BI = CAST(@AssessmentWindowID AS BIGINT);
    SET @MathTaskKey_BI        = CAST(@MathTaskKey        AS BIGINT);

    -- 51030: caller resolves to a current DimStaff row
    SELECT TOP 1 @CallerStaffKey = StaffKey, @CallerAccessLevel = AccessLevel
    FROM DimStaff WHERE LOWER(Email) = @CallerEmail AND IsCurrent = 1;

    IF @CallerStaffKey IS NULL
    BEGIN
        ;THROW 51030, 'usp_UpsertMathAssessment: caller does not resolve to a current DimStaff row.', 1;
    END;

    -- 51012: window resolves and is active
    SELECT
        @WindowStartDate      = StartDate,
        @WindowEndDate        = EndDate,
        @WindowMinGrade       = MinGrade,
        @WindowMaxGrade       = MaxGrade,
        @WindowBenchmarkMonth = BenchmarkMonth,
        @WindowAssessmentType = AssessmentType
    FROM DimAssessmentWindow
    WHERE AssessmentWindowID = @AssessmentWindowID_BI AND ActiveFlag = 1;

    IF @WindowStartDate IS NULL
    BEGIN
        ;THROW 51012, 'usp_UpsertMathAssessment: @AssessmentWindowID does not resolve to an active DimAssessmentWindow row.', 1;
    END;

    -- 51015: this proc only handles Math windows
    IF @WindowAssessmentType <> 'Math'
    BEGIN
        ;THROW 51015, 'usp_UpsertMathAssessment: window AssessmentType is not Math. Use the matching upsert proc for Reading/Writing.', 1;
    END;

    -- 51032: Upcoming windows are not writeable (closed windows ARE — late entry)
    SET @WindowStatus =
        CASE WHEN @Today < @WindowStartDate THEN 'Upcoming'
             WHEN @Today > @WindowEndDate   THEN 'Closed'
             WHEN @Today = @WindowEndDate   THEN 'ClosesToday'
             ELSE 'Open' END;

    IF @WindowStatus = 'Upcoming'
    BEGIN
        ;THROW 51032, 'usp_UpsertMathAssessment: window is Upcoming (not yet started). No entries allowed before it opens.', 1;
    END;

    -- 51040: GRACE-LOCK (0.7.0). Past EndDate + the cycle's GraceHours (default 168h, from the close
    -- moment = midnight after EndDate), the window is LOCKED: read-only for everyone EXCEPT a caller
    -- holding the Math override (StaffAppAccess.CanOverrideMath) or IsSysAdmin. The boundary is
    -- hour-granular, so compare the Atlantic NOW timestamp, not @Today. @IsLocked drives the audit note.
    DECLARE @GraceHours INT, @LockBoundary DATETIME2(0), @IsLocked BIT = 0, @HasOverride BIT = 0;
    SELECT @GraceHours = COALESCE(sc.GraceHours, 168)
    FROM DimAssessmentWindow w
    LEFT JOIN DimShortCycle sc ON sc.CycleGroupID = w.CycleGroupID
    WHERE w.AssessmentWindowID = @AssessmentWindowID_BI;

    SET @LockBoundary = DATEADD(HOUR, COALESCE(@GraceHours, 168), CAST(DATEADD(DAY, 1, @WindowEndDate) AS DATETIME2(0)));
    IF CAST(GETDATE() AT TIME ZONE 'UTC' AT TIME ZONE 'Atlantic Standard Time' AS DATETIME2(0)) > @LockBoundary
        SET @IsLocked = 1;

    IF @IsLocked = 1
    BEGIN
        SELECT @HasOverride = CASE WHEN IsSysAdmin = 1 OR COALESCE(CanOverrideMath, 0) = 1 THEN 1 ELSE 0 END
        FROM StaffAppAccess WHERE LOWER(Email) = @CallerEmail;
        IF @HasOverride = 0
        BEGIN
            ;THROW 51040, 'usp_UpsertMathAssessment: this cycle is locked (grace period expired). You do not hold the Math override to enter data for it.', 1;
        END;
    END;

    -- 51017: AssessmentDate within [StartDate, MIN(today, EndDate)] (late entry bins into the window's month)
    IF @AssessmentDate < @WindowStartDate
       OR @AssessmentDate > CASE WHEN @Today < @WindowEndDate THEN @Today ELSE @WindowEndDate END
    BEGIN
        ;THROW 51017, 'usp_UpsertMathAssessment: @AssessmentDate is outside this window''s range [StartDate, min(today, EndDate)].', 1;
    END;

    -- 51011: student resolves via effective-date join on AssessmentDate
    SELECT TOP 1 @StudentKey = s.StudentKey, @StudentGrade = s.Grade
    FROM DimStudent s
    WHERE s.StudentNumber = @StudentNumber
      AND @AssessmentDate BETWEEN s.EffectiveStartDate AND COALESCE(s.EffectiveEndDate, '9999-12-31');

    IF @StudentKey IS NULL
    BEGIN
        ;THROW 51011, 'usp_UpsertMathAssessment: @StudentNumber does not resolve to a DimStudent row effective at @AssessmentDate.', 1;
    END;

    -- 51016: student grade within window's [MinGrade, MaxGrade]
    SELECT @StudentGradeOrder = GradeOrder FROM DimGrade WHERE GradeCode = @StudentGrade;
    SELECT @MinGradeOrder     = GradeOrder FROM DimGrade WHERE GradeCode = @WindowMinGrade;
    SELECT @MaxGradeOrder     = GradeOrder FROM DimGrade WHERE GradeCode = @WindowMaxGrade;

    IF @StudentGradeOrder IS NULL OR @MinGradeOrder IS NULL OR @MaxGradeOrder IS NULL
       OR @StudentGradeOrder NOT BETWEEN @MinGradeOrder AND @MaxGradeOrder
    BEGIN
        ;THROW 51016, 'usp_UpsertMathAssessment: student grade at AssessmentDate is outside the window grade range.', 1;
    END;

    -- 51013: task resolves and is active
    SELECT @TaskGrade = GradeCode, @TaskMonth = AssessmentMonth
    FROM DimMathTask WHERE MathTaskKey = @MathTaskKey_BI AND ActiveFlag = 1;

    IF @TaskGrade IS NULL
    BEGIN
        ;THROW 51013, 'usp_UpsertMathAssessment: @MathTaskKey does not resolve to an active DimMathTask row.', 1;
    END;

    -- Cycle's month: explicit BenchmarkMonth on the Short Cycle wins, else the dominant month.
    IF @WindowBenchmarkMonth IS NOT NULL
        SET @DominantMonth = @WindowBenchmarkMonth;
    ELSE
        SELECT TOP 1 @DominantMonth = Month
        FROM DimCalendar
        WHERE Date BETWEEN @WindowStartDate AND @WindowEndDate
        GROUP BY Month
        ORDER BY COUNT(*) DESC, Month;

    -- 51018: the task must belong to THIS student's grade and THIS cycle's month
    IF @TaskGrade <> @StudentGrade OR @TaskMonth <> @DominantMonth
    BEGIN
        ;THROW 51018, 'usp_UpsertMathAssessment: task is not applicable to this student/cycle (grade or month mismatch).', 1;
    END;

    -- =========================================================================
    -- UPSERT / CLEAR into FactAssessmentMath, grain (StudentKey, Window, Task, Date).
    -- =========================================================================
    SELECT @ExistingAssessmentID = MathAssessmentID
    FROM FactAssessmentMath
    WHERE StudentKey         = @StudentKey
      AND AssessmentWindowID = @AssessmentWindowID_BI
      AND MathTaskKey        = @MathTaskKey_BI
      AND AssessmentDate     = @AssessmentDate;

    IF @ResultClean IS NULL
    BEGIN
        -- CLEAR: remove this exact (student, window, task, date) mark if present.
        IF @ExistingAssessmentID IS NOT NULL
        BEGIN
            DELETE FROM FactAssessmentMath WHERE MathAssessmentID = @ExistingAssessmentID;
            SET @Action = 'CLEAR';
        END
        ELSE SET @Action = 'NOOP';
    END
    ELSE IF @ExistingAssessmentID IS NOT NULL
    BEGIN
        UPDATE FactAssessmentMath
        SET Result              = @ResultBit,
            EnteredByStaffKey   = @CallerStaffKey,
            SubmissionTimestamp = @Now,
            LastUpdated         = @Now
        WHERE MathAssessmentID = @ExistingAssessmentID;
        SET @Action = 'UPDATE';
    END
    ELSE
    BEGIN
        INSERT INTO FactAssessmentMath (
            StudentKey, AssessmentWindowID, MathTaskKey, Result,
            AssessmentDate, EnteredByStaffKey, SubmissionTimestamp, LastUpdated
        )
        VALUES (
            @StudentKey, @AssessmentWindowID_BI, @MathTaskKey_BI, @ResultBit,
            @AssessmentDate, @CallerStaffKey, @Now, @Now
        );
        SET @Action = 'INSERT';
    END;

    -- Audit row.
    INSERT INTO FactSubmissionAudit (
        RecordType, Source, SubmittedBy, SubmissionTimestamp, Status, Message, RecordCount, LastUpdated
    )
    VALUES (
        'MathAssessment',
        CASE WHEN @CallerUPN IS NOT NULL THEN 'WebApp' ELSE 'PowerApps' END,
        @CallerEmail,
        @Now,
        'Accepted',
        CONCAT(
            'usp_UpsertMathAssessment: ', @Action,
            ' | StudentNumber=',      CAST(@StudentNumber AS VARCHAR(20)),
            ' | AssessmentWindowID=', @AssessmentWindowID,
            ' | MathTaskKey=',        @MathTaskKey,
            ' | Result=',             COALESCE(@ResultClean, 'CLEAR'),
            CASE WHEN @IsLocked = 1 THEN ' | GRACE-OVERRIDE' ELSE '' END   -- 0.7.0: save into a locked cycle via override
        ),
        1,
        @Now
    );
END;
GO

-- Self-contained redeploy: DROP+CREATE drops the EXECUTE grant, so re-grant to the SP.
GRANT EXECUTE ON [dbo].[usp_UpsertMathAssessment] TO [StudentDataAssessment];
GO

/* ========== sql/procedures/usp_UpsertShortCycleHeader.sql ========== */
/*******************************************************************************
 * Procedure: usp_UpsertShortCycleHeader
 * Purpose: Create or edit a Short Cycle of Response HEADER (DimShortCycle) -- the
 *          display name + date range, identified by a distinct key (@CycleGroupID,
 *          an app-generated GUID). The per-subject/language/scope assessment
 *          instances (DimAssessmentWindow rows) tie to this key and INHERIT its
 *          dates. Editing the header here re-propagates the name/dates/year to all
 *          of the cycle's instance windows, so "set the dates once" stays true.
 * SCD Type: N/A (DimShortCycle managed manually)
 * Created: 2026-09-17
 * Region: Canada East (PIIDPA compliant)
 *
 * Authorization: enforced at the app layer (Manage-Cycles capability, server-side);
 *   this proc validates input only. Grant is to the web-app SP alone.
 *
 * THROW codes (user-fixable):
 *   51040  @CycleGroupID blank
 *   51041  @DisplayName blank
 *   51042  @EndDate < @StartDate (or a date is NULL)
 ******************************************************************************/

DROP PROCEDURE IF EXISTS dbo.usp_UpsertShortCycleHeader;
GO
CREATE PROCEDURE dbo.usp_UpsertShortCycleHeader
    @CycleGroupID VARCHAR(36),                 -- required; app generates a GUID for a new header
    @DisplayName  VARCHAR(100),
    @StartDate    DATE,
    @EndDate      DATE,
    @ActiveFlag   BIT          = 1,
    @GraceHours   INT          = NULL,          -- editable-after-close grace in HOURS; NULL -> keep existing / 168 default
    @CallerUPN    VARCHAR(255) = NULL           -- recorded as CreatedBy (audit)
AS
BEGIN
    SET NOCOUNT ON;

    IF @CycleGroupID IS NULL OR LTRIM(RTRIM(@CycleGroupID)) = ''
    BEGIN
        ;THROW 51040, 'usp_UpsertShortCycleHeader: @CycleGroupID is required.', 1;
    END;

    IF @DisplayName IS NULL OR LTRIM(RTRIM(@DisplayName)) = ''
    BEGIN
        ;THROW 51041, 'usp_UpsertShortCycleHeader: @DisplayName is required.', 1;
    END;

    IF @StartDate IS NULL OR @EndDate IS NULL OR @EndDate < @StartDate
    BEGIN
        ;THROW 51042, 'usp_UpsertShortCycleHeader: @EndDate must be on or after @StartDate.', 1;
    END;

    DECLARE @Y INT = YEAR(@StartDate), @M INT = MONTH(@StartDate);
    DECLARE @SchoolYear VARCHAR(9) =
        CASE WHEN @M >= 9 THEN CONCAT(@Y, '-', @Y + 1) ELSE CONCAT(@Y - 1, '-', @Y) END;
    DECLARE @Now DATETIME2(0) = GETDATE();

    IF EXISTS (SELECT 1 FROM DimShortCycle WHERE CycleGroupID = @CycleGroupID)
    BEGIN
        UPDATE DimShortCycle
        SET DisplayName = @DisplayName, StartDate = @StartDate, EndDate = @EndDate,
            SchoolYear = @SchoolYear, ActiveFlag = @ActiveFlag,
            GraceHours = COALESCE(@GraceHours, GraceHours, 168), LastUpdated = @Now
        WHERE CycleGroupID = @CycleGroupID;

        -- Keep the cycle's instance windows in sync (name/dates/year live once on the header).
        UPDATE DimAssessmentWindow
        SET WindowName = @DisplayName, StartDate = @StartDate, EndDate = @EndDate,
            SchoolYear = @SchoolYear, LastUpdated = @Now
        WHERE CycleGroupID = @CycleGroupID;
    END
    ELSE
    BEGIN
        INSERT INTO DimShortCycle (CycleGroupID, DisplayName, StartDate, EndDate, SchoolYear, ActiveFlag, GraceHours, CreatedDate, CreatedBy, LastUpdated)
        VALUES (@CycleGroupID, @DisplayName, @StartDate, @EndDate, @SchoolYear, @ActiveFlag, COALESCE(@GraceHours, 168), @Now, @CallerUPN, @Now);
    END;

    SELECT CycleGroupID, DisplayName, StartDate, EndDate, SchoolYear, ActiveFlag, GraceHours
    FROM DimShortCycle WHERE CycleGroupID = @CycleGroupID;
END;
GO

GRANT EXECUTE ON dbo.usp_UpsertShortCycleHeader TO [StudentDataAssessment];
GO

/* ========== sql/procedures/usp_SetStaffAppAccess.sql ========== */
/*******************************************************************************
 * Procedure: usp_SetStaffAppAccess
 * Purpose: The SOLE writer of StaffAppAccess — upserts one staff email's five
 *          app-capability flags (IsSysAdmin, CanManageCycles, CanRunIngest,
 *          CanOverrideMath, CanOverrideLiteracy). Backs the SysAdmin-only
 *          /admin/staff-access grant GUI (0.7.0). Re-checks the caller is a
 *          SysAdmin SERVER-SIDE — the page/nav gate is convenience, not the
 *          authority, so a stale client or a direct call can't grant itself power.
 * Created: 2026-09-24
 * Region: Canada East (PIIDPA compliant)
 *
 * A SysAdmin CAN grant SysAdmin to another user (small-team bootstrap; the GUI
 * confirms first). Email is stored lowercased. Fabric has no MERGE, so this is an
 * IF EXISTS UPDATE / ELSE INSERT. A save that clears ALL five flags DELETEs the row
 * instead (removes the person from the access list — automated house-cleaning; the
 * last-sysadmin guard still applies). Every change writes a FactSubmissionAudit row.
 *
 * THROW codes:
 *   51010  a required parameter is NULL / @TargetEmail blank
 *   51050  caller is not a SysAdmin
 *   51051  would remove the LAST SysAdmin (never allowed — grant sysadmin to someone else first)
 ******************************************************************************/

DROP PROCEDURE IF EXISTS usp_SetStaffAppAccess;
GO

CREATE PROCEDURE usp_SetStaffAppAccess
    @TargetEmail          VARCHAR(255),
    @IsSysAdmin           BIT,
    @CanManageCycles      BIT,
    @CanRunIngest         BIT,
    @CanOverrideMath      BIT,
    @CanOverrideLiteracy  BIT,
    @CallerUPN            VARCHAR(255) = NULL   -- signed-in SysAdmin UPN; NULL -> CURRENT_USER
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @Now              DATETIME2(0) = GETDATE();
    DECLARE @CallerEmail      VARCHAR(255) = LOWER(COALESCE(@CallerUPN, CURRENT_USER));
    DECLARE @Target           VARCHAR(255) = LOWER(LTRIM(RTRIM(@TargetEmail)));
    DECLARE @CallerIsSysAdmin BIT = 0;

    -- 51010: required-parameter guard
    IF NULLIF(@Target, '') IS NULL
       OR @IsSysAdmin IS NULL OR @CanManageCycles IS NULL OR @CanRunIngest IS NULL
       OR @CanOverrideMath IS NULL OR @CanOverrideLiteracy IS NULL
    BEGIN
        ;THROW 51010, 'usp_SetStaffAppAccess: @TargetEmail and all five capability flags are required.', 1;
    END;

    -- 51050: caller must be a SysAdmin (re-checked here; the page gate is NOT the authority)
    SELECT @CallerIsSysAdmin = CASE WHEN IsSysAdmin = 1 THEN 1 ELSE 0 END
    FROM StaffAppAccess WHERE LOWER(Email) = @CallerEmail;

    IF COALESCE(@CallerIsSysAdmin, 0) = 0
    BEGIN
        ;THROW 51050, 'usp_SetStaffAppAccess: caller is not a SysAdmin — cannot change app access.', 1;
    END;

    -- 51051: never let a save drop the system to ZERO SysAdmins. Blocks demoting the LAST sysadmin
    -- (the target is currently a sysadmin, is being set to non-sysadmin, and is the only one) — which
    -- would lock everyone out of access administration.
    IF @IsSysAdmin = 0
       AND EXISTS (SELECT 1 FROM StaffAppAccess WHERE LOWER(Email) = @Target AND IsSysAdmin = 1)
       AND (SELECT COUNT(*) FROM StaffAppAccess WHERE IsSysAdmin = 1) <= 1
    BEGIN
        ;THROW 51051, 'usp_SetStaffAppAccess: cannot remove the last System Administrator. Grant SysAdmin to someone else first.', 1;
    END;

    -- REMOVE from the access list: a save that clears EVERY capability deletes the row (automated
    -- house-cleaning — there is no separate delete button; you clear the roles and Save). The 51051
    -- guard above already blocks doing this to the last sysadmin. A no-op if no row exists (e.g. a
    -- staff member who was added-by-email but never granted anything).
    IF @IsSysAdmin = 0 AND @CanManageCycles = 0 AND @CanRunIngest = 0
       AND @CanOverrideMath = 0 AND @CanOverrideLiteracy = 0
    BEGIN
        DELETE FROM StaffAppAccess WHERE LOWER(Email) = @Target;

        INSERT INTO FactSubmissionAudit
            (RecordType, Source, SubmittedBy, SubmissionTimestamp, Status, Message, RecordCount, LastUpdated)
        VALUES
            ('StaffAppAccess', 'WebApp', @CallerEmail, @Now, 'Accepted',
             CONCAT('usp_SetStaffAppAccess: REMOVED ', @Target, ' (all capabilities cleared)'), 1, @Now);
        RETURN;
    END;

    -- Upsert (Fabric has no MERGE).
    IF EXISTS (SELECT 1 FROM StaffAppAccess WHERE LOWER(Email) = @Target)
    BEGIN
        UPDATE StaffAppAccess
        SET IsSysAdmin          = @IsSysAdmin,
            CanManageCycles     = @CanManageCycles,
            CanRunIngest        = @CanRunIngest,
            CanOverrideMath     = @CanOverrideMath,
            CanOverrideLiteracy = @CanOverrideLiteracy,
            LastUpdated         = @Now
        WHERE LOWER(Email) = @Target;
    END
    ELSE
    BEGIN
        INSERT INTO StaffAppAccess
            (Email, IsSysAdmin, CanManageCycles, CanRunIngest, CanOverrideMath, CanOverrideLiteracy, LastUpdated)
        VALUES
            (@Target, @IsSysAdmin, @CanManageCycles, @CanRunIngest, @CanOverrideMath, @CanOverrideLiteracy, @Now);
    END;

    INSERT INTO FactSubmissionAudit
        (RecordType, Source, SubmittedBy, SubmissionTimestamp, Status, Message, RecordCount, LastUpdated)
    VALUES
        ('StaffAppAccess', 'WebApp', @CallerEmail, @Now, 'Accepted',
         CONCAT('usp_SetStaffAppAccess: ', @Target,
                ' | SysAdmin=',  @IsSysAdmin,  ' Cycles=', @CanManageCycles, ' Ingest=', @CanRunIngest,
                ' MathOvr=',     @CanOverrideMath, ' LitOvr=', @CanOverrideLiteracy),
         1, @Now);
END;
GO

-- Self-contained redeploy: DROP+CREATE drops the EXECUTE grant, so re-grant to the SP.
GRANT EXECUTE ON [dbo].[usp_SetStaffAppAccess] TO [StudentDataAssessment];
GO

