#!/usr/bin/env bash
# generate_live_deploy.sh — bundle the 0.5.0 LIVE deploy into a few staged files.
# Faithful concatenation of tracked sql/ sources (no transcription). Run from repo root.
# Output: sql/deploy/live_0.5.0/NN_*.sql  — run each stage IN ORDER, in the Fabric editor.
#
# Live is at 0.4.1, so this is INCREMENTAL: 0.5.0 migrations, then 0.5.0-new tables, then ALL
# programmable objects redeployed (DROP/CREATE, safer parity), then grants. DEV FIRST (runbook §3).
#
# DELIBERATELY EXCLUDED — the 5 PowerSchool COPY INTO loaders (usp_Load{Students,Staff,Section,
# Enrollment,CoTeacher}Staging): the repo has the not-yet-deployed CSV-cutover version; LIVE still
# runs the TAB format, so redeploying them would break live ingest. They are NOT part of 0.5.0.
# (They also lack GO terminators — a separate source cleanup.) usp_LoadMathTasks IS new + safe → included.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=sql/deploy/live_0.5.0
mkdir -p "$OUT"
rm -f "$OUT"/*.sql

emit () {  # $1=outfile  $2=title  $3..=source files
  local out="$OUT/$1"; local title="$2"; shift 2
  { echo "/* ============================================================================";
    echo "   $title";
    echo "   GENERATED by scripts/generate_live_deploy.sh — do not hand-edit; edit sources + regen.";
    echo "   0.5.0 live deploy. Run DEV first. Run stages in filename order.";
    echo "   ============================================================================ */";
    echo; } > "$out"
  for f in "$@"; do
    if [[ ! -f "$f" ]]; then echo "!! MISSING: $f" >&2; echo "/* !! MISSING SOURCE: $f */" >> "$out"; continue; fi
    { echo "/* ========== $f ========== */"; cat "$f"; } >> "$out"
    # Ensure the file's batch is terminated: add a GO only if it doesn't already end with one.
    local last; last=$(grep -vE '^[[:space:]]*$' "$f" | tail -n1 | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')
    if [[ "$last" != "GO" ]]; then printf '\nGO\n' >> "$out"; fi
    echo >> "$out"
  done
  echo "wrote $out ($(grep -c . "$out") non-empty lines)"
}

# --- 01: migrations that change EXISTING live tables (0.5.0 only; idempotent-guarded) ---
emit 01_migrations.sql "STAGE 01 — schema migrations on existing live tables (idempotent)" \
  sql/scripts/migrate_DimProgram_add_ScopeBucket.sql \
  sql/scripts/migrate_DimAssessmentWindow_add_AssessmentLanguage.sql \
  sql/scripts/migrate_DimAssessmentWindow_add_CycleGroupID.sql \
  sql/scripts/migrate_FactWriting_conventions_varchar.sql \
  sql/scripts/migrate_FactWriting_add_AssessmentLanguage.sql \
  sql/scripts/migrate_FactAssessmentReading_add_score_context.sql \
  sql/scripts/migrate_FactAssessmentWriting_add_average.sql

# --- 02: tables NEW in 0.5.0 (+ their seeds/backfills) ---
emit 02_new_tables.sql "STAGE 02 — tables new in 0.5.0 (+ seeds/backfills)" \
  sql/dimensions/DimCourseAssessment.sql \
  sql/scripts/seed_DimCourseAssessment_live.sql \
  sql/dimensions/DimShortCycle.sql \
  sql/scripts/backfill_DimShortCycle_headers.sql \
  sql/dimensions/DimMathComprehensionBand.sql \
  sql/scripts/seed_DimMathComprehensionBand.sql \
  sql/dimensions/DimMathTask.sql \
  sql/staging/Stg_MathTask.sql \
  sql/facts/FactAssessmentMath.sql \
  sql/facts/FactStudentAdaptation.sql \
  sql/security/AppMaintenance.sql

# --- 03: procedures (DROP/CREATE parity). Excludes the 5 PS loaders; includes usp_LoadMathTasks. ---
emit 03_procedures.sql "STAGE 03 — procedures (DROP/CREATE; full parity)" \
  sql/procedures/usp_LoadMathTasks.sql \
  sql/procedures/usp_MergeStudent.sql \
  sql/procedures/usp_MergeStaff.sql \
  sql/procedures/usp_MergeSection.sql \
  sql/procedures/usp_MergeEnrollment.sql \
  sql/procedures/usp_MergeSectionTeachers.sql \
  sql/procedures/usp_RunDataQualityChecks.sql \
  sql/procedures/usp_RunFullIngestCycle.sql \
  sql/procedures/usp_TriggerIngestCycle.sql \
  sql/procedures/usp_YearEndCloseOut.sql \
  sql/procedures/usp_GenerateMonthlyWindows.sql \
  sql/procedures/usp_InsertSubmissionAudit.sql \
  sql/procedures/usp_UpsertReadingAssessment.sql \
  sql/procedures/usp_DeleteReadingAssessment.sql \
  sql/procedures/usp_UpsertWritingAssessment.sql \
  sql/procedures/usp_UpsertMathAssessment.sql \
  sql/procedures/usp_UpsertStudentIPP.sql \
  sql/procedures/usp_UpsertStudentAdaptation.sql \
  sql/procedures/usp_UpsertShortCycle.sql \
  sql/procedures/usp_UpsertShortCycleHeader.sql \
  sql/procedures/usp_SetMaintenanceWindow.sql \
  sql/procedures/usp_ClearMaintenanceWindow.sql

# --- 04: views (DROP/CREATE parity) ---
emit 04_views.sql "STAGE 04 — views (DROP/CREATE; full parity)" \
  sql/security/vw_TeacherStudents.sql \
  sql/security/vw_SchoolStudents.sql \
  sql/security/vw_RegionalData.sql \
  sql/security/vw_UserAssessmentWindows.sql \
  sql/security/vw_TeacherGroups.sql \
  sql/security/vw_TeacherRoster.sql \
  sql/security/vw_StudentCohort.sql \
  sql/security/vw_StudentAssessmentHistory.sql \
  sql/security/vw_StudentIPP.sql \
  sql/security/vw_StudentCohortTeachers.sql \
  sql/security/vw_DimReadingScale.sql \
  sql/security/vw_StudentReadingStartingPoint.sql

# --- 05: table-valued functions (DROP/CREATE parity) ---
emit 05_tvfs.sql "STAGE 05 — table-valued functions (DROP/CREATE; full parity)" \
  sql/security/tvf_UserAssessmentWindows.sql \
  sql/security/tvf_TeacherGroups.sql \
  sql/security/tvf_TeacherRoster.sql \
  sql/security/tvf_TeacherRosterWriting.sql \
  sql/security/tvf_TeacherRosterMath.sql \
  sql/security/tvf_StudentCohort.sql \
  sql/security/tvf_StudentCohortWriting.sql \
  sql/security/tvf_StudentAssessmentHistory.sql \
  sql/security/tvf_StudentAssessmentHistoryWriting.sql \
  sql/security/tvf_StudentIPP.sql \
  sql/security/tvf_StudentAdaptation.sql \
  sql/security/tvf_ProgrammingGroups.sql \
  sql/security/tvf_ProgrammingRoster.sql

# --- 06: master grant (run last) ---
emit 06_grants.sql "STAGE 06 — master grant (run last)" \
  sql/security/grant_webapp_sp.sql

echo "---- done. review $OUT/ ----"
