#!/usr/bin/env bash
# generate_live_deploy_0.7.0.sh — bundle the 0.7.0 LIVE deploy into staged files.
# Faithful concatenation of tracked sql/ sources (no transcription). Run from repo root.
# Output: sql/deploy/live_0.7.0/NN_*.sql — run each stage IN ORDER, in the Fabric editor.
#
# Live is at 0.6.3, so this is INCREMENTAL: 0.7.0 schema migration first (grace + overrides on
# EXISTING tables), then the changed programmable objects (procs, then TVFs) via DROP/CREATE, then
# an explicit grants stage. DEV FIRST.
#
# WHY a grants stage: usp_UpsertReadingAssessment is DROP/CREATE with no inline GRANT, so it loses
# EXECUTE on redeploy — the SP would then fail every reading save. Stage 06 re-grants every object
# (idempotent; the TVFs + the other procs also self-grant, so this is belt-and-suspenders).
#
# EXCLUDED: the PowerSchool COPY INTO loaders (unchanged in 0.7.0; live parity concerns as in 0.5.0).
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=sql/deploy/live_0.7.0
mkdir -p "$OUT"
rm -f "$OUT"/*.sql

emit () {  # $1=outfile  $2=title  $3..=source files
  local out="$OUT/$1"; local title="$2"; shift 2
  { echo "/* ============================================================================";
    echo "   $title";
    echo "   GENERATED by scripts/generate_live_deploy_0.7.0.sh — do not hand-edit; edit sources + regen.";
    echo "   0.7.0 live deploy (live is at 0.6.3). Run DEV first. Run stages in filename order.";
    echo "   ============================================================================ */";
    echo; } > "$out"
  for f in "$@"; do
    if [[ ! -f "$f" ]]; then echo "!! MISSING: $f" >&2; echo "/* !! MISSING SOURCE: $f */" >> "$out"; continue; fi
    { echo "/* ========== $f ========== */"; cat "$f"; } >> "$out"
    local last; last=$(grep -vE '^[[:space:]]*$' "$f" | tail -n1 | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')
    if [[ "$last" != "GO" ]]; then printf '\nGO\n' >> "$out"; fi
    echo >> "$out"
  done
  echo "wrote $out ($(grep -c . "$out") non-empty lines)"
}

# --- 01: schema migration on EXISTING live tables (idempotent, guarded) ---
emit 01_migrations.sql "STAGE 01 — 0.7.0 schema migration (grace + overrides; idempotent)" \
  sql/scripts/migrate_0.7.0_grace_and_overrides.sql

# --- 03: procedures changed in 0.7.0 (DROP/CREATE parity) ---
emit 03_procedures.sql "STAGE 03 — procedures changed in 0.7.0 (DROP/CREATE)" \
  sql/procedures/usp_UpsertReadingAssessment.sql \
  sql/procedures/usp_UpsertWritingAssessment.sql \
  sql/procedures/usp_UpsertMathAssessment.sql \
  sql/procedures/usp_UpsertShortCycleHeader.sql \
  sql/procedures/usp_SetStaffAppAccess.sql

# --- 05: table-valued functions changed/new in 0.7.0 (DROP/CREATE) ---
emit 05_tvfs.sql "STAGE 05 — TVFs changed/new in 0.7.0 (DROP/CREATE)" \
  sql/security/tvf_UserAssessmentWindows.sql \
  sql/security/tvf_TeacherGroups.sql \
  sql/security/tvf_StudentCohort.sql \
  sql/security/tvf_StudentAssessmentHistory.sql \
  sql/security/tvf_MathCohortGroups.sql \
  sql/security/tvf_StudentCohortMath.sql \
  sql/security/tvf_StudentCohortRWM.sql \
  sql/security/tvf_StudentRWMHistory.sql

# --- 06: explicit grants (idempotent; required for usp_UpsertReadingAssessment) ---
emit 06_grants.sql "STAGE 06 — grants to StudentDataAssessment (idempotent)" \
  sql/deploy/_grants_0.7.0.sql

echo "DONE. Stages in $OUT — run 01 → 03 → 05 → 06, DEV first."
