/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by Next.js. It is committed here so a fresh
// `tsc --noEmit` works before the first `next build`. Do not edit.
